### ISSUE TITLE
Error during bun install on Windows [bunsh: No such file or directory]

### ISSUE THREAD

**Issue by coyjiv** [oven-sh/bun#10398]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### Install Bun using this command

`powershell -c "irm bun.sh/install.ps1|iex"`

#### Try bootstraping t4-app

`bun create t4-app@2.4.1`

![image](https://github.com/oven-sh/bun/assets/33584261/3f918901-8b83-4177-a564-3a13d90cd264)

### What is the expected behavior?

Command execution should end successfully with no errors

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/33584261/299d2985-594f-4a02-9583-902a88db9184)

### Additional information

Some info from t4-app discord channel 
![image](https://github.com/oven-sh/bun/assets/33584261/88419bae-40e4-444d-ab8c-7865ac024473)

**Comment by Jorgemacias-12** [comment]
I have the same issue, I'm trying to install depedencies on a backend project, and when I ran bun run dev, I got this message too:
![image](https://github.com/oven-sh/bun/assets/63885983/877335cd-777e-42e4-a695-6d89cd6e4121)
It's strange because, the command only fails on my laptop.

Version of bun:
`1.1.4+fbe2fe0c3`

Platform: 
`Microsoft Windows NT 10.0.22631.0 x64
`

I left here my package.json:

```JSON
{
  "name": "redacted",
  "module": "server",
  "type": "module",
  "devDependencies": {
    "@types/bun": "^1.1.0",
    "@types/cors": "^2.8.17",
    "@types/express": "^4.17.21",
    "@types/swagger-ui-express": "^4.1.6",
    "@types/helmet": "^4.0.0",
    "@types/morgan": "^1.9.9",
    "prisma": "^5.12.1",
    "express-validator": "^7.0.1"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "@prisma/client": "^5.12.1",
    "cors": "^2.8.5",
    "express": "^4.19.2",
    "helmet": "^7.1.0",
    "moment": "^2.30.1",
    "morgan": "^1.10.0",
    "swagger-ui-express": "^5.0.0",
    "tsoa": "^6.2.0"
  },
  "scripts": {
    "dev": "bun --watch ./server.ts",
    "build": "bun build --target=bun ./server.ts --outdir ./build",
    "predev": "bun swagger || true",
    "prebuild": "bun swagger || true",
    "swagger": "bun tsoa spec"
  },
  "prisma": {
    "schema": "./src/db/schema.prisma"
  }
}
```

On my computer I have:

Version of bun:
`1.1.3+2615dc742`

Windows version:
`Microsoft Windows NT 10.0.22631.0 x64`
