### ISSUE TITLE
bun install -g <pacakge> THROWS ERRORS

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#10514]
### What version of Bun is running?

1.1.4

### What steps can reproduce the bug?

when I try to install pacakges globally in bun as I do normally with npm, it throws this error:

```sh
# bun install -g express
bun add v1.1.4 (fbe2fe0c)
[2.39ms] migrated lockfile from package-lock.json
  🔍 content-type [5/25] Illegal instruction at address 0x7ff79f302ce1
???:?:?: 0x7ff79f302f7f in ??? (bun.exe)
???:?:?: 0x7ff79e82f57e in ??? (bun.exe)
???:?:?: 0x7ff79e744554 in ??? (bun.exe)
???:?:?: 0x7ff79e74d79a in ??? (bun.exe)
???:?:?: 0x7ff79e984773 in ??? (bun.exe)
???:?:?: 0x7ffb16de53df in ??? (KERNEL32.DLL)
???:?:?: 0x7ffb1726485a in ??? (ntdll.dll)
```

**Comment by Calemy** [comment]
can't recreate this personally using the same version using bun install -g pm2

**Comment by Bader-Idris** [comment]
# assumption

I have installed bun through both npm and PowerShell, though it might cause those issues

## wishing

bun developers, please combine both of installations; or remove the conflicts caused by having both of them

**Comment by sohaieb** [comment]
Hi @Bader-Idris , 
as far as I know: to install a package in BunJs, you have to use `bun add -g <package-name>` instead
`bun install` command is used only when you want to install a project depencies that have already a package.json filled with some registred dependencies.
Please check [bun add](https://bun.sh/docs/cli/add) and [bun install](https://bun.sh/docs/cli/install) documentations.

**Comment by Bader-Idris** [comment]
Same error

**Comment by sohaieb** [comment]
Was your project created using Bun from the start, or was it an npm project that you migrated to Bun?

also can you try this workaround:
1. delete your package-lock.json
2. delete your node_modules folder
3. run bun init and follow the instructions
4. check if express exists in your package.json file, if it does not existe then run `bun add express` (be sure to run this without the flag `-g` express should not be a global package at all)
5. run your project and see if this works

**Comment by Bader-Idris** [comment]
My man, it's not because of a mistake that I made, Bun is under development, and many other developers get the same/or similar problems, especially because of the variety of hardware differences, and I keep reporting them to notify its developers of its exists, it's as our neuro system, it says I'M SENSING AN ISSUE RIGHT NOW 📛 to our minds

**Comment by sohaieb** [comment]
@Bader-Idris 
### **No one here said that you made a mistake at all.**
I'm agree with your point about Bun, yes it is under development and that's why **WE ARE HERE**. However reporting things should not be in a blind way. It should always passes by a "**reproducing phase**" to make people aware about the steps you made and the environment you worked on. This will help everybody to understand more about your issue, to help you or to make PRs for a fix.
So overal, my goal with my comments above, is simply:
- To help to get more details and the reproduced steps,to reduce its technical scope. This will make it easier for others to investigate and fix. 
- To support everybody and specially others who, faced or will face the same issue, to get more insights about the reproduced steps. 
- To match the issue with the same development environment, knowing that you did not provide any furhter information neither necessary details about your computer system environement which makes sense for any interested person to either ask a lot of questions or to try to give you hints to support you.

BR.
