### ISSUE TITLE
Crash on Nuxt hot reload

### ISSUE THREAD

**Issue by Soulusions** [oven-sh/bun#10708]
### How can we reproduce the crash?

Crash happens when hot reloading nuxtjs, specifically when server code gets hot reloaded.

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on linux x86_64 [RunCommand]

Bus error at address 0x7FE4E80EC000

- [`ld-temp.o:0`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/ld-temp.o#L0): `WTF::Unicode::convertUTF16ToUTF8`

Features: Bun.stdin, transpiler_cache

**Comment by nic9347** [comment]
Having the same problem on Bun v1.1.7. Seems to only be present with server code hot reload, not though when client code gets changed. I have tried earlier Versions of Bun, e.g. v1.1.0 seems to have had the same problem. Node doesn't seem to have this problem.

**Comment by Jarred-Sumner** [comment]
There's probably an 80% chance this was fixed in https://github.com/oven-sh/bun/pull/11635 and https://github.com/oven-sh/bun/pull/11494, as it sounds similar to other issues but it's hard to say for sure unless you run into it in a more recent build of Bun. There were some bugs in the stacktraces of that version of Bun.

The fix will land in Bun v1.1.13, but you can try it in canary `bun upgrade --canary` until then. If you still run into this issue, please let us know and I'll re-open the issue.
