### ISSUE TITLE
net's onread doesn't work as intended

### ISSUE THREAD

**Issue by soitchu** [oven-sh/bun#10719]
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Linux 6.8.1-arch1-1-surface x86_64 unknown

### What steps can reproduce the bug?

Run the following code:

```
const net = require("net");
const opts = {
	host: "localhost",
	port: 143,
	onread: {
		buffer: Buffer.allocUnsafe(4096),
		callback: (size, buf) => {
			console.log(size);
		}
	}
};

net.connect(opts, () => console.log("Connected"));
```

### What is the expected behavior?

onread's callback should be called when the socket receives data.

### What do you see instead?

onread's callback is never called.

### Additional information

The code works fine if node.js is used to run it. The documentation for this behavior can be found [here](https://nodejs.org/api/net.html#socketconnectoptions-connectlistener).

**Comment by uasan** [comment]
The behavior in PR https://github.com/oven-sh/bun/pull/10753  is different from Node.js, you have not implemented the option when in addition to the callback a second buffer property is passed and this is a function that returns the buffer, it is in this form that this interface makes sense, because it easily allows you to implement a ring buffer (BYOB) based on one buffer.

From Node.js docs:

buffer: Buffer | Uint8Array | Function Either a reusable chunk of memory to use for storing incoming data or a function that returns such.

P.S.
I tested in bun 1.2
