### ISSUE TITLE
Huge file produced by bun build --compile

### ISSUE THREAD

**Issue by Zibri** [oven-sh/bun#10958]
94 MB for a program that opens a websocket and speaks to it seems HUGE to me. :(

bun build test.js --compile --outfile test

**Comment by akirarika** [comment]
This is because the 94 MB actually includes Bun itself. Unfortunately, almost all executable files packaged with JavaScript languages have large file sizes because they need to include the runtime, which is almost always difficult to trim down. For example, Electron, Node.js v20, and Deno, although they vary in size, always exceed 50MB.
