### ISSUE TITLE
Support IPC in bun package.json script runner

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#11132]
### What is the problem this feature would solve?

package.json
```json
{ "scripts": { "mycoolscript":"bun ./child.js"}}
```

./child.js
```js
process.send('hello')
```

parent.js
```js
Bun.spawn(['bun', 'mycoolscript'], {
  ipc(message) {
    console.info(message) // hello
  }
})
```

### What is the feature you are proposing to solve the problem?

Make bun script runner as IPC proxy

**Comment by TiBianMod** [comment]
https://bun.sh/guides/process/ipc

**Comment by Jarred-Sumner** [comment]
To any contributors who want to do this:
- An environment variable is used to inform the other process about IPC
- In Bun, file descriptors are not inherited when a process spawns (we try to prevent leaking file descriptors as much as possible) which means we mark the IPC file descriptor as "close-on-exec". 
- The fix is to make the codepaths which do `bun run <package.json script>` and `bun <package.json script>` add the IPC file descriptor as `.inherit` in the Stdio options if the environment variable exists. Most of this code is in [`src/cli/run_command.zig`](https://github.com/oven-sh/bun/blob/main/src/cli/run_command.zig)

**Comment by lpessoa** [comment]
Can I have a go at this one? been looking to jump in the zig bandwagon for some time 😄
