### ISSUE TITLE
Postinstall not blocked when installing @swc/core

### ISSUE THREAD

**Issue by lcswillems** [oven-sh/bun#11396]
### What version of Bun is running?

1.0.31+e25675121

### What platform is your computer?

Linux

### What steps can reproduce the bug?

```
$ bun install @swc/core

test-bun-postinstall$ bun install @swc/core
bun add v1.0.31 (e2567512)

 installed @swc/core@1.5.7

[12.00ms] done
```

### What is the expected behavior?

When I install other packages that have postinstall scripts, the postinstall is blocked:

```
test-bun-postinstall$ bun install xsuite
bun add v1.0.31 (e2567512)

 installed xsuite@0.0.60 with binaries:
  - xsuite

 81 packages installed [6.47s]

 Blocked 1 postinstall. Run `bun pm untrusted` for details.
```

**Comment by Polygons1** [comment]
I think it's because @swc/core is trusted by bun by default

**Comment by lcswillems** [comment]
What's the point of trusting some but not others? Is it based on the list? How frequent is the list updated?

**Comment by Electroid** [comment]
We maintain the default list of trusted dependencies here: https://github.com/oven-sh/bun/blob/main/src/install/default-trusted-dependencies.txt

We added the ~500 most depended on packages that use postinstall scripts to the list, for convenience.

If you do not want to trust these dependencies, you can explicitly set the `trustedDependencies` list in your package.json. If specified, it will pull from that list instead of the default.

```jsonc
{
  // trust nothing
  "trustedDependencies": []
}
```

```jsonc
{
  // trust only esbuild, not anything in the default list
  "trustedDependencies": ["esbuild"]
}
```

**Comment by lcswillems** [comment]
@Electroid The list has not been updated in 4 months...
