### ISSUE TITLE
Bun does not end after closing mysql2 pool

### ISSUE THREAD

**Issue by Dovonun** [oven-sh/bun#11414]
### What version of Bun is running?

1.1.10+5102a9443

### What platform is your computer?

Linux 6.8.0-31-generic x86_64 x86_64

### What steps can reproduce the bug?

This is the simplest example of where I saw this behavior.
Without using the pool(no query), Bun exits as expected.
```javascript
import mysql from "mysql2/promise";

const pool = mysql.createPool({
  uri: process.env.DATABASE_URL,
  database: 'tower',
  waitForConnections: true,
  connectionLimit: 10,
  maxIdle: 10,
  idleTimeout: 60000,
  queueLimit: 0,
  enableKeepAlive: true,
  keepAliveInitialDelay: 0,
});

const test = await pool.query('select 1 from dual where 1=1');
console.log(test);

pool.end();
```

### What is the expected behavior?

Exit after everything is executed.

### What do you see instead?

Bun does not exit.
![image](https://github.com/oven-sh/bun/assets/31408384/08059451-7bcb-47c4-b484-fcfc67c4f619)

**Comment by wellwelwel** [comment]
If you think there's something that could be done from **MySQL2** side, please ping me.

Currently, all **MySQL2** test suite runs _against_ **Node.js** and **Deno**, but due to this reported behavior, we only perform a basic `SELECT` test with **Bun** using a workaround to force the process exit:

```js
connection.end((err) => { 
  assert.ifError(err); 
  process.exit(0); 
}); 
```

---

In addition, 100% of the test suite passes with **Bun** if we ignore this problem.

**Comment by Tanavya** [comment]
Might be related to this issue: https://github.com/oven-sh/bun/issues/12155
