### ISSUE TITLE
@auth/core not working

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#11461]
### What version of Bun is running?

1.1.10-canary.1+4b8f89cb7

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

This is a vite (vinxi) app, and at dev-time everything is fine, but when previewing a build of my app I get a:

```sh

$ bun --env-file=.env .output/server/index.mjs

│ error: Cannot find package "jose" from "/Users/admin/repos/project/.output/server/node_modules/@auth/core/jwt.js"
│ 
```

As mentioned in this ticket, when jose isn't used directly, bun is breaking
- https://github.com/panva/jose/issues/471

**Comment by ghyath5** [comment]
I'm facing the same issue now

`bun --bun .output/server/index.mjs
Listening on http://[::]:3000
[nuxt] [request error] [unhandled] [500] Cannot find package "jose" from ".output/server/chunks/routes/api/auth/_..._.mjs"
  at new H3Error (./.output/server/chunks/runtime.mjs:1922:4)  
  at createError$1 (./.output/server/chunks/runtime.mjs:1955:26)  
  at <anonymous> (./.output/server/chunks/runtime.mjs:3420:25)  
  at processTicksAndRejections (:12:39)`
  
  
  is it because of @auth/core is using `crypto` which is not fully supported by bun yet!

**Comment by birkskyum** [comment]
@ghyath5 , does it work for you now?

**Comment by luksch42** [comment]
@birkskyum Did you solve this? I'm experiencing this with TanStack Start (Vite/Vinxi) and better-auth
