### ISSUE TITLE
Will Bun be spec-compatible or not?

### ISSUE THREAD

**Issue by sahithyandev** [oven-sh/bun#11571]
Reason: https://x.com/jarredsumner/status/1797306398633779331?t=46Wimo8j3e7nmahtB6yrug&s=09
... And some other tweets of Jarred Sumner.

Some recent tweets from Jarred Sumner (an engineer working on Bun), captioned "thinking out loud", include code snippets that break well-established specs. And we have concerns with using Bun as we are unsure regarding whether the specs will be followed or nto.

![20240603_232908.jpg](https://github.com/oven-sh/bun/assets/29434759/928ce3e4-5483-4150-8a62-adfe75591916)

The above code snippet is from Jarred Sumner's tweet (linked above). He is extending the fetch function (which is well established) with non standard options. As he is an engineer working on Bun, many of us raised concerns of this feature landing on Bun. As far as I know he did not respond to any of the concerns. I am creating this issue to discuss and make decisions regarding those concerns.

I know Bun is your (you, your = Oven) software, and you can do whatever you want with it. But we, the JavaScript community, needs your stand on "being spec-compatible". We are expecting a clear response from your side. You can just omit our request and close this issue if you wish.

**Comment by Electroid** [comment]
Hi there! As Jarred mentioned in his tweet, these are personal ideas of his and we will not necessarily be implementing them.

Regarding your concerns about spec-compatibility: Our goal is for Bun to be spec-compatible. However, being "spec-compatible" can be more nuanced than you might think! Here's an example:

Node.js added built-in support for `fetch()` and its related APIs. Recently, the Node.js maintainers also decided to make a change to allow async iterables in the body of a `Response` object. This would make the following code valid in Node.js, but invalid in a browser!

```js
const response = new Response({
  async *[Symbol.asyncIterator]() {
    yield "Hello, ";
    yield "world!";
  },
});
const text = await response.text();
console.log(text);
// Node.js: "Hello, world!"
// Bun:     "Hello, world!"
// Chrome:  "[object Object]"
```

Regardless of whether we agree or not with that decision, it was made! Soon after, the maintainers of Astro started to rely on this behaviour, which meant Astro and other packages that might rely on this change became broken in Bun.

That's why we also decided to implement this change in Bun. Is it spec-compliant? No. Could it become part of the spec? Yes, possibly!

We want Bun to be as spec-compliant as possible! Sometimes though, we need to "extend" these browser APIs to either be more compatible with Node.js, or to support server-only APIs that browsers would (likely) never implement, like TLS options in `fetch()`.
