### ISSUE TITLE
Support ${configDir} in typescript paths

### ISSUE THREAD

**Issue by lurebat** [oven-sh/bun#11752]
### What is the problem this feature would solve?

The upcoming typescript 5.5 will have a template variable in tsconfig.json called ${configDir}, which lets you specify relative path to the tsconfig.json file.

Currently bun does not support this feature when parsing typescript's paths.

### What is the feature you are proposing to solve the problem?

Add support for this feature.
Currently the version is still in RC, but I didn't see any issue about this yet.

**Comment by alextbok** [comment]
Looks like this still isn't supported in bun v1.1.16 even though typescript v5.5.2 is now released.

**Comment by ivodolenc** [comment]
Hi, I can also confirm that this is not working for me either.

`${configDir}` is super useful and a long awaited feature from `TS`, especially for shared config from npm.

Bun version: `1.1.27`

---

### Current behavior:

**shared npm pkg `tsconfig.json`**

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "baseUrl": "${configDir}",
    "paths": {
      "@": ["${configDir}/src"],
      "@/*": ["${configDir}/src/*"],
      "~": ["${configDir}/src"],
      "~/*": ["${configDir}/src/*"]
    }
  },
  "include": ["${configDir}/src/**/*"],
  "exclude": ["${configDir}/node_modules"]
}
```

**local project `tsconfig.json`**

```json
{
  "extends": "shared-npm-pkg/tsconfig"
}
```

Everything works great, alias and all local dev configs such as eslint etc, but as soon as I run CLI command `bun run ./src/test.ts` it throws error:

```txt
error: Cannot find module "@/utils" from "..."

Bun v1.1.27 (macOS x64)
 ELIFECYCLE  Command failed with exit code 1.
```

### Current Workaround:

The current solution is to manually specify the `paths`, `baseUrl`, `include` and `exclude` options in `tsconfig.json`.

This example below works fine with `bun`:

```json
{
  "extends": "shared-npm-pkg/tsconfig",
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@": ["./src"],
      "@/*": ["./src/*"]
    }
  },
  "include": ["src/**/*", "*.js", "*.ts"],
  "exclude": ["node_modules"]
}
```

### Expected behavior:

I would expect `bun` to work without additional manual config changes within the `tsconfig.json` file.

**Comment by ivodolenc** [comment]
Please let us know when this might be added or is it already being worked on?

This is a huge and very good feature from `TypeScript`.

In any project that uses `Bun`, the `tsconfig` file needs to be further customized due to the lack of support for the `${configDir}` option and this can be time consuming and difficult to maintain.

In every other project, everything works as expected with just one line of code:

```json
{
  "extends": "shared-npm-pkg/tsconfig"
}
```

**Comment by zoto-ff** [comment]
+1

**Comment by ivodolenc** [comment]
@Jarred-Sumner Hi, thanks for adding support for this 👍🏻. 

I just tested it (`Bun 1.1.36`) and it still doesn't work as expected.

I'm importing a shared configuration from an `npm` package.

This example doesn't work:

```json
{
  "extends": "@hypernym/tsconfig"
}
```

Error message:

```txt
error: Cannot find module '@/utils' from '...'

Bun v1.1.36 (macOS x64)
ELIFECYCLE  Command failed with exit code 1.
```

But as soon as I add the `baseUrl` and `paths`, it works fine.

This example works:

```json
{
  "extends": "@hypernym/tsconfig",
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@": ["./src"],
      "@/*": ["./src/*"]
    }
  }
}
```

Here is the source of the shared [`tsconfig`](https://github.com/hypernym-studio/tsconfig/blob/main/tsconfig.json).

**Comment by Jarred-Sumner** [comment]
@ivodolenc we haven't implemented  support for `extends` when using a module specifier (only a file path). The error you're seeing is due to that, not due to `$[configDir}`

**Comment by ivodolenc** [comment]
Ok, thanks for the info 👍🏻

> we haven't implemented support for extends when using a module specifier (only a file path)...

Can we expect this to be supported in future releases? It would definitely make the dev process easier in projects that often use shared configs.
