### ISSUE TITLE
Add an Uninstall Script to delete Bun from the system 

### ISSUE THREAD

**Issue by Manuelito-Code** [oven-sh/bun#11819]
### What is the problem this feature would solve?

If someday in the future i would delete the Bun runtime without delete manually, add an uninstall script to uninstall it

### What is the feature you are proposing to solve the problem?

Do something similar like the rust uninstall self script of the rust language cli

**Comment by paperdave** [comment]
uninstallation is already documented here:

https://bun.sh/docs/installation#uninstall

on Mac and Linux it is removal of one folder `$HOME\.bun`. a script to do this one command does not make much sense, since it would be easier to type the `rm` command.

on Windows, there is already provided `uninstall.ps1` script. it, like all other applications, can also be uninstalled graphically through the windows ui

**Comment by Iovans** [comment]
Okay thats fine too
