### ISSUE TITLE
Prevent environment variables from being coerced out of a string

### ISSUE THREAD

**Issue by rsc1975** [oven-sh/bun#1185]
### Version

0.1.11 (canary)

### Platform

`Linux ThinkPad-Rob 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What steps will reproduce the bug?

File `sandbox.ts` with content:

```ts
const quiet = process.env.QUIET === "true";
console.log('quiet:', quiet);
console.log('process.env.QUIET:', process.env.QUIET, typeof process.env.QUIET);
```

Run the file with: 
```sh
$ QUIET=true bun run sandbox.ts
```

### What is the expected behavior?

The object `process.env` is a `Record<string, string>` all variables values should be stored as strings.

The output should be: 
```txt
quiet: true
process.env.QUIET: true string
```

### What do you see instead?

This output:
```txt
quiet: false
process.env.QUIET: true boolean
```

### Additional information

It only happens with boolean values, with numbers works as expected.

**Comment by Jarred-Sumner** [comment]
Bun is part bundler/transpiler and part runtime

The behavior you're seeing is an optimization for dead code elimination. It's not exactly a bug (but is clearly confusing sometimes). `process.env.QUIET` simplifies to `"true"` and then `"true" === "true"` simplifies to `true`. Note how `process.env.QUIET` is a string if evaluated at runtime

<img width="650" alt="image" src="https://user-images.githubusercontent.com/709451/187857135-a17e9778-70d4-4bf8-8f6f-b3aed439899b.png">

If you wanted to coerce it to always be a string, you could do `"" + process.env.QUIET`

**Comment by rsc1975** [comment]
But @Jarred-Sumner , that code works different in node (and deno), where `quite` var is resolved as true, but in Bun is `false`, that sounds not correct. In other words, the problem is that in Bun `quite` local variable is resolved as `false`, and that is not correct according to specs.

**Comment by Jarred-Sumner** [comment]
Ah, yes you are correct. This is a bug in the `.env` parser. It is coercing boolean strings to boolean values when it should keep them as strings

<img width="668" alt="image" src="https://user-images.githubusercontent.com/709451/187862787-6140aa98-bf24-42f7-bbcd-c9a7320514b2.png">

**Comment by pfgithub** [comment]
It looks like the bug is in one of these places

<details>

https://github.com/oven-sh/bun/blob/f023b89b732db0aff24445acbbe39c366d13118d/src/env_loader.zig#L540-L562

https://github.com/oven-sh/bun/blob/f023b89b732db0aff24445acbbe39c366d13118d/src/env_loader.zig#L588-L610

https://github.com/oven-sh/bun/blob/f023b89b732db0aff24445acbbe39c366d13118d/src/env_loader.zig#L638-L660

https://github.com/oven-sh/bun/blob/f023b89b732db0aff24445acbbe39c366d13118d/src/env_loader.zig#L692-L761

</details>

It also causes `0` and `1` to be numbers instead of strings and `"undefined"` to be `undefined`. 

I wonder what this is for? It was clearly written out four times, so it probably has some use. I don't see any test cases covering it

A visual reproduction:

```js
const q = "QUIET";
console.log({a: process.env.QUIET, b: process.env[q]});
```
