### ISSUE TITLE
Support JSR package registry out of the box

### ISSUE THREAD

**Issue by notramo** [oven-sh/bun#11911]
### What is the problem this feature would solve?

I want to get started with [JSR](https://jsr.io), but Bun doesn't provide the "all-in-one" UX for it.

According to the JSR documentation, `bunx jsr add package` works, but I don't know if it uses the `bun.lockb` or not.

It should be as simple as `bun add jsr:package`. JSR provides an npm-compatible registry at npm.jsr.io, and adding it to Bun default settings would improve developer experience.

### What is the feature you are proposing to solve the problem?

Add native support for JSR.

### What alternatives have you considered?

Deno supports it out of the box.

**Comment by ryoppippi** [comment]
When we run `bunx jsr add package` command, `bun.lockb` records its dependencies correctly.

**Comment by Jarred-Sumner** [comment]
You can use JSR as a registry in Bun, like any other npm registry. We aren’t going to add support for it beyond that at this time

**Comment by notramo** [comment]
`bunx jsr add package` does not save the package version automatically, as it records the compatibility workaround hack in place of the version.
```json
  "dependencies": {
    "@hono/hono": "npm:@jsr/hono__hono"
  }
```

**Comment by ryoppippi** [comment]
@notramo 
Since Bun now supports `.npmrc` we can set package version correctly.
I  created a PR for JSR, but JSR cli repo is inactive for a while...
https://github.com/jsr-io/jsr-npm/pull/94

**Comment by KnorpelSenf** [comment]
`yarn`, `pnpm` and Deno all support JSR natively now. Bun is lagging behind, and so is npm. https://github.com/jsr-io/jsr/pull/1029

@Jarred-Sumner has your position changed by now?

**Comment by loucyx** [comment]
@KnorpelSenf `npm` migh never support it because `jsr.io` is an alternative to `npmjs.com`, and `bun` might feel similarly about `deno`, so I wouldn't keep my hopes up, but you're 100% right, `bun` is lagging behind:

| Package manager | Native JSR support | Command                                 |
| --------------- | ------------------ | --------------------------------------- |
| `deno`          | ✅                 | `deno add jsr:@namespace/package`       |
| `pnpm`          | ✅                 | `pnpm add jsr:@namespace/package`       |
| `yarn`          | ✅                 | `yarn add jsr:@coven/compare`           |
| `esm.sh`        | ✅                 | `https://esm.sh/jsr/@namespace/package` |
| `npm`           | ❌                 | `npm jsr add jsr:@namespace/package`    |
| `bunx`          | ❌                 | `bunx jsr add jsr:@namespace/package`   |

**Comment by loucyx** [comment]
Added `vlt` to the table, we keep getting native JSR support everywhere...

**Comment by BlackAsLight** [comment]
It seems `npm` is also looking to add JSR support: https://github.com/npm/npm-package-arg/pull/214

Given this is Bun open to reconsidering their current stance?
