### ISSUE TITLE
Object expansion is broken

### ISSUE THREAD

**Issue by al6x** [oven-sh/bun#12084]
### What version of Bun is running?

1.1.16

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```
Object.defineProperty(Object.prototype, 'some', { value: 1, enumerable: false, writable: true, configurable: true })
console.log(({} as any).some)

const found = /.+ (?<a>\d+) (?<b>\d+)/.exec('a 22 45')
console.log(({ ...(found?.groups || {}) } as any).some)
```

### What is the expected behavior?

1
1

### What do you see instead?

1
undefined

**Comment by Jarred-Sumner** [comment]
Looks like a JavaScriptCore bug.

This reproduces in Safari Technology Preview:
```js
Object.defineProperty(Object.prototype, 'some', { value: 1, enumerable: false, writable: true, configurable: true })
console.log(({}).some)

const found = /.+ (?<a>\d+) (?<b>\d+)/.exec('a 22 45')
console.log(({ ...(found?.groups || {}) }).some)
```

<img width="809" alt="image" src="https://github.com/oven-sh/bun/assets/709451/8d5de51e-b902-4bb3-aa8a-9c884e3197b4">

Began in Bun v1.1.2:

<img width="170" alt="image" src="https://github.com/oven-sh/bun/assets/709451/ba0349a7-5227-40f6-87c1-13976734206c">

Judging by the commit diff from WebKit versions in Bun v1.1.1 and Bun v1.1.2, potentially caused by https://github.com/oven-sh/WebKit/commit/804d44f89619bfae3e5e2e21a07669b1fb320d57. I'll file a bug with WebKit/JSC
