### ISSUE TITLE
bun --filter "*" does not match scoped packages

### ISSUE THREAD

**Issue by DaniGuardiola** [oven-sh/bun#12300]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Attempt to run `bun --filter '*' build` in a monorepo context where multiple packages have build scripts. Some packages are scoped (e.g. `@scope/name` in the `"name"` field of `package.json`).

### What is the expected behavior?

The `build` task is executed in all packages.

### What do you see instead?

The `build` task is only executed in non-scoped packages and scoped packages are ignored.

### Additional information

A way to get the filter to work with scoped packages is to do `bun --filter '@*/*' build`, but then it doesn't match any non-scoped packages.

**Comment by DaniGuardiola** [comment]
@Guyutongxue I assume you mean `bun run --filter="**" test` as per Jarred's comment here: https://github.com/oven-sh/bun/issues/10322#issuecomment-2067551768

Haven't tried yet. Thanks for linking to the related bug.

**Comment by Guyutongxue** [comment]
@DaniGuardiola  Sorry I previously thought that the problem is caused by the difference between `bun --filter ...` and `bun run --filter ...`. But actually in my environment, both commands work for scoped/unscoped workspace packages.

![image](https://github.com/oven-sh/bun/assets/33127223/b570327c-6409-457b-80db-61ffb5252d14)

So I cannot reproduce this problem 🤔

**Comment by DaniGuardiola** [comment]
Huh, seems to be working now. Not sure what change. I didn't upgrade. Closing.
