### ISSUE TITLE
async @napi-rs/canvas crashes under load

### ISSUE THREAD

**Issue by 7f8ddd** [oven-sh/bun#12375]
### How can we reproduce the crash?

`bun i @napi-rs/canvas`

```
import { createCanvas } from "@napi-rs/canvas";

async function generate() {
  const canvas = createCanvas(400, 200);
  const ctx = canvas.getContext("2d");

  ctx.fillStyle = "#FFFFFF";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  const encoded = await canvas.encode("webp");

  return `data:image/webp;base64,${encoded.toString("base64")}`;
}

while (true) {
  generate();
}
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`ee25618`](<https://github.com/oven-sh/bun/tree/ee256181971857082889a895b64ab8c4dff46c68>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x63DDD711F

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/ee256181971857082889a895b64ab8c4dff46c68/ld-temp.o#L0>): `WTF::jscSignalHandler`

**Comment by 7f8ddd** [comment]
Kinda important, used for captcha generation, will crash randomly under semi-high load.

**Comment by Jarred-Sumner** [comment]
This is a bug in napi-rs. The same code segfaults in Node if you add a short delay every N runs.

```ts
import { createCanvas } from "@napi-rs/canvas";

async function generate() {
  const canvas = createCanvas(400, 200);
  const ctx = canvas.getContext("2d");

  ctx.fillStyle = "#FFFFFF";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  const encoded = await canvas.encode("webp");

  return `data:image/webp;base64,${encoded.toString("base64")}`;
}

while (true) {
  const promises = [];
  for (let i = 0; i < 1000; i++) {
    promises.push(generate());
  }
  const images = await Promise.all(promises);
}
```

The crash in Bun happens earlier because we run the finalizers without delaying to the `setImmediate` task queue. The crash occurs because the context pointer passed to the finalizer is no longer valid.

I suggest opening an issue in @napi-rs/canvas to address this. It may be a bug in napi-rs itself, it's a little unclear.
