### ISSUE TITLE
Bun 1.1.20 bricks ssh2-sftp-client

### ISSUE THREAD

**Issue by Sevenlive** [oven-sh/bun#12593]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Darwin 23.5.0 x86_64 i386

### What steps can reproduce the bug?

 let client = new Client();
    try {
        console.log("Connecting to SFTP Server");
        await client.connect(config);
        console.log("Connected to SFTP Server");
        let status = await client.exists("/");

### What is the expected behavior?

Should connect to the SFTP Server and check if remote dir exist.

### What do you see instead?

The process starts to freeze without errors. 

### Additional information

Working Version - 1.1.18+5a0b93523
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received EXT_INFO
Inbound: Received SERVICE_ACCEPT (ssh-userauth)
Outbound: Sending USERAUTH_REQUEST (none)
Inbound: Received USERAUTH_FAILURE (publickey,gssapi-keyex,gssapi-with-mic,password)
Client: none auth failed
Outbound: Sending USERAUTH_REQUEST (password)
Inbound: Received USERAUTH_SUCCESS
CLIENT[sftp]: getConnection ready listener: got connection - promise resolved

Non Working - 1.1.20+ae1948925
Host accepted (verified)
Outbound: Sending NEWKEYS
Inbound: NEWKEYS
Verifying signature ...
Verified signature
Handshake completed
Outbound: Sending SERVICE_REQUEST (ssh-userauth)
Inbound: Received EXT_INFO
Socket ended
CLIENT[sftp]: getConnection Unexpected end event
CLIENT[sftp]: connect endListener - handled end event
CLIENT[sftp]: Global end event: Handling unexpected event
Socket closed
CLIENT[sftp]: getConnection closeListener - handled close event
CLIENT[sftp]: connect closeListener - handled close event
CLIENT[sftp]: Global close event: Handling unexpected event

**Comment by marcellocurto** [comment]
I just ran into a similar issue. It was still working on version 1.1.18 but stopped working on version 1.1.19. The error message I get is: "Requested service not available" with error code 7. I also tried different libraries like `ssh2-sftp-client`, `node-ssh`, and `ssh2`, but the issue remains the same.

**Comment by louisescher** [comment]
I'm experiencing the same thing, the issue was (as stated) introduced in v1.1.19. Currently having this issue with `node-ssh`. I get the error `No response from server, code: "ETIMEDOUT"`. 
Checking the auth logs on the system I'm trying to connect to produces the following:
`2024-08-02T15:35.504214+00:00 kvm5070 sshd[1457]: ssh_dispatch_run_fatal: Connection from [IP_ADDRESS] port 26913: invalid format [preauth]`.
After looking through the files when comparing v1.1.18 and v1.1.19, I think the regression must've been introduced while making changes to the `bun-usockets` package. I'm sadly not able to test this locally as I only have a windows machine, would appreciate if someone else could look into which piece of code caused this?

**Comment by JanHolger** [comment]
Same here, In 1.0.33 I had linker issues (missing symbol called), after upgrading to 1.1.26 I receive the same message as @marcellocurto

**Comment by nxht** [comment]
It seems it's working now in 1.1.27. At least when tested on wsl/linux

**Comment by Sevenlive** [comment]
I can confirm it, so i will close the Issue.
