### ISSUE TITLE
Crash reporter lacks debug symbols in canary

### ISSUE THREAD

**Issue by Araxeus** [oven-sh/bun#12715]
### What version of Bun is running?

1.1.21-canary.1+dc775f75f

### What platform is your computer?

Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Crash on canary and open link:
for example:
https://bun.report/1.1.21/wa2dc775f7AiogggCCqB/node.napi.glibc.nodesjZCqB/node.napi.glibc.node+jjCCqB/node.napi.glibc.nodeo/7Bw2kk0C0qupsB__A2AwK

### What is the expected behavior?

![image](https://github.com/user-attachments/assets/d8a705df-14a6-426c-8dbc-abec28c67634)

### What do you see instead?

![image](https://github.com/user-attachments/assets/2ff20016-a0df-42ed-95bd-3ff0cf11737b)

### Additional information

see also https://github.com/oven-sh/bun/issues/12711#issuecomment-2241646631

**Comment by paperdave** [comment]
this link shared is very interesting to me because it remaps fine on my local clone of bun.report, but not in production.

the latest version of canary, however, is not marking it's urls as is_canary=true, which is because that entire build is not marked canary. that secondary issue is a CI specific one.

still bugs me that this specific commit is breaking

**Comment by Araxeus** [comment]
It seems to work fine on latest canary, should this issue be closed?

**Comment by Araxeus** [comment]
@Electroid this is still happening on latest canary https://bun.report/1.1.22/wa298f9e27AiwgggDggn50C2nhkJ__m7p8wBA2AQ
