### ISSUE TITLE
Monorepo support for `bun outdated`

### ISSUE THREAD

**Issue by alextbok** [oven-sh/bun#13519]
### What is the problem this feature would solve?

Currently `bun outdated` only reports on dependencies at the top level of a monorepo (no matter which directory it is run from). It'd be really nice if it also reported on dependencies defined in workspace `package.json` files.

### What is the feature you are proposing to solve the problem?

For `bun outdated` to report on workspace `package.json` files in addition to the root level.

**Comment by alextbok** [comment]
cc @dylan-conway

**Comment by dylan-conway** [comment]
`bun outdated` does work with workspaces, but the experience isn't the greatest because it requires cd'ing to the target workspace (or using `--cwd`). In the next few days we will add support for `--filter`, same as `bun --filter` and `pnpm --filter`, to make it easier working with monorepos.

> Currently bun outdated only reports on dependencies at the top level of a monorepo (no matter which directory it is run from)

This should be working, we have a test for this. Was there a bug you ran into?

**Comment by austinm911** [comment]
taze is your best bet for now

https://github.com/oven-sh/bun/issues/533#issuecomment-2295394488 

`bunx --bun taze --interactive --recursive`

**Comment by alextbok** [comment]
@dylan-conway sorry for the false alarm. I could've sworn I was getting same output even after cc'ing into a particular package but just tried again and the demo effect prevailed. Closing this out and looking forward to `--filter` support!

**Comment by dylan-conway** [comment]
#13557 this pr will add `--filter` support to `bun outdated`
