### ISSUE TITLE
Electron not working

### ISSUE THREAD

**Issue by real-kwellercat** [oven-sh/bun#1377]
### What version of Bun is running?

0.2.1

### What platform is your computer?

Linux 5.19.0-76051900-generic #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S x86_64 x86_64

### What steps can reproduce the bug?

1. Install electron
2. Make a sample app
3. Try to run it

### How often does it reproduce? Is there a required condition?

It will reproduce no matter what I do, also it breaks the tsconfig.json.

### What is the expected behavior?

A window will open up with something in it.

### What do you see instead?

![image](https://user-images.githubusercontent.com/89104643/197407337-ed9a434a-87b6-4554-97f8-a9488cb00a9e.png)

### Additional information

I am pretty sure it is electron not supporting typescript, but I don't really know.

**Comment by real-kwellercat** [comment]
I am on POP!_os 22.04 LTS by  the way.

**Comment by cryptodeal** [comment]
I can confirm I've been unable to get Electron working w Bun; with that being said, I highly recommend checking out [Wails](https://wails.io) as it's an open sourced Electron competitor, core app is written in Go and it leverages native rendering engines rather than bundling the browser (resulting builds for the same app built in Electron was ~80Mb vs Wails app of ~12Mb). 

I haven't had any issues getting wails to work with Bun runtime.  Link to repo I'm using Wails/Bun in, if you're interested in checking Wails out as a workaround in the meantime: https://github.com/cryptodeal/shumai-dataviz

**Comment by real-kwellercat** [comment]
> I can confirm I've been unable to get Electron working w Bun; with that being said, I highly recommend checking out [Wails](https://wails.io) as it's an open-sourced Electron competitor, the core app is written in Go and it leverages native rendering engines rather than bundling the browser (resulting builds for the same app built in Electron was ~80Mb vs Wails app of ~12Mb).
> 
> I haven't had any issues getting wails to work with Bun runtime. Link to repo I'm using Wails/Bun in if you're interested in checking Wails out as a workaround in the meantime: https://github.com/cryptodeal/shumai-dataviz

Ok, thanks for the suggestion! I think the reason it doesn't work is because it is typescript only and javascript isn't supported unless its jsx.
