### ISSUE TITLE
Response with `null` body causes segfault

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1379]
### What version of Bun is running?

0.2.1 (canary)

### What platform is your computer?

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64 arm

### What steps can reproduce the bug?

`bun run --hot index.ts`
```ts
// index.ts
export default {
  async fetch(request) {
    return new Response(null, { status: 405 });
  }
}
```

### How often does it reproduce? Is there a required condition?

Always

### What do you see instead?

```
SegmentationFault at 0x1000000000000000


----- bun meta -----
Bun v0.2.1 (73fba0c5) macOS Silicon 21.5.0
RunCommand: 
Elapsed: 3010ms | User: 54ms | Sys: 39ms
RSS: 62.18MB | Peak: 62.18MB | Commit: 67.11MB | Faults: 1123
----- bun meta -----
```

**Comment by Jarred-Sumner** [comment]
I wonder if it’s `null` as the body. If you try “null” as a string does it crash?

**Comment by Electroid** [comment]
> I wonder if it’s `null` as the body. If you try “null” as a string does it crash?

Ah yes, it looks like this only happens when the `body` is `null`, and it's not limited to `405`, it appears to be any status code.

**Comment by sno2** [comment]
Did some investigating and the problem is something with an invalid `InternalBlob` being created with a `new Response(null)` when converting responses' underlying data into an owned string.  A simpler repro is the following:

```ts
const res = new Response(null);
await res.text();
```

It calls `toStringOwned` on `InternalBlob` and then that fails because the data is undefined and not created by mimalloc.  https://github.com/oven-sh/bun/blob/main/src/bun.js/webcore/response.zig#L4030

I don't have enough time to find a fix but I would definitely look into the `Response` creation.
