### ISSUE TITLE
Segmentation fault in buggy `cc` code reports that crash is Bun's fault

### ISSUE THREAD

**Issue by moonjellydigital** [oven-sh/bun#14070]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Linux 6.5.0-1026-oracle aarch64 aarch64

### What steps can reproduce the bug?

1. Write some buggy C (code below).
2. Try to run buggy C using `cc`.

Steps 1 and 2 result in a crash with the message "oh no: Bun has crashed. This indicates a bug in Bun, not your code."

Offending code:

```c
#include <stdio.h>

void hello( char msg) {
    printf("Hello, %s\n", msg);
}
```

```typescript
import { cc, FFIType } from "bun:ffi";
const { char } = FFIType;

export const {symbols: { hello }} = cc({
  source: "./hello.c",
  symbols: {
    hello: {
      returns: "void",
      args: [char],
    },
  },
});

hello(87);
```

When the `%s` placeholder in the buggy C above is replaced with the correct `%c` placeholder, everything works as expected.

### What is the expected behavior?

When I write buggy C, something crashing is the behavior I expect.  I don't expect a message saying the buggy code I wrote isn't the problem.

### Relevant Log Output

Bun v1.1.29 (6d43b366) Linux arm64
Linux Kernel v6.5.0 | glibc v2.35
Args: "bun" "hello.ts"
Features: jsc 
Builtins: "bun:ffi" "bun:main" 
Elapsed: 22ms | User: 15ms | Sys: 3ms
RSS: 1.07GB | Peak: 34.67MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x50
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

Trace/breakpoint trap (core dumped)

### bun.report Stack Trace

Segmentation fault at address 0x00000050

Failed to remap stack trace to source code:
Could not find debug info for this version of Bun.
Bun v1.1.29 (6d43b36) on Linux aarch64

**Comment by codehz** [comment]
%s expect a char* while you provide a single char

**Comment by 190n** [comment]
> When I write buggy C, something crashing is the behavior I expect. I don't expect a message saying the buggy code I wrote isn't the problem.

You're right that the "This indicates a bug in Bun, not your code" message isn't always accurate. The issue is that it's impossible to automatically determine whether any segfault is the fault of Bun or the user's code (whether you're using dlopen, cc, or Node-API). Even if you look at the location of the crash and determine that it's in a user-provided module, that doesn't always mean it's a bug in the user code -- it could be because Bun passed it some invalid value (I've fixed many Node-API bugs that manifested as crashes in user code).

Because almost all crashes like this are actually Bun's fault, I think leaving the message as-is is the right choice.
