### ISSUE TITLE
Incorrect types for `Bun.gunzipSync()`

### ISSUE THREAD

**Issue by touhidurrr** [oven-sh/bun#14472]
### What version of Bun is running?

1.1.31-canary.9+ff476313a

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```ts
const base64 = 'Some Gzip data encoded to Base64';
const array = Bun.gunzipSync(Buffer.from(data, 'base64'));
```

### What is the expected behavior?

It works fine.

### What do you see instead?

I see type errors.
![Image](https://github.com/user-attachments/assets/13016415-9896-4d32-b6ab-cea70f51c99e)

### Additional information

Even though there was no type error previously, in the latest version there is even though `Bun.gunzipSync()` accepts `Buffer` properly. Without this you have to manually convert from `Buffer` to `ArrayBuffer` for no reason or use `//@ts-ignore`

**Comment by nektro** [comment]
works as expected with no errors

![Image](https://github.com/user-attachments/assets/ed4b666e-be09-4413-a2dd-0747fb488f66)

![Image](https://github.com/user-attachments/assets/7dd7926e-001c-48ed-bf25-bc71980a2fb4)

**Comment by touhidurrr** [comment]
> works as expected with no errors

I am not sure why are you not seeing any errors. Because from your screenshot itself, it is saying that `gunzipSync(data: string | Unit8Array | ArrayBuffer, ...`, so the type of `data` is `string | Unit8Array | ArrayBuffer`. But we are passing `Buffer` here. And that is the error what I faced in my usage. But you have the same types but no errors?

Are you sure that you are on the latest version of `typescript` and `@types/bun`?

**Comment by touhidurrr** [comment]
Ok, I found something interesting. With only `@types/bun` installed on the project, I am getting no error. But with both `@types/bun` and `@types/node` installed, this error appears. Since I was using **Bun** as a runtime in my project, I thought I did not need **node** types.

@nektro, I think this issue should be reopened and investigated.

**Comment by nektro** [comment]
`Buffer` extends from `Unit8Array`

**Comment by touhidurrr** [comment]
@nektro, reminder ping

**Comment by nektro** [comment]
> Ok, I found something interesting. With only `@types/bun` installed on the project, I am getting no error.

this is why i felt the issue should be closed

> But with both `@types/bun` and `@types/node` installed, this error appears. Since I was using **Bun** as a runtime in my project, I thought I did not need **node** types.

this is correct. `@types/bun` itself depends on `@types/node` to fill in the definitions it does not define and so you should only need to directly devDepend on `@types/bun`. this is reflected in the default `package.json` created by `bun init`.

> I am not sure why are you not seeing any errors. Because from your screenshot itself, it is saying that `gunzipSync(data: string | Unit8Array | ArrayBuffer, ...`, so the type of `data` is `string | Unit8Array | ArrayBuffer`. But we are passing `Buffer` here.

this is because as i said above, `Buffer` inherits from `Unit8Array` so that is the type it is being received as and passes the type-check.

> And that is the error that I faced in my usage. (Argument of type `Buffer` cannot be assigned to type `string | Unit8Array | ArrayBuffer`) But you have the same types here but no errors? Are you sure that you are on the latest version of `typescript` and `@types/bun`?

there may have been a definition conflict of the `Buffer` global related to something along the lines of https://github.com/oven-sh/bun/issues/8761 but it appears to have been fixed in this particular case given that u said above it now works with only `@types/bun` installed. i also recreated the example above in a new project with `bun init` and then did `bun add @types/node` and can confirm i still did not see the error in the latest versions of bun and the types packages.

if there's anything i've missed, am happy to look further :)

**Comment by touhidurrr** [comment]
>  i also recreated the example above in a new project with bun init and then did bun add @types/node and can confirm i still did not see the error in the latest versions of bun and the types packages.

You have to do `bun init` then `bun add @types/bun`, and you must not install `@types/node` for this to work.
