### ISSUE TITLE
zlib implementation failed to decompress gzip buffer

### ISSUE THREAD

**Issue by jiajzhou** [oven-sh/bun#1511]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64 i386

### What steps can reproduce the bug?

Create a new bun project.

Under the root folder of the bun project, create a test gzip file using this command line

```
echo '[1,2,3]' > test.json
gzip test.json
```

Under the root folder of the bun project, create a typescript file `zlibTest.ts` with the following content:

```
import * as zlib from "node:zlib";
import * as fs from "node:fs";

const content = fs.readFileSync("./test.json.gz");
zlib.gunzip(content, (err, data) => {
  console.log(err);
  console.log(data);
});
```

You'll see the script failed with the error message:

```
error: invalid input
      at /bun-vfs/node_modules/zlib/index.js:63:52128

undefined
```

Running the same program with `tsx` will succeed.

```
❯ npx tsx zlibTest.ts
null
<Buffer 5b 31 2c 32 2c 33 5d 0a>
```

### How often does it reproduce? Is there a required condition?

Always reproduce.

### What is the expected behavior?

The script should succeed with the correctly decompressed content.

### What do you see instead?

Error message shown in the repro step.

**Comment by Jarred-Sumner** [comment]
we need to switch out the `gzip` implementation to use Bun's gzip functions

**Comment by jiaz** [comment]
Hey, I might have some bandwidth to contribute a PR to fix this if there is an intention to have the nodejs API compatibility for Bun. From the documentation/roadmap it's not clear if Bun would treat such compatibility as a priority, but I think many people will try to use Bun as a drop-in replacement of nodejs. In my case, I have a nodejs app that needs to deal with JSON file larger than 512MB. v8's JSON parser cannot handle it while Bun handles larger JSON perfectly. However due to this issue, I have to update the code to adapt to Bun's gzip implementation.

**Comment by Jarred-Sumner** [comment]
@jiaz we definitely want node-compatible `zlib` in there

Our current `zlib` module is a browserify polyfill. It doesn't use the builtin `zlib-cloudflare` that `Bun.gzipSync` uses and it doesn't implement much of the `zlib` module's API.

Contribution definitely welcome.

This would work by creating a new module in Bun.

To do that:
1) Create `src/bun.js/zlib.exports.js`
2) Add `.{ "node:zlib", "node:zlib" }` and `.{ "zlib", "node:zlib" }` to this list: https://github.com/oven-sh/bun/blob/2392e48e9da65dbecdfa9b16446c739c7618e5a1/src/bun.js/module_loader.zig#L2111-L2120
3) Add `.{ "node:zlib", .@"node:zlib" }` to this list https://github.com/oven-sh/bun/blob/2392e48e9da65dbecdfa9b16446c739c7618e5a1/src/bun.js/module_loader.zig#L2066-L2068
4) Add `@"node:zlib"` to this `enum` https://github.com/oven-sh/bun/blob/2392e48e9da65dbecdfa9b16446c739c7618e5a1/src/bun.js/module_loader.zig#L2021-L2024
5) Add a switch case like this but for `@"node:zlib"` which returns the source code for `zlib.exports.js` https://github.com/oven-sh/bun/blob/2392e48e9da65dbecdfa9b16446c739c7618e5a1/src/bun.js/module_loader.zig#L1778-L1788

After that, importing `node:zlib` or `zlib` should import `zlib.exports.js` in `bun-debug`. The first time you'll need to recompile Bun, but subsequent times it will load zlib.exports.js in the debug mode.

From there, you'll need to implement the module matching Node.js' API. You can use Bun.gzipSync, Bun.deflateSync, Bun.gunzipSync etc. You'll probably need to add a concurrent version which would probably use `ConcurrentPromiseTask` in event_loop.zig https://github.com/oven-sh/bun/blob/2392e48e9da65dbecdfa9b16446c739c7618e5a1/src/bun.js/event_loop.zig#L27

This will need to partially be JavaScript because `zlib` module expects `node:stream` which is currently a JavaScript implementation.

**Comment by jiaz** [comment]
@Jarred-Sumner thanks so much for the detailed steps. I'll try following up.

**Comment by jiaz** [comment]
@Jarred-Sumner I took a look into the zlib fallback implementation. It looks like the root cause of the broken test case above is the fallback implementation (browserify-zlib) uses a bundled `buffer` implementation. Specifically, the `fs.readFileSync` returns a native buffer and the zlib implementation uses the bundled version to check if the passed in object is a `Buffer` object, which fails the assertion.

I made a change in the node-fallaback module to exclude `buffer` from the bundling process, by adding the ` --external:buffer` to the esbuild params. The change will make the following case pass:

```
import { it, describe, expect } from "bun:test";

import * as zlib from "node:zlib";
import * as fs from "node:fs";
import * as buffer from "node:buffer";

describe("zlib.gunzip", () => {
  it("should be able to unzip a Buffer and return an unzipped Buffer", async () => {
    const content = fs.readFileSync(import.meta.dir + "/fixture.html.gz");
    return new Promise((resolve, reject) => {
      zlib.gunzip(content, (error, data) => {
        if (error) {
          reject(error);
          return;
        }
        expect(data !== null).toBe(true);
        expect(buffer.Buffer.isBuffer(data)).toBe(true);
        resolve(true);
      });
    });
  });
});
```

The implementation of the `node:buffer` in Bun is a bit complex to understand, so I'm not sure if it's fully compatible with the nodejs version. If it is, is there any concern of making it `external` in the node-fallbacks build?

The fallback implementation is still a slow implementation, so it might be worth still rewriting it with Bun's native zlib implementation, but I'm wondering if the above solution can be a quick fix to achieve compatibility.

**Comment by ThatOneBro** [comment]
Oh yeah we actually noticed that before that it was using a bundled `buffer` implementation, I totally forgot about that. That temporary fix sounds to me like it's worth a PR in the meantime though, until a proper polyfill is written.

**Comment by jiaz** [comment]
I notice @Jarred-Sumner is already working on it when I try to merge the changes. Will wait for that change then!

**Comment by Jarred-Sumner** [comment]
@jiaz thank you for your test and explanation, you did the work I wired it up

It revealed two EventEmitter bugs though, which I'm fixing now:
1) EventEmitter needs to propagate the this value
2) Errors in the event emitter were being reported, but not acted upon via the onhandled exception handler

**Comment by jiaz** [comment]
You are welcome! Glad it helped!
