### ISSUE TITLE
x64 macOS binary hangs when run with Rosetta

### ISSUE THREAD

**Issue by ofalvai** [oven-sh/bun#15139]
### What version of Bun is running?

1.1.34

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

When I run any of the `darwin-x64` binaries on a `aarch64` host, it hangs with the following output while spinning the CPU 100%:

```
============================================================
Bun v1.1.34 (5e5e7c60) macOS x64
macOS v15.1
CPU: sse42 popcnt
Args:
Features: no_avx2 no_avx
```

I know this is a niche use case, but the Nixpkgs distribution of Bun is built in `aarch64` hosts using Rosetta. Note: I can reproduce the issue with the non-Nix, official prebuilt binaries as well, this doesn't seem to be a Nix-specific issue. More context is here: https://github.com/NixOS/nixpkgs/pull/355159

If it helps, the last successful Rosetta build was with Bun 1.1.20: https://hydra.nixos.org/job/nixpkgs/trunk/bun.x86_64-darwin

**Comment by nektro** [comment]
duplicate https://github.com/oven-sh/bun/issues/14982

**Comment by gshpychka** [comment]
@nektro reopened by accident?

**Comment by nektro** [comment]
no, closed by accident

**Comment by gshpychka** [comment]
> no, closed by accident

so not a duplicate?

**Comment by kzc** [comment]
https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment#What-Cant-Be-Translated

"Rosetta translates all x86_64 instructions, but it doesn’t support the execution of some newer instruction sets and processor features, such as AVX, AVX2, and AVX512 vector instructions"

**Comment by Jarred-Sumner** [comment]
We don't provide a macOS x64 binary that supports non-avx CPUs anymore because it's very difficult for us to have automated test coverage in CI and verify it does in fact work. 

We recommend using arm64 builds of Bun on Rosetta. The official install script detects Rosetta and installs the arm64 version for you when running on an x64 terminal.

We would be open to exploring a build of "universal" build of Bun that has both arm64 and x64 versions in the same binary if this is making it much harder to use Bun. But it probably wouldnt' be the default, as it'll double the binary size

**Comment by emilazy** [comment]
Hi @JarredSumner – thanks for the explanation and it’s totally understandable that it might be too painful to support. Just to give some context, we currently ship the binary builds of Bun to our users as part of Nixpkgs, one of the largest software distributions in the world. All our Mac builder hardware is Apple Silicon, so we build our x86 macOS packages using Rosetta 2. This works very well across the board, but in this case falls down as we need to execute binaries as part of the package builds for things like generating shell completions and running smoke tests. We can’t use the Apple Silicon build for that because we’re creating packages for x86 users, including native Intel Macs, so unfortunately a universal binary wouldn’t really help us either. Our build environment for x86 macOS is isolated from AArch64 binaries, and we use the same package definitions to build with Rosetta 2 on our central build farm and natively locally on Intel Macs.

In such a situation we might consider doing a from‐source build instead to avoid the difficult instruction set dependency, but my understanding is that you need a binary build of Bun to compile Bun, right? So I’m not quite sure what we could do here; it might not be possible for us to support Bun on the platform at all as a result due to the bootstrapping issues.

**Comment by sandydoo** [comment]
> We don't provide a macOS x64 binary that supports non-avx CPUs anymore because it's very difficult for us to have automated test coverage in CI and verify it does in fact work.

@Jarred-Sumner, are you saying that the baseline builds for x86_64 macOS are going to be deprecated? Because they're still available for the latest release.
