### ISSUE TITLE
`--bail` flag behavior to support space-separated arguments in `bun test`

### ISSUE THREAD

**Issue by aralroca** [oven-sh/bun#15293]
### What version of Bun is running?

1.1.37-canary.10+61a3f0859

### What steps can reproduce the bug?

Meanwhile with `bun test` all the tests pass ok, with `bun test --bail 10` is looking for files with 10, so is not working.

```sh
> bun test --bail 10

bun test v1.1.37-canary.10 (61a3f085)
The following filters did not match any test files:
  10
2323 files were searched [62.00ms]

note: Tests need ".test", "_test_", ".spec" or "_spec_" in the filename (ex: "MyApp.test.ts")

Learn more about the test runner: https://bun.sh/docs/cli/test
```

### What is the expected behavior?

Just run `bun test --bail 10`

**Comment by RiskyMH** [comment]
If you do `bun test --bail=10` it should work. 

I'm not sure about the root cause yet, but the clap cli having the `?` and its the only one out of them that cant have whitespace and instead require `=` is odd: https://github.com/oven-sh/bun/blob/c9d0fd51a9991840ea82bbcdc65edaf2ebe207f1/src/cli.zig#L307

**Comment by aralroca** [comment]
Ok, cool, then probably changing the documentation is enough
