### ISSUE TITLE
bug: parseArgs with { allowPositionals: false } throws ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL

### ISSUE THREAD

**Issue by 7flash** [oven-sh/bun#15877]
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```test.ts
import { parseArgs } from "util";

const args = parseArgs({
    args: Bun.argv,
    options: {
        filePath: {
            type: 'string',
        },
    },
    strict: true,
    allowPositionals: false,
});

const filePath = args.values.filePath!;
console.log("filePath ==> ", filePath);
```

runs with following output

```
> bun run ./test.ts --filePath=./App.tsx

1 | import { parseArgs } from "util";
2 | 
3 | const args = parseArgs({
                 ^
TypeError: Unexpected argument '/home/galaxy/.bun/bin/bun'. This command does not take positional arguments
 code: "ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL"
```

**Comment by DonIsaac** [comment]
I think I see the issue; node strips itself from `process.argv` while bun does not. We can't change that behavior, but we can tweak `parseArgs` to ignore it.

**Comment by DonIsaac** [comment]
Just got around to this. Here's what is going on.

- Both `Bun.argv` and `process.argv` start with the path to the bun executable
- This is different behavior from Node, but we rely on this in other places and it will not be changed.
- When `args` are passed to `parseArgs`, that array is taken at face value. The bun bin path is not stripped
- This works in node since the node binary path isn't there in the first place

However, when no `args` are provided, bun _does_ strip the binary path (and the name of the file being run). What you want to do here is
1. Don't pass an `args` option. The default value is sufficient for you.
2. Strip those leading arguments yourself: `Bun.argv.slice(2)`
