### ISSUE TITLE
Bun.connect on socket fails on large message, where node's net works

### ISSUE THREAD

**Issue by dlants** [oven-sh/bun#16076]
### What version of Bun is running?

1.1.42+50eec0025

### What platform is your computer?

MacOs 14.6.1 (23G93)

### What steps can reproduce the bug?

I tried to narrow things down here: https://github.com/dlants/neovim-mini-repro

initially I thought the issue was on neovim's side, but I think it's in Bun.connect on the socket.

As the repo is configured, you can see that:

- the small file is sent
- neovim receives it and updates the buffer
- the large file is sent
- neovim does not receive it
- no subsequent messages sent to neovim receive replies

If you swap the script to node instead:
- `rm -rf node_modules`
- `npm install`
- uncomment the `jobstart` for node and comment out the `jobstart` for bun

Then you can see the large file makes it into neovim.

I'd be happy to try and reduce it more, but I'm not super familiar with sockets so I'm not sure what to look for / what to sub out neovim for?

### What is the expected behavior?

Should work the same in node and bun.

### What do you see instead?

Works in node, does not work in bun.

**Comment by Jarred-Sumner** [comment]
`socket.write` returns the number of bytes written and doesn't buffer. That means if you write a large amount of data, the network might not send all of it, and you have to retry the unsent data when the `drain` callback is called. This buffering behavior is how it works the system APIs for posix/windows software.

This is very much a footgun, and we need to make this clearer in the documentation or have a way to buffer this automatically (outside of using node:net), because you're not the first person who thought this was a bug.
