### ISSUE TITLE
`stream.Readable` does not `_read()`

### ISSUE THREAD

**Issue by alexlamsl** [oven-sh/bun#1608]
### What version of Bun is running?

0.3.0 `--canary`

### What platform is your computer?

Linux 4.4.0-17763-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

```js
$ cat test.js
new class extends require("stream").Readable {
  _read(size) {
    console.log(size);
  }
}().on("data", console.log);
```

### What is the expected behavior?

```console
$ node test.js
16384
$
```

### What do you see instead?

```console
$ bun test.js
$
```

### Additional information

Tried `"node:stream"` or extra `.resume()` to no avail.

**Comment by ThatOneBro** [comment]
I'll look into this. We had originally worked around this via the explicit `_construct()` method, but obviously that's not a compatible solution

**Comment by alexlamsl** [comment]
As a completely random guess &minus; should we (schedule to) call `cb()` before `return`ing here?
https://github.com/oven-sh/bun/blob/5516adec57d5cee29e636ca43b4155e6279c7e1d/src/bun.js/streams.exports.js#L2235-L2238

**Comment by ThatOneBro** [comment]
So actually that is fine, I thought the same thing too. Turns out it has to do with an assumption that `_readableState.constructed` defaults to `true` at construction and only gets set to false when this `construct` function makes it to the next few lines down from where you are looking.

Currently we are not setting it to `true` at construction, so when we get to `read` it exits immediately.

I'm making a PR now to fix this 😄

**Comment by alexlamsl** [comment]
FYI these lines should be safe to remove by your PR:
https://github.com/oven-sh/bun/blob/f61d9e340d35f982e8ad86b705af46464c7f1d2a/src/bun.js/builtins/js/ProcessObjectInternals.js#L465-L468
Thanks for taking care of it 😉
