### ISSUE TITLE
Install Dev dependencies

### ISSUE THREAD

**Issue by nivekcode** [oven-sh/bun#1628]
### What is the problem this feature would solve?

`npm`offers the possibility to install `devDependencies`. It seems that bun currently does not offer this feature. All dependencies installed with bun are installed as normal dependencies. It would be great to add the `-d`flag to `bun install`so that we can install dependencies as devDependencies.

### What is the feature you are proposing to solve the problem?

`bun install -d`

### What alternatives have you considered?

Installing dependency with `bun install`and manually move them to `devDependencies`.

**Comment by alexreyes** [comment]
Seconding this, I would really like dev dependency support

**Comment by valbaca** [comment]
https://bun.sh/docs/cli/install#add-and-remove-packages

```
bun add --development @types/react
bun add -d @types/react
```

**Comment by Zeko369** [comment]
### My 2 cents on this

#### Rest of the ecosystem:

<table>
<tr>
	<td>Manager
	<td>Flags
<tr>
	<td>Yarn@1 / Berry
	<td>--dev / -D
<tr>
	<td>Npm
	<td>--save-dev / -D (but also accepts --dev as an internal alias)
<tr>
	<td>Pnpm
	<td>--save-dev / -D
</table>

Bun meanwhile fails for `-D` and prints out usage for `--dev`
I suggest adding `-D`/`--dev` as aliases to --development, to make it so you can use `-D` in all package managers and --dev (in everything but pnpm)

Example of code used in one of the packages I'm trying to upgrade because of this incompatibility
[// bun use `-d` instead of `-D`, #90](https://github.com/Zeko369/ni/blob/cc134d9900e0e4e2673bfeb43abcda289be8f754/src/parse.ts#L47-L50)

Also I'd love to contribute this change + improve docs (and by docs I mean CLI usage docs that don't mention which flag is used for dev)

<details>
<summary>Current usage</summary>

![CleanShot 2023-03-15 at 16 30 26](https://user-images.githubusercontent.com/3064377/225359799-0bae7e41-0c5a-4511-bdc0-c6083df53abc.png)

</details>

**Comment by Zeko369** [comment]
Hmm I actually found a PR that implemented this #2240, but it was reverted 🤔
cc: @Jarred-Sumner

**Comment by Electroid** [comment]
> Hmm I actually found a PR that implemented this #2240, but it was reverted 🤔 cc: @Jarred-Sumner

It had to be reverted because it caused other issues with CLI parsing, we will revive the change soon.

**Comment by Parzival-3141** [comment]
Seems to be a duplicate of #1819, which is resolved.
