### ISSUE TITLE
[bun:ffi] Non-null terminated CString corruption

### ISSUE THREAD

**Issue by lucifer1004** [oven-sh/bun#1684]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 5.15.0-56-generic x86_64 x86_64

### What steps can reproduce the bug?

Just follow the steps of https://github.com/lucifer1004/bun-ffi-bug-repro.

### What is the expected behavior?

`bun:ffi` should pass strings correctly.

**Comment by lucifer1004** [comment]
When passing a CString, we need to ensure that the string is null-terminated.

Both `Buffer.concat([Buffer.from(str), Buffer.from([0])])` and `Buffer.from(str + "\x00")` work.

**Comment by lucifer1004** [comment]
When passing a CString, we need to ensure that the string is null-terminated.

Both `Buffer.concat([Buffer.from(str), Buffer.from([0])])` and `Buffer.from(str + "\x00")` work.

**Comment by AlexAllocated** [comment]
@lucifer1004 Thank you for this. I was banging my head on this forever. Even knowing how C strings are terminated I still did not think to do this from the FFI side. Had a surprisingly hard time debugging and finding out what I was doing wrong due to very little info on the web regarding Bun's FFI and the FFI docs are pretty bare bones. All I needed was `"\x00"` so thank you!
