### ISSUE TITLE
os.arch() and os.platform() are not correct

### ISSUE THREAD

**Issue by kriszyp** [oven-sh/bun#173]
Currently `os.platform()` reports "browser", and `os.arch()` reports "javascript". These functions are used for determining the appropriate binary build to load, but these values don't actually represent the real os/arch. `os.platform()` should report "linux" (or "darwin" or hopefully someday "win32"), and `os.arch()` should report "x64" or "arm64" (or anything else you support).

**Comment by Jarred-Sumner** [comment]
(said this over DM but repeating for other readers)

The issue is bun doesn't implement the `"os"` module right now – it's using a browserify polyfill. Will fix this at least partially in teh next release, though will probably not implement all of `"os"` next release. Just enough to make it work a little better

**Comment by xhyrom** [comment]
I'll try to implement it after vacation 👍
