### ISSUE TITLE
buffer.utf8Write's third argument should be max bytes to write

### ISSUE THREAD

**Issue by kriszyp** [oven-sh/bun#175]
Currently bun is treating the third argument to utf8Write as the maximum ending position of the write, but it is supposed to be maximum number of bytes to write (starting at the starting offset). This should print 5, but is printing 0 right now:
```
let b = Buffer.alloc(16)
let length = b.utf8Write("hello", 8, 8);
console.log('wrote', length)
```

**Comment by jhmaster2000** [comment]
This bug also affects the regular `buffer.write`. The underlying issue seems a little more complex than being simply calculating the end position of the write from offset 0, otherwise the following codes would be writing a few bytes (The last example with 4, 7 would have written 3 bytes from offset 4):
![image](https://user-images.githubusercontent.com/32803471/181391980-8dbac0ea-470d-4f0e-b894-f8c4bac0bc93.png)
