### ISSUE TITLE
Implement `primordials`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1778]
To run Node.js tests, we need to support `primordials`, likely only exposed using a special flag.

Example from [`lib/internal/errors.js`](https://github.com/nodejs/node/blob/main/lib/internal/errors.js)
```js
  // ..
  SafeMap,
  SafeWeakMap,
  String,
  StringPrototypeEndsWith,
  StringPrototypeIncludes,
  StringPrototypeSlice,
  StringPrototypeSplit,
  StringPrototypeStartsWith,
  StringPrototypeToLowerCase,
  Symbol,
  SymbolFor,
  SyntaxError,
  TypeError,
  URIError,
} = primordials;
```

**Comment by Jarred-Sumner** [comment]
Use `import.meta.primordials` from a .*.exports.js file. Only a handful of these are exposed and it will crash if unavailable ones are chosen

**Comment by ThatOneBro** [comment]
We have the beginning of this in `import.meta.primordials` though I don't think it's anywhere near complete when compared with Node's primordials. This would also help make it easier to port Node builtin modules because we wouldn't have to assign them to vars at the top of the file

EDIT: Yeah what Jarred said.

**Comment by Jarred-Sumner** [comment]
This was mostly implemented and we can add to it as necessary
