### ISSUE TITLE
Will there be Windows port of bun?

### ISSUE THREAD

**Issue by orzklv** [oven-sh/bun#1858]
### What is the problem this feature would solve?

Actually, some part of developer community use windows and there are people who might refuse to use WSL. Therefore, will there be a Windows port of blazingly fast runtime "bun". 

### What is the feature you are proposing to solve the problem?

By having bun.js's windows port, many sysadmins or projects would be able to (be) replace(d) nodejs with bun on IIS or Windows servers.

**Comment by brian316** [comment]
one workaround I use is to install it in a distro for WSL then you can use it on windows :)

**Comment by globalkonvict** [comment]
No I don't think it's necessary at this point in development since not all features are yet implemented.. besides on servers it runs on Linux by default

**Comment by ThatOneBro** [comment]
Short answer: Yes, it's on the list. 😅 

Windows support is coming, but please understand that we are working up to it because it is non-trivial to support alongside Unix-like systems, including Linux which is most likely the target OS for 99% of real-world deployments. We have to make sure Bun gets optimized across all existing and future features on each OS independently, and we are currently building up the team to be able to support this feat while making progress towards all other planned features. 

It should be soon, though, as we do recognize it to be important for some developers and it's listed as one of the planned features for Bun 1.0

Here is the issue tracking Windows support: https://github.com/oven-sh/bun/issues/43

I'll close this issue and future discussions of Windows tracking can occur in that issue. Thank you
