### ISSUE TITLE
Implement glob support for workspace names in bun install

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1918]
We can likely use @The-King-Of-Toasters' [globlin](https://github.com/The-King-of-Toasters/globlin/tree/master/src) for matching globs. The main question there is if we could somehow make it an iterator while respecting things like negative matching patterns. 

The code is here:

https://github.com/oven-sh/bun/blob/8d622ad541e7c6ee72bf00d813c6764f3b16ba03/src/install/lockfile.zig#L2711-L2740

There are three changes to make there:
1) When there is a glob to match against (any workspace name contains either a "*" or a "{" character or a "!" character), we instead allocate all the workspaces name patterns into a temporary string array and then iterate through each one
2) The current code path which only supports exact names should continue to exist only when there are no workspace names with glob-like patterns. Ideally we could still make it work with this code path if you specify just a directory name like `"packages/"` (note the trailing slash) or `"packages/*"`.
3) The current code path should be modified to only open the package.json for the directory directly, rather than open the directory for the worskpace then open the package.json then close the directory. It is inefficient to open directories unnecessarily.

**Comment by Jarred-Sumner** [comment]
A limited version of this is available in Bun v0.5.8. Just a trailing `/*` is implemented.

**Comment by Kleywalker** [comment]
Are there any plans to implement multi level globs? I use bun in a complex monorepo. The limited version with trailing `/*` gets quite confusing pretty fast.

**Comment by denieler** [comment]
This is absolutely necessary feature 🙇‍♂️

**Comment by andyjessop** [comment]
I have an nx repo and I'm just converting to bun, but this is currently a deal-breaker. I have nested folders inside, e.g. `packages/`, but I cannot access them with global nx commands without using a pattern like `packages/**/*`. But if I use that then Bun won't install anything. Is there a way to ignore this error?

**Comment by mblackrittr** [comment]
> A limited version of this is available in Bun v0.5.8. Just a trailing `/*` is implemented.

True, and would be good enough for me, but it's really "limited" as in working only one level deep:

```json
"workspaces": [
  "test/2nd-level/*"
]
```

fails with

```
error: workspace dependency "@test/nested" not found
Searched in "./test/2nd-level/test-nested"
```


What's worse and a real dealbreaker is that even explicitely given deeper full paths fail: 

```json
"workspaces": [
  "test/2nd-level/test-nested"
]
```

fails with the very same error

```
error: workspace dependency "@test/nested" not found
Searched in "./test/2nd-level/test-nested"
```

So, yeah, it says it checks the right paths but still fails for some reason.

**Comment by Kleywalker** [comment]
Are there any news on this topic yet?

**Comment by mblackrittr** [comment]
> Are there any news on this topic yet?

#OhHellboyYeah! 🥳🎉

Thanks to @zackradisic, it's now fully supported since 1.1.7 - super great work, enjoyed following through the MR/PR for some `zig`-insights and also finding the very useful `tempDirWithFiles()`! 😻

From the changelog:
https://bun.sh/blog/bun-v1.1.7#glob-workspace-names-in-bun-install

## [Glob workspace names in bun install](https://bun.sh/blog/bun-v1.1.7#glob-workspace-names-in-bun-install)

You can now use advanced glob patterns in `workspaces` in `package.json` to specify which directories to include in a monorepo. For example:

```json
{
  "name": "monorepo",
  "workspaces": ["{app,packages,lib}/**"]
}
```

Previously, we only supported `/*` as a pattern or exact paths in `workspaces`. `workspaces` matching is now powered by [Bun.Glob](https://bun.sh/docs/api/glob), so you can use any glob pattern supported by `Bun.Glob`.

Thanks to @zackradisic for implementing this feature!
