### ISSUE TITLE
version, --version, -V (but not -v, which is for verbose)

### ISSUE THREAD

**Issue by coolaj86** [oven-sh/bun#1989]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

```
bun -v
```

### What is the expected behavior?

`-V` (capital V) is for `--version`

Newer programs often use a `version` subcommand.

I say support all 3.

Maybe even add just `v` to the mix \
(🤮, but it's how npm does things... so there's that)

### What do you see instead?

`-v` has the long held POSIX tradition of being short for `--verbose`, as in when you want debug output or extra logging...

It is _not_ for version info.

Not that I'd ever want to go full on `-vvv` or anything - I'm not a madman, but...

### Additional information

Obviously this is just a nit... but better to use the long-held common standards than to cross the streams - wouldn't want to let loose Gozer and the Terror Dogs!

**Comment by ThatOneBro** [comment]
As much as I agree about not needlessly changing POSIX traditions, in this case I think this is an issue of how Node does things, ie. `node -v`, so a lot of Node users are already used to this. Deno does follow the POSIX convention though, with `deno -V` and no `deno -v`. 

I think originally we didn't do any uppercase anywhere because of something with the command line parser Bun uses internally not liking uppercase (hence we have `bun add -d <package>` instead of `bun add -D <package>` for `--save-dev` shortcut, which we will fix here: #1931). We should fix that though, some flags should be uppercase.

Anyways, I could probably be swung either way. I'm generally in favor of keeping POSIX traditions, no need to break things in areas where they aren't already broken.

**Comment by birkskyum** [comment]
"-v" aside, one step that can be taken here is to add "-V" as a shorthand for --version. That would adopt the POSIX convention without breaking the node convention. Of course it's a bit unpractical, because the zig_clap code is written to only contain one short form and long form of each command:

```zig
    res.names.long = param_str[2..];
    res.names.short = short_name;
```

**Comment by Electroid** [comment]
Ditto to @ThatOneBro's comment. We can't change the behaviour of `bun -v`, since too many things will depend on it.
