### ISSUE TITLE
Add support for `next/dynamic`

### ISSUE THREAD

**Issue by monshan** [oven-sh/bun#199]
# Problem

Using bun as a bundler for a managed package example application. Though the bundling goes through, a specific component (home) is not rendered on the DOM due to the use of `next/dynamic`. Commenting out dynamic and other components it supports will only render HTML as a string.

https://user-images.githubusercontent.com/54310614/176044324-cea5800c-97d9-4555-a9e4-73a691b0e9fb.mov

# Context

We understand the next release of bun is fast approaching and there is a solution for the use of [dynamic](https://twitter.com/jarredsumner/status/1540328592965390336?cxt=HHwWgMCi0besrOAqAAAA). We hope that this solution will also resolve our issue of using dynamic imports.

# Reproduce

Clone [Shepherd React Wrapper](https://github.com/shipshapecode/react-shepherd) and checkout the `bun-integration` branch. Access packages > example and run `yarn start` that is the script for `bun bun && bun dev`

**Comment by Jarred-Sumner** [comment]
Thank you for the detailed bug report and reproduction. Sadly, this isn't fixed yet in the upcoming release.

> there is a solution for the use of [dynamic](https://twitter.com/jarredsumner/status/1540328592965390336?cxt=HHwWgMCi0besrOAqAAAA)

I think my tweet was confusing -  that applies to bun.js, the JavaScript runtime environment (like Node.js), rather than JavaScript running in web browsers. In your case here, bun.js is used to render the HTML for the page on the server (`bun dev`) before it reaches the client (your browser)

I will update this as a tracking issue for adding support for `next/dynamic`. Most likely, this will work as a macro that uses `React.lazy`

**Comment by fdemir** [comment]
Any updates?

**Comment by monshan** [comment]
@Jarred-Sumner Hi just wanted to follow up on this? any way this could make it into a future release?

**Comment by Jarred-Sumner** [comment]
This is no longer relevant as `bun dev` was deprecated in Bun 1.0
