### ISSUE TITLE
SegmentationFault at 24

### ISSUE THREAD

**Issue by swyxio** [oven-sh/bun#216]
Memory issue when making a simple React SSR server

![image](https://user-images.githubusercontent.com/6764957/177436562-83752a00-2720-46f7-a448-19e6fc74927b.png)

full repro instructions here: https://github.com/sw-yx/bun-segfault-issue-repro

**Comment by swyxio** [comment]
(acknowledged on Discord)

**Comment by jparw3** [comment]
did you find a fix for this?

**Comment by overra** [comment]
I also have this issue if I make any reference to `React.useState` or `React.Component`.

**Comment by swyxio** [comment]
no, i didnt find a fix. see my repro repo above to repro

**Comment by ccmdo** [comment]
I was running into this issue too, and it seemed to be fixed by running `bun bun`.
Which meant that when I then ran `bun dev` it was using the node_modules.bun file 

```bash
vscode ➜ /workspace (main ✗) $ bun dev
[0.36ms] "node_modules.bun" - 57 modules, 6 packages
[15.00ms] bun!! v0.1.4
```

Honestly though, I really don't know enough to say why doing this helped, but perhaps it can help point someone else in the right direction! 🙏

**Comment by rafaelalmeidatk** [comment]
I had the same issue and tracked it down to dynamic imports. Here is a minimal reprodution of the issue:

```tsx
// src/component.tsx
import { useState } from "react";

export const App = () => {
  useState(1);
  return <div>App</div>;
};

// src/index.tsx
import { renderToString } from "react-dom/server";

const headers = { "Content-Type": "text/html" };

export default {
  port: 3000,
  async fetch() {
    const { App } = await import("./component");
    return new Response(renderToString(<App />), {
      headers,
    });
  },
};
```

When running `bun src/index.tsx` and accessing the page I receive this error:
```
SegmentationFault at 24

–––– bun meta ––––
Bun v0.1.4 Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
AutoCommand:
Elapsed: 1188ms | User: 49ms | Sys: 0ms
RSS: 67.11MB | Peak: 72.13MB | Commit: 67.11MB | Faults: 0
–––– bun meta ––––
```

If instead of using the `await import` statement I import the component directly from the top of the file, the component is rendered without issues. It is not an issue exclusive with React, the same happens with other installed libraries (like lodash). It does not happen with native modules like `fs`

**Comment by zhuzilin** [comment]
@sw-yx Hi, could you try with the latest version of bun with `bun upgrade`? I just tried with v0.1.10, the segfault has gone~
but some other js relevant fault occurs. I don't know react, so I'm not sure if this is some bug within bun...

@rafaelalmeidatk Hi, for the latest version, your code should works fine~ Could you give it another try with `bun upgrade`?

**Comment by swyxio** [comment]
i upgraded and the segfault is gone, good enough for me
