### ISSUE TITLE
Match Node's `events.on` (`node:events`) implementation

### ISSUE THREAD

**Issue by ThatOneBro** [oven-sh/bun#2187]
Currently our implementation is copy-pasta of `EventEmitter.on`, which seems logical. However, calling `events.on` on an existing `EventEmitter` is supposed to return an async iterator which can be iterated as events come in

I've already started an implementation for this, but we should really get this in as it fixes the async iterator for `node:readline`

**Comment by paperclover** [comment]
since then, events was rewritten in js but it still never included events.on so this is still an issue.

closing, see #2679 (the only reason i'm closing this one instead of the newer one, is that the `NotImplementedError` thrown in this function at runtime points to the newer issue; my bad for not seeing this one initially)
