### ISSUE TITLE
`FormData` missing Content-Type header when used with `fetch()`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#2264]
Serialize FormData but missing content-type "boundary"?  @Jarred-Sumner 

![image](https://user-images.githubusercontent.com/968222/222348622-ee8bcd9e-3af8-408c-b42e-ec2a6273cd19.png)

![image](https://user-images.githubusercontent.com/968222/222348735-463cef04-ffac-4212-9573-80916e3abdc9.png)

_Originally posted by @terrywh in https://github.com/oven-sh/bun/issues/621#issuecomment-1451364621_

**Comment by Olamarx** [comment]
@Electroid I would like to take up this, can I continue?

**Comment by Electroid** [comment]
> @Electroid I would like to take up this, can I continue?

Absolutely, go for it!

**Comment by Dan1ve** [comment]
I have a `FormData` file upload that doesn't work with Bun (but it _does_ work with Node, as well as from an unrelated webpage.) The upload is rejected by the server with a rather cryptic `Error 415 (Unsupported Media Type) - No consumer for application/octet-stream` . 

I'm mentioning this here to document that there are things in Bun's `FormData` that (still) don't work as expected. Happy to re-test once this issue is resolved.

**Comment by fartek** [comment]
> I have a `FormData` file upload that doesn't work with Bun (but it _does_ work with Node, as well as from an unrelated webpage.) The upload is rejected by the server with a rather cryptic `Error 415 (Unsupported Media Type) - No consumer for application/octet-stream` .
> 
> I'm mentioning this here to document that there are things in Bun's `FormData` that (still) don't work as expected. Happy to re-test once this issue is resolved.

I'm facing the same problem 👀.

**Comment by terrywh** [comment]
any news on this ? @Electroid @Olamarx

**Comment by Olamarx** [comment]
> any news on this ? @Electroid @Olamarx

Hello @terrywh, I tried fixing it but I realized some files are not javascript, which could not run on my machine and it threw errors.

**Comment by paperclover** [comment]
this affects any blob used

and this is holding back discord.js from uploading files
