### ISSUE TITLE
bun --hot reloads twice on file change

### ISSUE THREAD

**Issue by Kapsonfire** [oven-sh/bun#2299]
### What version of Bun is running?

0.5.8

### What steps can reproduce the bug?

```ts
import {Router} from "@kapsonfire/bun-bakery"
import { DEV_RELOAD } from "./dev_reload.ts";
console.log(Date.now(), DEV_RELOAD);
let router = new Router({
    autoListen: false,
    routesPath: './routes/',
    assetsPath: './assets/',
    port: 3333
});

export default router.getListenConfig();
```

changing content of any imported file makes it reloading twice

### What is the expected behavior?

console.log is only triggered once on file change

### What do you see instead?

```
1677926472355 true
1677926472373 true
```

**Comment by Electroid** [comment]
Are you still running into this issue after upgrading Bun? Also, what machine are you using?

**Comment by Jarred-Sumner** [comment]
I don't think this is happening anymore after we made it debounce slightly longer in Bun v1.1.20

**Comment by hyrious** [comment]
I noticed this issue again on Bun 1.3.1 and Windows 11 (25h2).
It may because the `ReadDirectoryChangesW` [receives 2 events on 1 file write operation](https://stackoverflow.com/questions/14036449/c-winapi-readdirectorychangesw-receiving-double-notifications). I have confirmed that happens:

1. I (actually the AI) wrote [a simple C program](https://gist.github.com/hyrious/6246e5bd66e1361937582f58613bd54c) to watch folder changes.
2. I tried to trigger the event by editing a file, through the editor or simple `fs.writeFile` call.
3. I noticed there're 2 (or sometimes 3) file MODIFIED events happen on each write.

Screenshots:

<img width="1007" height="666" alt="Image" src="https://github.com/user-attachments/assets/0ad58e0d-4846-4ece-8bf1-04596b132e56" />

<img width="983" height="161" alt="Image" src="https://github.com/user-attachments/assets/24197f85-2a7b-4c11-be65-6927ef1812a2" />

(The second screenshot is the process monitor to verify there's only one write file call to the system.)
