### ISSUE TITLE
SIGPIPE crash when streaming file through HTTP

### ISSUE THREAD

**Issue by pyxyne** [oven-sh/bun#2356]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.15.0-67-generic x86_64 x86_64

### What steps can reproduce the bug?

Start a basic HTTP server serving a file:
```ts
// server.ts
Bun.serve({
	port: 3000,
	fetch(req) {
		return new Response(Bun.file("./hello.txt"));
	}
});
```
In my tests, "hello.txt" is a text file containing "hello, world!".

Have a client make a request, but close the connection before reading the response:
```py
# client.py
import socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
	sock.connect(("localhost", 3000))
	sock.sendall(b"GET / HTTP/1.1\r\nHost: localhost\r\n\r\n")
```
In my tests, running the Python script above twice triggers the bug.

### What is the expected behavior?

I would expect the server to keep running, maybe reporting a socket error in a recoverable way.

### What do you see instead?

The server process receives a SIGPIPE signal and terminates, with no error message.

### Additional information

Replacing `Bun.file("./hello.txt")` with the literal contents of the file (`"hello, world!"`) seems to stop triggering the crash.

Reading some of the response, but not all of it seems to make the crash less immediate, but does not prevent it. In my tests, I reproduced the crash consistently by using a 1 MiB file with random contents, adding a single `sock.recv(1024)` in the Python script, and running the latter in a loop. It takes a few dozen requests before the crash is triggered.

The Python script manually sending the HTTP header may make this seem artificial, but I encountered this on an actual web application built with Elysia. A few visits to the web server were enough to make the server crash multiple times. Presumably, when navigating too quickly, the browser may abort a download, causing the same "partial read" problem from above.

**Comment by infrahead** [comment]
Was going to file a bug for what I believe is the same thing... multiple canceled requests (i.e. aborted fetches) on the client-side cause Bun process to exit (without seeing any error or segfault), at least when responding with blobs.

My use case probably demonstrates this most clearly.  I wanted to use Bun to make a local/self-contained pmtiles mapping tool, which uses the blob.slice byte-serving approach for the range requests to the file.

But the client-side libraries all use tile cancellation, meaning quick zooming across many levels will interrupt the loading of tiles that are never shown, in order to improve user experience.

It was nice to discover that Bun exposes the AbortSignal on a request to check for this, but unfortunately this is happening after JS is already returning.

Without the delay added in this example code, Bun will exit every time multiple tile requests are canceled.  This happens easily by mouse-wheel zooming in and out of an area.  

```javascript
		// moved out of inline return statement to give better chance of catching fetch cancellation
		const r = new Response(pmtiles.slice(start, end+1))

		// nope. still never see the aborted/cancelled request
		// must be happening while Bun is responding (sendFile'ing?)

		// but a bad hack to show this IS the problem...
		await Bun.sleep(1000)
		// 250-500ms catches most, but had to go even higher for all
		if (req.signal.aborted) {
			console.error(q.signal.reason)
			return // returning nothing in this case prevents exiting
		}

		return r
```

What version of Bun is running?
0.6.4

What platform is your computer?
Linux 5.15.90.1-microsoft-standard-WSL2 x86_64

**Comment by Jarred-Sumner** [comment]
Oh, sendfile() is probably missing MSG_NOSIGNAL
