### ISSUE TITLE
[feature request] webrtc and indexedb support

### ISSUE THREAD

**Issue by shynome** [oven-sh/bun#249]

**Comment by Electroid** [comment]
Thanks for filling this feature request! [WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) and [IndexDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) support would be interesting. However, we're unlikely to prioritize either at the moment, there's a lot of other higher priority items.

Instead of WebRTC, we might introduce [WebTransport](https://github.com/w3c/webtransport/blob/main/explainer.md) support so you can use HTTP3/QUIC. And for IndexDB, while different, we do have a [SQLite](https://github.com/oven-sh/bun#bunsqlite-sqlite3-module) API that is fast and built-in.

Since this is far out, going to close for now, but we may revisit this in the future!
