### ISSUE TITLE
[feature request] dgram module

### ISSUE THREAD

**Issue by skibz** [oven-sh/bun#251]
are there plans to support node's `dgram` or some other type of udp socket module?

**Comment by evanwashere** [comment]
support for tcp and udp is on roadmap #159 
you can also get access to sockets and any other native functionality through [FFI](https://github.com/Jarred-Sumner/bun#bunffi-foreign-functions-interface)

**Comment by skibz** [comment]
thanks :)

**Comment by DonaldFoss-VVV** [comment]
I see this closed as completed, yet bun 0.5.7 doesn't support a

`const udp = require('dgram');`

statement. Is this "completed" as in not-doing-this-now, do-it-with-FFI-somehow ([FFI link](https://github.com/Jarred-Sumner/bun#bunffi-foreign-functions-interface) above is unhelpful) or an undefined meaning of complete?

**Comment by Electroid** [comment]
Support for `dgram` is still planned, it will be tracked here: https://github.com/oven-sh/bun/issues/1630

**Comment by DonaldFoss-VVV** [comment]
Thank you.

--Donald
________________________________
This e-mail contains information which may be privileged, confidential, proprietary, trade secret and/or otherwise legally protected. It is not intended for transmission to, or receipt by, any unauthorized persons. If you are not the intended recipient, please do not distribute this e-mail. Instead, please delete this e-mail from your system without copying it, and notify us that you received it in error, so that our address record can be corrected. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. No waiver of any applicable privileges or legal protections is intended (and nothing herein shall constitute such a waiver), and all rights are reserved.
________________________________
