### ISSUE TITLE
Bun requires typescript project build for javascript for production environment?

### ISSUE THREAD

**Issue by tghpereira** [oven-sh/bun#2553]
### What is the type of issue?

Documentation is confusing

## Is compiling typescript to javascript using babel or another compiler mandatory in a production environment?

My question and that of other users, which was not clarified by the documentation, is how Bun behaves in a production environment.
Is there a need to compile the typescript code to javascript before being sent to the production environment, or can Bun receive the typescript code directly, does this affect performance in production?
The documentation is not clear regarding this topic.

### Where did you find it?

Current documentation url which doesn't give as accurate information at the moment

[https://bun.sh/docs/ecosystem/typescript](url)

**Comment by paperclover** [comment]
the first sentence of the doc page states that you can just run ts files as is, but it doesn't state on how the performance of this works. this could be clarified.

i might be wrong on the following, but bun transpiles every file (js and ts) to properly handle esm imports, commonjs interop, macros, and some other things. **so the overhead of ts vs js is extremely small**, and it's only done for a couple milliseconds on startup, so it should be suitable for production.

typechecking isn't done though, so you should run `tsc` before you go on production

i think details like how this works would be valuable to have in the documentation, maybe in a different section since its not required to use bun, but helpful to understand what is going on and how things TS support works.

**Comment by tghpereira** [comment]
yes @paperdave would be of great help.
Some developers are still afraid to migrate to bun in production because they don't know these details

**Comment by zypher420** [comment]
read the docs :)

https://bun.sh/docs#design-goals

Edit: deleted

**Comment by tghpereira** [comment]
@zypher420 read the issue :)
https://github.com/oven-sh/bun/issues/2553#issuecomment-1498331804

**Comment by zypher420** [comment]
was a littlebit slow with my edit. but bun has his own compiler for ts files on server side. I use for my website vitejs.
and in nodejs you use too webpack,rollup or babel for production in client side.
