### ISSUE TITLE
[install] Support for --no-frozen-lockfile

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#2564]
### What is the problem this feature would solve?

Hi,

I'd like to install production-only dependencies without lock file changes aborting the operation with the following error: `error: lockfile had changes, but lockfile is frozen`, I tried to use `bun install` with the `--production` and `--no-save` flags together but it didn't work. 

This feature request is similar to how pnpm does this with `--[no-]frozen-lockfile`

### What is the feature you are proposing to solve the problem?

Add a similar flag like `--no-frozen-lockfile`

**Comment by lukeed** [comment]
Running into this now in a monorepo setup.

1. Building a service with the `dependencies` marked as externals (during `Bun.build`).
2. Within Dockerfile, copy over the built file(s)
3. Within Dockerfile, copy over the `package.json`
4. Trying to run `bun install --production` -> fails with OP's error

I get the same error locally even after removing `bun.lockb` and `node_modules`. 
Seems like `bun install --production` doesnt work at all

**Comment by KishCom** [comment]
Can confirm still in 1.0.0

Hit this problem while moving a Dockerfile based deploy from Node.js to Bun.

**Comment by dylan-conway** [comment]
This issue is addressed in bun `v1.1.2` and newer versions. Instead of `--no-frozen-lockfile`, `--production` was changed to allow installing without an existing lockfile (and still exclude `devDependencies`), similar to npm, yarn, and pnpm.

Closing as complete, but please reopen this issue if you still have a use case for `--no-frozen-lockfile`
