### ISSUE TITLE
overriding `env` object not working

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#2696]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```
console.log('before', process.env.PORT);
process.env = {
	...process.env,
	PORT: '0',
};
console.log('after', process.env.PORT);
```

run the code with bun and node

### What is the expected behavior?

```
before undefined
after 0
```

### What do you see instead?

```
before undefined
after undefined
```

### Additional information

I am not sure if one should be able to override the env object but since node allows doing so bun should too because of compatibility.

**Comment by paperclover** [comment]
Related to https://github.com/oven-sh/bun/issues/556

This happens because we are inlining `process.env.*` (as if you're using `--define`) at the moment

This case doesnt throw an error like the other issue because `process.env` itself doesn't get replaced but both usages of `process.env.PORT` are replaced before the program is started. We shouldn't be doing this transform outside of bundling.

**Comment by simylein** [comment]
As of bun version 0.7.1 this is working. Thank you for fixing this 🙂
