### ISSUE TITLE
Readonly on global

### ISSUE THREAD

**Issue by sp90** [oven-sh/bun#3129]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

1. Goto - https://github.com/sp90/reproduce-bun-readonly-global
2. Clone
3. Run `bun run dist/reproduce-bun-readonly-global/server/main.js`

I have precompiled the code but there are a guide in the repo if the code recompiled should be done

### What is the expected behavior?

Should start the server

### What do you see instead?

<img width="790" alt="Screenshot_2023-05-30_at_10 22 48" src="https://github.com/oven-sh/bun/assets/3041602/aca850dd-b184-452b-a669-e2fe25eb417e">

### Additional information

Its an angular precompiled frontend, that is served using their universal addition, which normally works on node, and that implementation uses express under the hood

**Comment by xhyrom** [comment]
Trying to figure out why this happens, because

```js
const things = {
  lol: class Test {
    constructor() {
      this.a = 1;
    }
  },
  xdd: "looool",
  someNumber: 5,
};

Object.assign(global, things);

console.log(global.lol);
```

works fine, ill look deeper

**Comment by arturovt** [comment]
@xHyroM this happens because Angular is using `domino` package for its server-side rendering and trying to expose `domino` globals onto the `global` scope:
```js
import domino from 'domino';
Object.assign(globalThis, domino.impl);
```

It fails to run `Object.assign` because `domino.impl`  contains `Event` and `DOMException` objects which are already available on the `globalThis` in Bun (compared to Node.js environment). You can try to run the following code:

```sh
$ echo "console.log(globalThis.DOMException)" > test.js
$ node test.js
undefined
$ bun test.js
{ name: "DOMException", prototype: { ... } }
```

Given the following example:

```js
const originalImpl = globalThis.DOMException;

globalThis.DOMException = function () {
  console.log('I am patched...');
  return originalImpl.apply(this, arguments);
};
```

This will fail with the same error `Attempted to assign to readonly property.`.
