### ISSUE TITLE
`onSuccess` bundler hook

### ISSUE THREAD

**Issue by o-az** [oven-sh/bun#3194]
### What is the problem this feature would solve?

Often we need to run some code upon successful build step.

In `tsup` it's:

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  entryPoints: ['./index.ts'],
  // ...
  onSuccess: async () => {
    // ... do something here
  }
})
```

### What is the feature you are proposing to solve the problem?

Add `onSuccess` to `Bun.build`

```ts
interface BuildConfig {
  onSuccess?: string | (() => Promise<void | undefined | (() => void | Promise<void>)>);
  // ...
}
```

### What alternatives have you considered?

shell script

**Comment by paperclover** [comment]
hmm, in bun you would be calling the method directly `Bun.build`, and to run code on success/fail, you would just await the promise and check `.success`.

Not sure if we should implement this because it feels redundant to me, especially since bun doesnt consume the config as a file like tsup is doing.

**Comment by paperdave** [comment]
realizing this is a duplicate of #2771's `onEnd` plugin hook. it would be given a parameter containing the build result, so turning that into an "onSuccess" would be an `if` there
