### ISSUE TITLE
Since version 0.6.3, websockets don't publish data

### ISSUE THREAD

**Issue by nickyhajal** [oven-sh/bun#3285]
### What version of Bun is running?

0.6.3 and up

### What platform is your computer?

MacOS and Fly.io (debian)

### What steps can reproduce the bug?

I have a websocket server that had been working but suddenly stopped sending messages. To test if my implementation was wrong, I found this very simple Bun Chat application: https://github.com/monroeclinton/bun-chat/tree/main

Surprisingly - it had the same issue as my server.

So, I tried downgrading several versions and eventually realized that at version 0.6.3, both of our implementations stopped working.

### What is the expected behavior?

`ws.publish('channel', {data})` should publish the message to subscribers and return the number of bytes sent

### What do you see instead?

`ws.publish('channel', {data})` always returns 0

**Comment by Jarred-Sumner** [comment]
i have a guess for why this is happening and I’m sorry we didn’t make this breaking change clearer in the runtime to warn you 

can you switch your code to use server.publish instead of ws.publish? Or set publishToSelf: true in the `websocket` object 

You can read about the breaking change here: https://bun.sh/blog/bun-v0.6.3#breaking-change-to-publishtoself-behaviour
