### ISSUE TITLE
Sourcemaps should contain `sourceMappingURL`

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3325]
### What version of Bun is running?

0.6.10

### What platform is your computer?

macos

### What steps can reproduce the bug?

Currently no source maps are working when using `sourcemaps: 'external'`. `sourceMappingURL` is not appended.

It also breaks `stacktrace-gps` package which requires this.

Confirm via `Developer Resources` in DevTools: https://developer.chrome.com/docs/devtools/developer-resources/

**Comment by PfisterFactor** [comment]
`sourcemap=inline` seems to be doing nothing as well (doesn't append the base64 comment to the file)

**Comment by mangs** [comment]
I've run into this bug too. Source maps don't seem to be working at all no matter what I try. I'm on macOS, x86, and Bun v1.0.7.

**Comment by spamshaker** [comment]
same issue here - it seems also doubles the entires in map while external option

{
  "version": 3,
  "sources": ["../src/main.ts", "../src/main.ts"],
  "sourcesContent": [

**Comment by raylu** [comment]
according to the docs https://bun.sh/docs/bundler#sourcemap, the bundled files use sentry's debugId proposal. unfortunately, it's not implemented anywhere but sentry, as far as I can tell

you can get firefox to use sourcemaps by sending the `SourceMap` header. https://caniuse.com/mdn-http_headers_sourcemap claims that chrome supports this, but it doesn't (https://stackoverflow.com/q/54142925/385891)

would the bun team welcome a small change to append `sourceMappingURL` too?

**Comment by Jarred-Sumner** [comment]
> would the bun team welcome a small change to append `sourceMappingURL` too?

definitely

@paperdave has more recent context than me, but the relevant places I think are:

https://github.com/oven-sh/bun/blob/33ca0921f246487ff2f97d5bc3b36c7084725722/src/bundler/bundle_v2.zig#L11365-L11374

https://github.com/oven-sh/bun/blob/33ca0921f246487ff2f97d5bc3b36c7084725722/src/bundler/bundle_v2.zig#L11253-L11256

https://github.com/oven-sh/bun/blob/33ca0921f246487ff2f97d5bc3b36c7084725722/src/bundler/bundle_v2.zig#L11338-L11343

You can see that originally this was where `sourceMappingURL` was going to go

It probably needs to be relative to `public_path` when that is not empty, which is joined by using `cheapPrefixNormalizer`:

https://github.com/oven-sh/bun/blob/33ca0921f246487ff2f97d5bc3b36c7084725722/src/bundler/bundle_v2.zig#L11236-L11241

A lot of bun's bundler code was originally a port of esbuild so that's another codebase you can use as a point of reference

**Comment by paperdave** [comment]
linked pr does what esbuild does with the "linked" sourcemap option, but the difference in us is that --sourcemap without any options defaults to `inline` sourcemap and not the linked one.
