### ISSUE TITLE
Can't destructure json imports: SyntaxError: Import named 'name' not found in module '/home/hussein/Desktop/project/package.json'

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#3387]
### What version of Bun is running?

0.6.9

### What platform is your computer?

debian 11

### What steps can reproduce the bug?

This works:

```js
import pkg from "./package.json";
console.log(pkg.name);
```
But this doesn't:

```js
import { name } from "./package.json";
console.log(name);
```

I also found this error when using Deno

**Comment by Jarred-Sumner** [comment]
While JSON imports are default-only, this is supposed to work and it's a regression

**Comment by simylein** [comment]
I just tested a lot of different bun versions. I think this never worked to begin with. There is a change in error output when going from 0.1.x to 0.2.x and above though.

**Comment by huben1337** [comment]
i'm having a similar issue.
![grafik](https://github.com/oven-sh/bun/assets/88612147/b8512c4d-4437-4f3a-be0d-99dad4848266)

**Comment by OliverWich** [comment]
I am seeing the same issue with bun 1.0 on WSL2 when running `bun test`. It is also failing to import something from package.json using named imports. 
It produces some weird looking log too:
![BunTestError](https://github.com/oven-sh/bun/assets/35409274/af26cf25-5a2c-42db-82ec-b1cc147e0a7d)

**Comment by nmussy** [comment]
I can also confirm that this issue only affects the `run`/`test` commands. The bundler supports named imports:

https://github.com/oven-sh/bun/blob/ffe4f561a3af53b9f5a41c182de55d7199b5d692/test/bundler/bundler_edgecase.test.ts#L340-L354

I'll try and look into it, see what I can find

EDIT: Just realized that test is currently not being ran, but does work if `dce` is disabled (as well as `todo`, to get the test running). That does line up with what I was seeing when running `bun 1.0`. `bun build` works, but `run` and `test` do not. `repl` also interprets the named JSON imports correctly

**Comment by nmussy** [comment]
Alright, so here are my findings. Imported JSON files are being transpiled by `transpileSourceCode` into CommonJS modules with a default export, like so:
```ts
// Current transpilation of test.json
export default { hello: 234, world: "REMOVE" };
```

Which makes the following operation illegal in CommonJS, since there are no named exported properties:
```ts
// Throws: "SyntaxError: Import named 'hello' not found in module"
import file, { hello } from './test.json.js';

// The following would be fine:
import file from './test.json.js';
const { hello } = file;

// This is also expected to work in TypeScript, with JSON files:
import file, { hello } from './test.json';
```

`bun build` works around this issue because it inlines the JSON object, and creates variables to replace the named imports:
```ts
// test.json
var hello = 234;
var test_default = {
  hello,
  world: "REMOVE"
};

// index.ts
console.log(test_default, hello);
```

This could be solved for `run` and `test` by changing the transpilation logic. We could keep the default export, but also evaluate the named imports, and to add the corresponding named exports:

```ts
// Proposed transpilation of test.json
export default { hello: 234, world: "REMOVE" };
export hello = 234;

// index.js can remain as is
import file, { hello } from './test.json.js';
```

I'm not familiar enough with the codebase to be sure this would be the ideal solution. If I can get a green light from a maintainer (or another suggestion,) I could try and make a PR out of it.
