### ISSUE TITLE
version `GLIBC_2.29' not found (required by bun)

### ISSUE THREAD

**Issue by jasil2215P** [oven-sh/bun#340]
![Screenshot from 2022-07-07 14-52-42](https://user-images.githubusercontent.com/100070014/177740398-82012d71-a647-4488-bfa8-adbae9c58565.png)
I am running ubuntu 18.04 LTS

whenever I tried to run bun it just throws an error 
bun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by bun)
bun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by bun)

**Comment by akomm** [comment]
18.04 LTS: `/lib/x86_64-linux-gnu/libc.so` comes from `libc6-dev` package: [file search](https://packages.ubuntu.com/search?suite=bionic&arch=any&searchon=contents&keywords=%2Fusr%2Flib%2Fx86_64-linux-gnu%2Flibc.so)

Looks like the libc version there is `2.27` and that is the problem [package details](https://packages.ubuntu.com/bionic/libc6-dev). Your version of bun asks for `2.29`.

I'v installed with explicit version of last release using: `curl https://bun.sh/install bun-v0.1.1 | bash` and it asks for `2.28` as its a bit older than the `latest` you have. But I have obviously same problem. 

- You can run it with older bun version (just lookup releases on github). 
- Or you can get manually libc at the required version.

It appears bun executable (amd64 v0.1.1) doesn't make a typical lookup, it wants the .so exactly there. So it forced you to replace the libc6-dev one and I don't think its a good idea, since other packages might rely on the version 2.27...

**Comment by FinnRG** [comment]
Duplicate of #255. Please close this issue.

**Comment by moderation** [comment]
Thanks for your work in trying to close multiple duplicate issues @FinnRG
