### ISSUE TITLE
`peer = true` in `bun.toml` seems to have no effect

### ISSUE THREAD

**Issue by EvHaus** [oven-sh/bun#3410]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Windows Ubuntu Bash

### What steps can reproduce the bug?

Using the following `package.json` file:

```json
{
	"name": "test",
	"version": "0.0.1",
	"type": "module",
	"dependencies": {
		"html-react-parser": "^4.0.0"
	}
	"peerDependencies": {
		"react": "^18.2.0",
		"react-dom": "^18.2.0"
	}
}

```

And the following `bun.toml` file:

```toml
[install]

peer = true
```

Run `bun install` in the folder.

### What is the expected behavior?

I expect the `react` and `react-dom` dependencies to get installed.

### What do you see instead?

Only `html-react-parser` gets installed. Output is:

```
bun install v0.6.9 (2ab797ff)
 + html-react-parser@4.0.0
```

**Comment by Jarred-Sumner** [comment]
Confusingly, it seems that flag only applies to non-local dependencies. It installs peer dependencies of dependencies instead of "peerDependencies" from local packages.

https://github.com/oven-sh/bun/blob/96a255fc065e7eb29ac5c7d9fee5977f7de12689/src/install/install.zig#L4434

**Comment by zfben** [comment]
I have the same issue and I use mac os and bun 0.6.14.

**Comment by tobi-or-not-tobi** [comment]
@Jarred-Sumner I've tested this a few times with various versions of bun (did it again with 0.7.1 today), but I'm not able to get peer dependencies installations to work. I'm not using peer dependencies in the local dependencies, they are provided by the packages that I use in package.json. 

When I use a boilerplate project uses a package that brings both dependencies and peer dependencies, the dependencies are installed, but the peer dependencies are not. 

This one is stopping me for a long time to get the team excited about bun, as we do want to keep the boilerplate as lean as possible and rely on the packages to bring their 

Let me know if you like a reproduction.

**Comment by omarkhatibgg** [comment]
I just tested version 1 and the problem still exists
`bun install` won't install your `peerDependencies`

**Comment by tobi-or-not-tobi** [comment]
Seems not a feature anymore, I noticed its been dropped from the docs.

**Comment by johnnyhuirilef** [comment]
I've been testing version **1.0.1** of bun, and it doesn't seem to install peer dependencies. After reading the [documentation](https://bun.sh/docs/runtime/configuration#default-flags) , it mentions that the configuration file is named bunfig.toml. I tried adding 'peer = true', but it didn't yield any results. Whether I run the `bun install` command or `bun install --config=bunfig.toml`, it appears that the CLI's API is ignoring 'peer' because when I use `bun install --help`, the flag is not found.

**Comment by DrKabum** [comment]
Same issue here. Maybe I'm doing it wrong but I've been trying to use `eslint` in my Bun project and it won't work because `typescript` is not installed in the project.
As per [documentation](https://bun.sh/docs/runtime/bunfig#install-peer), in `bunfig.toml` at the root of my project, I tried:
```toml
[install]
peer = true
```
but it still won't install.

```
bun --version
1.0.0
```
