### ISSUE TITLE
Implement `server.requestIp`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#3540]
```js
export default {
  async fetch(request, server) {
    return new Response(server.requestIp(request));
  }
}
```

**Comment by simylein** [comment]
Can we put this onto the Wishlist for the bun v1 release?

**Comment by Jarred-Sumner** [comment]
@Parzival-3141 want to turn your code for this from before into a PR?

**Comment by phtdacosta** [comment]
And I thought I was alone when I asked for it Hahahahah

**Comment by farzher** [comment]
it's impossible to get the client ip address. pls help +1

**Comment by crimson-med** [comment]
Looking forward the the PR from @Parzival-3141
Thanks a lot!

**Comment by 0x464e** [comment]
I want to bump this issue by saying I really wish this just existed.  
I just had to abandon my whole Bun project and move back to NodeJS due to there not being support to get the remote requester's IP and port in Bun.

To make it clear what I mean, in NodeJS this is all that's needed:
```js
import http from 'http';

http.createServer((req, res) =>
    console.log(req.socket.localAddress, req.socket.remoteAddress, req.socket.remotePort)
).listen(8000);
```
It logs the server's ip address, the remote requester's ip address, and the remote requester's port.

**Comment by ImLunaHey** [comment]
@0x464e you could have thrown a reverse proxy in front of it instead of moving back to nodejs.

**Comment by 0x464e** [comment]
> @0x464e you could have thrown a reverse proxy in front of it instead of moving back to nodejs.

How would that work? I'm not familiar with these things.  
But either way, not sure that would have worked for my needs because this was for a specific university assignment.

**Comment by mattbeiswenger** [comment]
This is also an issue I'm running into with a project. Yes, a reverse proxy is a workaround but requires more infrastructure setup and reduces performance and the _amazing_ performance of bun is what draws developers to it in the first place!

I understand that in order to keep bun performant some tradeoffs are required but this seems necessary to me. Any application that uses internal rate limiting without a required api key will be using the ip address in order to limit requests and prevent DDos attacks (I'm currently trying to implement this with [@upstash/ratelimit](https://github.com/upstash/ratelimit)).

**Comment by pi0** [comment]
This is amazing to add! Will magically also fix `getRequestIP` h3 util for nitro/nuxt!

BTW, not me, but the AI goddess's words: 

<img width="780" alt="image" src="https://github.com/oven-sh/bun/assets/5158436/ac6cdd0b-01df-4299-ae92-35edc9e11005">
 
Update: above is a joke :)

**Comment by phtdacosta** [comment]
@pi0 LOL

If you want to be pedantic, the better argument would be that conventionally, JavaScript/NodeJS naming when it comes to acronyms is that all letters must be uppercase so getRequestIP actually does make more sense according to the naming convention (eg: ```new URL```)

**Comment by phtdacosta** [comment]
![image](https://github.com/oven-sh/bun/assets/8548534/8cbc5967-7007-4233-8577-2094de7d729c)
It was actually a poll on Twitter Hahahahahah

**Comment by Avaray** [comment]
Ok, but is this implemented already?

**Comment by Avaray** [comment]
```ts
async fetch(req) {
    const ip = this.requestIP(req)?.address.split(":").pop();
    console.log(ip);
}
```
