### ISSUE TITLE
Missing last byte when serving static files

### ISSUE THREAD

**Issue by RobotoSkunk** [oven-sh/bun#3668]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Linux 6.3.0-1-amd64 x86_64 unknown

### What steps can reproduce the bug?

1. Install `express` and `compression` packages.
2. Configure compression to work with express.
3. Serve static files with express.
4. Add some example files to the static directory.
5. Start the server.
6. Try loading any static file.

### What is the expected behavior?

The whole file is being sent across HTTP.

![image](https://github.com/oven-sh/bun/assets/49355293/f7faba06-432f-4659-be23-7083d53f3ffb)

### What do you see instead?

The last byte (or bytes) is missing in the file, so, things like WebP, JPG, BMP and other files are affected.

![Screenshot_20230726_190405](https://github.com/oven-sh/bun/assets/49355293/ac79c6f9-6d0d-4bd5-881b-6488b8112008)

### Additional information

I have a repository prepared to test Bun (https://github.com/RobotoSkunk/personal-website/).

If you're going to use it, run it and check out the `/assets/img/*` URL path (`public/assets/img/*` in the repo), there are prepared files to test.

This does not happen with Node.js

**Comment by Hanaasagi** [comment]
After some debugging, I believe the minimal reproducing code for this bug is as follows:

### Step 1 create a test file

```Bash
echo -n 12345 > test.txt
```

### Step 2 minimal http static server

index.js

```JavaScript
var http = require("http");
var send = require("send");

var server = http.createServer(function onRequest(req, res) {
  send(req, "./test.txt").pipe(res);
});

server.listen(8080);

```

*NOTE: express utilizes the server-static package to handle static routes, and this package depends on the send package.*

![2023-07-27_23-12](https://github.com/oven-sh/bun/assets/9482395/59d42d30-21f3-4a47-9c9f-331fd60a6476)

The content-length here is also calculated incorrectly (should be 5 not 4).


----

Updated:

I set the debugging flag for this file https://github.com/oven-sh/bun/blob/main/src/js/node/stream.js and found some interesting logs.


![2023-07-28_03-07](https://github.com/oven-sh/bun/assets/9482395/71ffdc59-4231-4c5e-b0d6-f81010ef2cac)

Some callstack


https://github.com/oven-sh/bun/blob/704ee133923a4e28bd51bc95b56eb54d50424c17/src/js/node/stream.js#L5359-L5368


https://github.com/oven-sh/bun/blob/704ee133923a4e28bd51bc95b56eb54d50424c17/src/js/node/stream.js#L5216-L5222

https://github.com/oven-sh/bun/blob/704ee133923a4e28bd51bc95b56eb54d50424c17/src/js/node/stream.js#L2595-L2602
