### ISSUE TITLE
Update shell completions

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#4016]
Our fish, bash, and zsh completions are very out of date

**Comment by janwilmake** [comment]
What completions?

I noticed, by default, VSCode completions import other files via index (I have an index.ts file that re-exports all files via `export * from "./file"`.) I was wondering if it can be setup in a way that it imports it from the original file instead of from index.

Is that a bun thing or vscode?

**Comment by Hanaasagi** [comment]
working on zsh part https://github.com/oven-sh/bun/pull/4428

**Comment by AnishKacham** [comment]
Can I work on the bash completions. I've checked the related PRs and I think it's still incomplete?

**Comment by nektro** [comment]
duplicate of #2503
