### ISSUE TITLE
bun install with Gitlab repository in dependencies not working

### ISSUE THREAD

**Issue by DrWarpMan** [oven-sh/bun#4068]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 6.4.7-arch1-1 x86_64

### What steps can reproduce the bug?

1. `bun init`
2. Add Gitlab dependency like this, in `package.json`:
```
"dependencies": {
    "package": "git+ssh://git@gitlab.example.com:foobar.git"
}
```
3. `bun install`

### What is the expected behavior?

Gitlab dependency should be installed without errors.

### What do you see instead?

```
bun install v0.7.3 (a9b3d583)
  🔍 Resolving [1/1] 
error: InstallFailed cloning repository for "<package-name>"
error: "git clone" for "<package-name>" failed
error: "git clone" for "<package-name>" failed
```

### Additional information

1. HTTPS protocol works, SSH doesn't.
`git+https://gitlab.example.com/foobar.git` ✅ 
`git+ssh://git@gitlab.example.com:foobar.git` ❌ 

2. `npm install` works just fine.

3. I would assume this might be an issue on Github as well, haven't tested though.

**Comment by mozkomor05** [comment]
Git supports two URL syntaxes for SSH cloning:
1. `git clone git@gitlab.example.com:foobar.git`
2. `git clone ssh://git@gitlab.example.com/foobar.git` (notice the use of a slash instead of a colon)

So, in a way, it makes perfect sense for Bun not to support `git+ssh://git@gitlab.example.com:foobar.git`. However, NPM does support it, and for Bun to be a drop-in replacement, it should also support it.

In my opinion, it makes sense to incorporate a `trySSH` logic that would check different SSH url formats, similar to the existing `tryHTTPS`, similar to how it's done here: 

https://github.com/oven-sh/bun/blob/3a9a6c63ac58564d8bae126a3edfc368ca4be671/src/install/install.zig#L666-L684

**Comment by DrWarpMan** [comment]
https://docs.npmjs.com/cli/v9/commands/npm-install#description

```
npm install git+ssh://git@github.com:npm/cli.git#v1.0.27
npm install git+ssh://git@github.com:npm/cli#pull/273
npm install git+ssh://git@github.com:npm/cli#semver:^5.0
npm install git+https://isaacs@github.com/npm/cli.git
npm install git://github.com/npm/cli.git#v1.0.27
```
Here are the formats that NPM supports.

**Comment by Eckhardt-D** [comment]
Is there any feedback on this? v1.0.5 still cannot clone private `git@gitlab.com:org/repo.git` urls. It attempts the clone but fails, assuming that it's either an issue with missing ssh key in the connect or something else. The error is quite vague:

```
error: FileNotFound cloning repository for db-migrations
```

Is it perhaps trying to look at Github instead of Gitlab?

**Comment by h2oearth** [comment]
I tested the latest version (1.0.6) , and the public repos seem to work, but I can not access my private repos. :-/

**Comment by Eckhardt-D** [comment]
> I tested the latest version (1.0.6) , and the public repos seem to work, but I can not access my private repos. :-/

That seems like Bun install is not using the ssh key. id_rsa gets automatically used in other pm’s. @Jarred-Sumner 

it should also handle for example (~/.ssh/config):

```
Host gitlab.com
     IdentityFile ~/.ssh/gitlab_key
     IdentitiesOnly yes
```

**Comment by MikkelSVDK** [comment]
I have the same issue, bun does not use my public key to download from a git repo.

Resulting in this mess
```
bun install v1.0.11 (f7f6233e)
[3.32ms] migrated lockfile from package-lock.json
Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com': Username for 'https://git.mygitrepo.com':   🚚 brace-expansion

error: no commit matching "semver:~1.0.0" found for "@my-app/project" (but repository exists)
```

My package.json looks like this
```
{
  ...
  "dependencies": {
    "@my-app/project": "git+ssh://git@git.mygitrepo.com/my-app/project.git#semver:~1.0.0",
    ...
  }
}
```

Another note is, the terminal stops displaying any characters you type, cause it somewhere disables the output, but never enables it again after i fails.

**Comment by Eckhardt-D** [comment]
Obligatory 6 month follow-up. Installing private GitLab repos with bun + shh (using any ssh URL) does not work. The installer prompts for the ssh password, when it should be using the host's SSH key. 🔑

**Comment by h2oearth** [comment]
Any news @bun team?
