### ISSUE TITLE
--bun flag adds +300 ms

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4143]
### What version of Bun is running?

0.7.4+78defe7a87226b5b10766e24fae458a62811dab2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

* `bun init`
* add this to package.json

```
  "scripts": {
    "dev": "echo \"test\""
  }
```

Run `bun --bun run dev` (387 ms)
Run `npm run dev` (225 ms)
Run `bun run dev` (59 ms)

The way I logged the runtime was:

```sh
start_ms=$(ruby -e 'puts (Time.now.to_f * 1000).to_i')
bun run dev      
end_ms=$(ruby -e 'puts (Time.now.to_f * 1000).to_i')
elapsed_ms=$((end_ms - start_ms))
echo "$elapsed_ms ms passed"
```

### What is the expected behavior?

I didn't expect --bun to add this much runtime

### What do you see instead?

> 300 ms added

### Additional information

I didn't expect --bun to add this much runtime. I've seen indications ([link](https://github.com/withastro/astro/pull/7944#issuecomment-1666084805)) that --bun likely won't be needed from v1, what does that exactly mean? That it's added always under the hood, adding this overhead, or will the overhead go away then?

**Comment by Jarred-Sumner** [comment]
i wonder what's going on here

**Comment by Jarred-Sumner** [comment]
It looks like there's a syscall run during --bun which causes a 300ms delay in a small % of runs on macOS

<img width="790" alt="image" src="https://github.com/oven-sh/bun/assets/709451/6fa1ac67-39c6-495f-bc99-de52c9fbbcee">

**Comment by kapolos** [comment]
This also happens with Vite (env: WSL 2):

`yarn dev`
![image](https://github.com/oven-sh/bun/assets/10794126/e93ce997-0387-4251-82bd-42edadabb667)

`bun --bun run dev`
![image](https://github.com/oven-sh/bun/assets/10794126/ce596219-d972-43da-b363-8d610d110849)

I run both multiple times each to prime any possible caching. While running bun I also disabled the `@vitejs/plugin-basic-ssl` since `node:http2 createSecureServer is not yet implemented in Bun.`, so it would probably be a tad slower with that on.
