### ISSUE TITLE
`bun run dev` acts differently than `bun dev`

### ISSUE THREAD

**Issue by wintercounter** [oven-sh/bun#4166]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 5.15.90.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. `bun create react app`
2. `cd app`
3. `bun dev` => all static assets will be 404
4. `bun run dev` => works fine

### What is the expected behavior?

No 404s.

### What do you see instead?

404 for every static asset for `public` and `build` dir.

### Additional information

I tried to add some logs to `dev.tsx` and there is nothing logged when using `bun dev` command. It's like it's not even using that `dev.tsx` file.

**Comment by Aakarshak1** [comment]
I have noticed the same issue with bun v0.07.3 on MacBook Also if you update the `app.tsx` file it is not getting reflected in the UI.

**Comment by mi4uu** [comment]
why should it works the same?
those are different command, one is automagically try to create dev server, second one run dev script from your package.json

**Comment by wintercounter** [comment]
Well it's quite misleading then. Seems like the basic react template is
even more broken.

Why does it ask me to run bun dev if it's not working?
Why does it have its dev.tsx and dev script if it should?

It's off-topic, but both watch and hmr are broken as they don't
work on build entries and the only entry is dev.tsx where it works...

I tried to use bun for the first time and burnt myself at dozens of places.
I went back to Node for this project. The very least I'd expect is a
working basic React template.

I know all these are the fault of the template and not bun itself, but it drove
me quite crazy at the end.

**Comment by JusttCallMeMike** [comment]
I know what you mean, this template is not usable in my opinion (yes, you can run it but no one would torture itself to develop is such conditions) . thats why I made alternative template, check this: https://github.com/oven-sh/bun/issues/4184

**Comment by Jarred-Sumner** [comment]
yeah I'm pretty unhappy with the current state of frontend dev using Bun

We've neglected `bun dev` and are expecting to replace it entirely with a different `bun build`-powered implementation, but it is unlikely we will get to it before 1.0

**Comment by Hebilicious** [comment]
@Jarred-Sumner Any chance you could just rename `bun dev` to `bun serve` in the meantime ? 
`dev` is a very common script in package.json. Tbf the same could be said for `build`, but `dev` => `serve` makes sense imo.

**Comment by mi4uu** [comment]
If there will be enough ppl interested in this, I mean there will be visible demand right now for something like hmr for react, I think I can make this work (might not be very elegant at first ;p ) and incorporate something like this into my template, but I have no idea if there is a big demand for something like this, making it without any reason, knowing there is a plan for bun to support this native in the future might not be best idea if there are like 3 ppl who would like to see it xD 
but if that's something that ppl need, then sure, I might spend some time to make it happen. 

will see if this template will help someone, or if it was just a waste of time ;p (not totally, since I will use it xD)


@Jarred-Sumner are there any specific point in time, where it is planned to implement this feature into bun? or it is more of an unknown future and not as important feature to put this into any real plan?

**Comment by g-wozniak** [comment]
Tried right now on Mac with the above, same issues. 
- With bun `0.7.3`, launching `--hot` and `--watch` don't have any effect.
- `bun dev` and `bun run dev` have different behaviour; the latter works; the first throws 404s regardless of running

**Comment by birkskyum** [comment]
Related to
- #485

**Comment by paperclover** [comment]
bun dev is a very old command that predates alot of stuff. it barely works now. we are simply going to just delete it.

it will do what most expect it to now.

![image](https://github.com/oven-sh/bun/assets/24465214/3e79a844-5252-479f-b4f6-7888e4ef1263)
