### ISSUE TITLE
`unlinkSync` throws EPERM when the target file doesn't exist

### ISSUE THREAD

**Issue by riywo** [oven-sh/bun#4198]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

`foo.js`:

```js
import { unlinkSync } from "node:fs";

unlinkSync("aaaa");
```

```
$ ls
foo.js

$ bun foo.js   
1 | import { unlinkSync } from "node:fs";
2 | 
3 | unlinkSync("aaaa");
   ^
EPERM: Operation not permitted
   path: "aaaa"
 syscall: "unlink"
   errno: -1

      at /foo/foo.js:3:0
```

### What is the expected behavior?

Node.js returns `ENOENT`, so `ENOENT` is expected:

```
$ node foo.js  
node:fs:1899
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, unlink 'aaaa'
    at unlinkSync (node:fs:1899:3)
    at file:///foo/foo.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'aaaa'
}

Node.js v20.5.1
```

### What do you see instead?

`EPERM` like above:

```
EPERM: Operation not permitted
   path: "aaaa"
 syscall: "unlink"
   errno: -1

```

### Additional information

Probably due to this difference, `eslint` doesn't work with Bun runtime:

```
$ strace -f bun eslint
...
[pid 14449] unlink("/foo/.eslintcache") = -1 ENOENT (No such file or directory)
[pid 14449] write(2, "\33[0m\33[31m", 9) = 9
[pid 14449] write(2, "\nOops! Something went wrong! :(\n"..., 544
Oops! Something went wrong! :(

ESLint: 8.47.0

EPERM: Operation not permitted
    at unlinkSync (native)
    at executeOnFiles (/foo/node_modules/eslint/lib/cli-engine/cli-engine.js:785:14)
    at <anonymous> (/foo/node_modules/eslint/lib/eslint/eslint.js:551:8)
    at lintFiles (/foo/node_modules/eslint/lib/eslint/eslint.js:543:13)
    at <anonymous> (/foo/node_modules/eslint/lib/cli.js:393:20)) = 544
```

**Comment by riywo** [comment]
See also https://discordapp.com/channels/876711213126520882/887787428973281300/1141939984971071590

**Comment by Jarred-Sumner** [comment]
@paperdave was looking at this earlier today

**Comment by paperclover** [comment]
so what i found so far is that its linux only, and probably some mistake with enums.

i haven't had time to debug this on my linux box but i will in the next couple of days, should be really easy to identify once i can actually step through the code with a debugger.

**Comment by Hanaasagi** [comment]
Perhaps it's directly using the return value as the `errno` value. Because when `unlink` got an error, it returns -1, while the value of `EPERM` is 1.


EDIT:
https://github.com/oven-sh/bun/blob/53c755467bda33e90161d809a4ab55388b812698/src/bun.js/node/syscall.zig#L188-L197

On drawin, it will use `system.getErrno`, which automatically reads the value of `errno` if the libc has been linked.

https://github.com/ziglang/zig/blob/ddf5859c22527c6bf5d8bb13310db996fcc58874/lib/std/os.zig#L274-L280

https://github.com/ziglang/zig/blob/ddf5859c22527c6bf5d8bb13310db996fcc58874/lib/std/c.zig#L114-L120


If call `std.os.linux.getErrno` directly, it will only use the return value, no `errno`


https://github.com/ziglang/zig/blob/ddf5859c22527c6bf5d8bb13310db996fcc58874/lib/std/os/linux.zig#L206-L211
