### ISSUE TITLE
missing script error when run a empty file

### ISSUE THREAD

**Issue by RolloMellette** [oven-sh/bun#4238]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
bun init
truncate index.ts -s 0
bun run index.ts
```

### What is the expected behavior?

No error.

### What do you see instead?

```
error: missing script "index.ts"
```

**Comment by RolloMellette** [comment]
Actually, using `bun index.ts` won't  report an error. Is there any difference between `bun index.ts` and `bun run index.ts`?

**Comment by Hanaasagi** [comment]
#### Debug info

https://github.com/oven-sh/bun/blob/07d8623976cd5fe1b11dd13f6988cd02e4fc5c15/src/cli/run_command.zig#L952-L963

Because it's an empty file, the `shebang` is also an empty string. This causes it to break to the `:possibly_open_with_bun_js` and then fall back to searching for `scripts` in the `package.json`. Of course, it won't find any script named `index.ts`.

**Comment by ejuarezg** [comment]
I am running into a similar issue. On one computer both `bun run script-name` and `bun script-name` work fine, but in another I get the "missing script" error when running `bun run script-name`

**Comment by JeremyFunk** [comment]
Implemented a fix [here](https://github.com/oven-sh/bun/pull/4907), still need to add a test.
