### ISSUE TITLE
SvelteKit unable to set two cookies?

### ISSUE THREAD

**Issue by gitblit** [oven-sh/bun#4285]
### What version of Bun is running?

0.8.0+20d42dfaa3c23c1302dd3d5837ba6714dc891ac4

### What platform is your computer?

WSL2

### What steps can reproduce the bug?

My SvelteKit app sets two cookies when the user logs in:
1. a session UUID cookie
2. an identify cookie with a minimal user object

```js
    // Expire cookies with this max age
    cookies.set(SESSION_COOKIE, sessionId, { maxAge });
    cookies.set(IDENTITY_COOKIE, JSON.stringify(identity), { maxAge });
```

Under Node, two cookies are created and transferred to the browser. Under Bun, the first cookie is properly created & transferred to the browser but the second cookie does not exist.

### What is the expected behavior?

Two cookies in the browser.

### What do you see instead?

One cookie.

<img width="1261" alt="image" src="https://github.com/oven-sh/bun/assets/868217/022ad45d-298e-4f2b-bae5-38662400122e">

**Comment by aloker** [comment]
I'm running into the same issue. It's probably due to the fact that bun tries to combine both cookies into one set-cookie header whereas under node, two set-cookie headers (one for each cookie) are sent.

In my case:

bun:
![image](https://github.com/oven-sh/bun/assets/140714/a01e3587-b314-4030-b74b-bdc2fb91f6de)

node:
![image](https://github.com/oven-sh/bun/assets/140714/3565aa68-05ea-4667-84e6-0ee8ac9e00fa)

**Comment by Electroid** [comment]
Thanks for debugging this, indeed looks like an issue with our `node:http` handling of `Set-Cookie`.

**Comment by bnt-razvanraspop** [comment]
so please fix this headers should be `[string,string][]`  and not `{[key: string]: string}`

**Comment by razvyrazvy41** [comment]
so please fix this headers should be `[string,string][]` and not `{[key: string]: string}`

**Comment by Electroid** [comment]
> so please fix this headers should be `[string,string][]` and not `{[key: string]: string}`

@razvyrazvy41 Mind opening an issue with some code so we can reproduce?
