### ISSUE TITLE
ReferenceError: Can't find variable: __dirname

### ISSUE THREAD

**Issue by KryptXBSA** [oven-sh/bun#4301]
### What version of Bun is running?

0.8.0

### What platform is your computer?

Linux 6.2.6-76060206-generic x86_64 x86_64

## Issue Description:

I'm getting a `ReferenceError for __dirname` when using Prisma after bundling the code with:
`bun build ./src/index.ts --outdir ./out --target bun`
`bun ./out/index.js` results in a ReferenceError for `__dirname`.
The issue still occurs if i change --target to node.

Full error:
```
ReferenceError: Can't find variable: __dirname
      at /home/aland/sandbox/bun-prisma-issue/out/index.js:1606:69
```
## Steps to Reproduce:

1. Clone the repository.
[https://github.com/AlandSleman/bun-prisma-issue](https://github.com/AlandSleman/bun-prisma-issue)
2. Install dependencies, and generate Prisma client.
`bun install && bun run prisma:generate`
3. Build using `bun build ./src/index.ts --outdir ./out --target bun`.
`bun run build`
4. Run the bundled code with `bun ./out/index.js`.
`bun start`

**Comment by codehz** [comment]
__dirname is unavailable on esm environment, it is same as node.js
you can use
```
const __filename = import.meta.path;
const __dirname = import.meta.dir;
```

**Comment by KryptXBSA** [comment]
> __dirname is unavailable on esm environment, it is same as node.js you can use
> 
> ```
> const __filename = import.meta.path;
> const __dirname = import.meta.dir;
> ```

Do i have to manually add that in the compiled index.js?
I did that and replaced `"__dirname"` at line 1608 to the __dirname variable as you mentioned, but now I'm getting this error:
```
1608 |     let binaryTarget = await lt(), searchedLocations = [], dirname = (0, eval)(__dirname), searchLocations = [config.dirname, Yt.default.resolve(dirname, ".."), co
nfig.generator?.output?.value ?? dirname, Yt.default.resolve(dirname, "../../../.prisma/client"), "/tmp/prisma-engines", config.cwd];
                                                                        ^
SyntaxError: Invalid regular expression: invalid flags
```

**Comment by KryptXBSA** [comment]
The issue seems to be that prisma can't find the binaryTarget. I've tried adding the `output` option to the generator as specified [in here](https://www.prisma.io/docs/concepts/components/prisma-schema/generators).
```
generator client {
  provider      = "prisma-client-js"
  output        = "./generated/prisma-client-js"
  binaryTargets = ["linux-musl"]
}
```
But still I'm getting the same error:
```
1608 |     let binaryTarget = await lt(), searchedLocations = [], dirname = (0, eval)(__dirname), searchLocations = [config.dirname, Yt.default.resolve(dirname, ".."), co
nfig.generator?.output?.value ?? dirname, Yt.default.resolve(dirname, "./generated/prisma-client-js/index.js"), "/tmp/prisma-engines", config.cwd];
                                                                        ^
SyntaxError: Invalid regular expression: invalid flags
```

**Comment by KryptXBSA** [comment]
Also on line 2602 `__dirname` and `__filename` are actually defined. I think there may be some bug regarding the bundling process which produces these issues.
```
  var __dirname = "/home/aland/sandbox/bun-prisma-issue/node_modules/@prisma/client/runtime", __filename = "/home/aland/sandbox/bun-prisma-issue/node_modules/@prisma/client/runtime/library.js";

```

**Comment by infrahead** [comment]
@AlandSleman perhaps the same issue I recently filed #4216

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/4216

**Comment by SijmenHuizenga** [comment]
I guess the `eval` is the problem here. `__dirname` is being replaced in other places, but i guess bun doesn't parse the things inside `eval`?

https://github.com/prisma/prisma/blob/dc54aedf77a368c83479a42aca46b250e15e796f/packages/internals/src/resolveBinary.ts#L80-L82

**Comment by chen-rn** [comment]
Although duplicate of #4216, this is the only post that shows up when searching the full error that shows up in github issues.

Seems like the issue is what @SijmenHuizenga describes as I'm running into this with a project that contains Prisma.

The good thing is, with Bun, there are no major downsides of directly running the source file in production aside from minor start up time. And I don't run into this issue when directly running my .ts file.

Bun docs mention that [in many cases, it isn't necessary to bundle server-side code; you can directly execute the source code without modification. However, bundling your server code can reduce startup times and improve running performance.](https://bun.sh/docs/bundler#NDGSKAILse:~:text=In%20many%20cases%2C%20it%20isn%27t%20necessary%20to%20bundle%20server%2Dside%20code%3B%20you%20can%20directly%20execute%20the%20source%20code%20without%20modification.)

I do wonder how big those start up times and performance differences are. Likely won't make a difference in my project, but maybe in a serverless environment it can be noticeable?

**Comment by Electroid** [comment]
Duplicate of #5094
