### ISSUE TITLE
Unnecessary comment at the napi.zig file

### ISSUE THREAD

**Issue by jonatasemidio** [oven-sh/bun#431]
I know that for some, this kind o issue is not exactly an issue, but for the sake of one cleaning house, it would be nice to have, instead of commented code, an open issue or a doc explaining the situation.

I think we can start here a conversation about different approaches to deal with that commented code.

What do you think?

https://github.com/Jarred-Sumner/bun/blob/b64c71eece7572749044ce1f4e5f1bf4c384be29/src/napi/napi.zig#L245

**Comment by Jarred-Sumner** [comment]
You'll find a lot of these right now. 

For example, there are still many comments in bun's JS AST actually copy pasted from esbuild because bun's JS parser was initially a port of esbuild's JS parser to zig

I did not spend time cleaning the code before making bun public (would be an easy way to create more bugs) 

If you're wondering what's going on in this particular case, I was originally going to implement NAPI completely in Zig. Then, I thought about it more, and realized it'd be slower and more difficult to do well because it needs very specific JSC bindings. So about half of the code for NAPI lives in napi.zig and the other half lives in napi.cpp

You're welcome to submit a PR that deletes the comment

**Comment by jonatasemidio** [comment]
I would like to delete some comments, but just to understand a bit more.

Do we still have different types of comments like: code that was commented in a hurry but is not needed anymore, blocks that is not working properly and needs to be analyzed in deep, last logic commented due to new code that should be tested (considering moving back to the old logic in case of problems), etc 

I'm just saying that because, It is possible create category of clean-up instead of just cleaning per file found (unless the second option is the intended one)

**Comment by jonatasemidio** [comment]
I will close this Issue considering that a PR was already opened
https://github.com/Jarred-Sumner/bun/pull/435/files
