### ISSUE TITLE
SvelteKit freezes on dev mode with the --bun flag when using specific dependencies

### ISSUE THREAD

**Issue by joaocstro** [oven-sh/bun#4371]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

- Create a SvelteKit app using `bunx create-svelte my-app`;
- Install `"@tiptap/core": "^2.1.7"` as a dependency;
- Run `bun --bun run dev`.

### What is the expected behavior?

After running `bun --bun run dev` and opening the app on localhost, it should load normally.

### What do you see instead?

The application does not load, and my terminal session becomes unresponsive.

### Additional information

This happens after just installing the dependency, even if you don't import anything from it. Both `bun --bun run build` and `bun --bun run preview` work as expected. This problem does not seem happen with other dependencies like `"popmotion": "^11.0.5"`.

**Comment by birkskyum** [comment]
Does this freeze with '@tiptap/core' reproduce outside of sveltekit, i.e. with 'bun create react my-react-app'?

**Comment by joaocstro** [comment]
Just did some quick tests and couldn't reproduce it with React or Astro.

**Comment by birkskyum** [comment]
I find that sveltekit sometimes freezes even before adding this dependency, just with:

`bunx create-svelte my-app`
`bun i`
`bun --bun run dev`

It would seem like this might not be related to this dependency after all, but rather that SvelteKit with bun seem to freeze often

I did manage to install this dependency and run the sveltekit demo app, but it's flaky as before installing it

**Comment by joaocstro** [comment]
This seems to be related to the `"@neoconfetti/svelte": "^1.0.0"` dependency that is used in the `sverdle` route. The freeze happens just after trying to load this route for the first time, and things seem to work normally after restarting the dev server. Just tested removing this dependency and its uses before running `bun i`, and the app worked as expected.

**Comment by cdmistman** [comment]
i'll note here that there's currently an issue with running `svelte-add` due to [unexpected async behavior](https://github.com/oven-sh/bun/issues/4343#issue-1867855660), and you need to [pass `--package-manager bun` to `svelte-add`](https://github.com/egoist/detect-package-manager/pull/10)

**Comment by defnorep** [comment]
I've done a little investigating on this issue and want to ensure I'm reproducing the right thing.

All of the following issues only occur when passing `--bun` to `bun`. My environment is WSL2 with Ubuntu 22.

When running `bun --bun run dev`, the build completes and the correct output is displayed to the terminal. Opening the app in a browser works, and I can interact with the dev server keybindings.

This behaviour occurs with or without `@tiptap/core`, and I tested all of the below findings with and without that dependency.

After interrupting with Ctrl + C, I get an exit error and my terminal stops accepting input. It looks like it has hanged. The same thing happens when I interact with the dev server keybind for restart.

I determined that it's possible to pass commands to the terminal even though it appears frozen. If I type `reset` or `stty sane` and hit enter, the terminal is returned to me.

I performed the same tests on my Macbook. When interrupting the dev server, I do gain control back on normal terminal input, but when I tried to clear terminal input with Ctrl + C, I got a bell alert from ITerm and my input didn't clear. This specific behaviour does not happen when I call `bun run dev`, so maybe terminal modes are only partially returned on MacOS and could be different depending on the terminal application being used.

There are some complex control flows around child processes and signals in `bunx_command.zig` and `run_command.zig`. I will spend some time trying to break things further there.

@joaocstro you described the problem as the application not loading at all and your terminal becoming unresponsive. I don't get that specific behaviour but have found the above problems. If you have some time maybe you could provide some screenshots, or try resetting your terminal as described above to help me understand if I've reproduced the right thing or not.
