### ISSUE TITLE
Build system don't depends on system toolchain

### ISSUE THREAD

**Issue by CGQAQ** [oven-sh/bun#4381]
### What is the problem this feature would solve?

As we are going to support Windows, the build system we have now (Gnu make) doesn't play well with Windows at all, so we should migrate to let Zig take care of the whole building process.

### What is the feature you are proposing to solve the problem?

I think it could be done in several steps:
1. We could switch over from clang to `zig cc`, `zig c++` respectively
2. Switch from `GNU Make` to `The zig build system`
3. Maybe take advantage of `zig package management system` to pull the deps from the Github instead of git submodules? not sure

### What alternatives have you considered?

Cmake could be another option as the build system to support cross-platform, Windows support is just there. But I personally don't like it

P.S.: I'm going to spend some time figuring out how to do this, but I'm not sure if I could get this work.

**Comment by CGQAQ** [comment]
# Blocking issues
- [ ] https://github.com/ziglang/zig/issues/17008

**Comment by Jarred-Sumner** [comment]
I don't think we can realistically depend on`zig build`. 
- `zig build` has breaking changes ~monthly. Not worth effort spent keeping up to date.
- It doesn't parallelize C/C++ files as efficiently as ninja or `make -j`
- It is too opinioniated about linker & compiler flags. We need control over all the flags
- We will need to use MSVC for the Windows build in order to support WebKit (which uses MSVC and does not officially support ClangCL or msys2)

The main reason really though is the instability. 

I agree though that the Makefile is hideously complicated. We should probably use Bazel.

**Comment by CGQAQ** [comment]
I'll try to compile `jsc` with `zig c++` and see if it works on Windows later today. I think you are right, `the zig build system` right now is not very API-stable and may change at any time. we could switch to zig cc with Bazel if `zig c++` can actually compiles `jsc` and decides whether or not switch to `zig build system` after `zig 1.0 milestone`

If we do get `jsc` compile, we could get:
1. Cross-compile with one flag
2. Take advantage of `zig cache system` so we don't need `ccache` anymore
3. Don't depends on the system toolchain and linking statically so we can run bun anywhere
4. Zig is doing some very interesting experiments right now, `rewrite libc in zig` for example, we can get those for free
5. By only depending on zig, Bun will be easier to compile and contributor friendly
6. Don't need to upgrade llvm after upgrade zig version (zig uses libclang to emit binary, so technically we need to sync llvm version with libclang inside the zig as we linking those object files together)

**Comment by Electroid** [comment]
We are in the process of revamping our build system to use cmake and ninja. It's unlikely we'll use Zig's build anytime soon.
