### ISSUE TITLE
Segmentation fault when importing declaring a function using jose's jwtVerify

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#4388]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```
import { jwtVerify } from "jose";
// declare a function that uses it
async function verifyFirebaseToken(token: string) {
  const decodedToken = await jwtVerify(
        token,
        async (header, _alg) => {
            const x509Cert = publicKeys[header.kid!];
            const publicKey = await importX509(x509Cert, "RS256");
            return publicKey;
        },
        {
            issuer: `https://securetoken.google.com/${firebaseProjectId}`,
            audience: firebaseProjectId,
            algorithms: ["RS256"],
        }
    );
}
```

### What do you see instead?

Segmentation fault

### Additional information

it's working fine in bun 0.7.2

**Comment by Jarred-Sumner** [comment]
Going to need some more information here to reproduce the crash

The following example code from `jose` does not reproduce it:

```ts
import * as jose from "jose";
const secret = new TextEncoder().encode(
  "cc7e0d44fd473002f1c42167459001140ec6389b7353f8088f4d9a95f2f596f2"
);
const jwt =
  "eyJhbGciOiJIUzI1NiJ9.eyJ1cm46ZXhhbXBsZTpjbGFpbSI6dHJ1ZSwiaWF0IjoxNjY5MDU2MjMxLCJpc3MiOiJ1cm46ZXhhbXBsZTppc3N1ZXIiLCJhdWQiOiJ1cm46ZXhhbXBsZTphdWRpZW5jZSJ9.C4iSlLfAUMBq--wnC6VqD9gEOhwpRZpoRarE0m7KEnI";

const { payload, protectedHeader } = await jose.jwtVerify(jwt, secret, {
  issuer: "urn:example:issuer",
  audience: "urn:example:audience",
});

console.log(protectedHeader);
console.log(payload);
```

Are you sure that the crash is caused by the code in there? Often the cause of GC/memory issues is somewhere before it happens, rather than where it crashes

Here are two things you can do to narrow it down more:
- Sprinkle `Bun.gc(true)` in a lot of places. The earliest place it crashes is closest to the cause. Like "hot or cold"
- `bun --smol` runs the GC more often so it might crash earlier/closer to the cause

**Comment by Electroid** [comment]
If you are able to provide some more information to reproduce this, let us know and we'll re-investigate.
