### ISSUE TITLE
SpyOn doesn't work on ESM namespace object properties

### ISSUE THREAD

**Issue by coratgerl** [oven-sh/bun#4482]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

The spyOn of bun test doesn't work when the function is import from a different file of the test file. Like the example below:

**Test file :** 
```javascript
import { describe, expect, it, spyOn } from 'bun:test'
import * as fileA from './fileA'

describe('fileB', () => {
	it('should spy the say toto in file A', async () => {
		const spySayToto = spyOn(fileA, 'sayToto')

		fileA.sayToto()

                // This test failed and have 0 as value
		expect(spySayToto).toHaveBeenCalledTimes(1)
	})
})
```

**File A with function to spy:**
```javascript
export const sayToto = () => {
	console.log('toto')
}
```

### What is the expected behavior?

The function have been called 1 times and not zero.

**Comment by winghouchan** [comment]
I've found a workaround by assigning the imported function to an object created in the test file:

**`index.ts`**

```
export function fn() { ... }
```

**`index.test.ts`**

```
import { expect, spyOn, test } from "bun:test";
import { fn } from "./index";

test("spied fn is called", () => {
  const obj = { fn };
  const spy = spyOn(obj, "fn");

  obj.fn();

  expect(spy).toHaveBeenCalledTimes(1);
});
```

**Comment by winghouchan** [comment]
I've taken a few steps to look at this but I'm not familiar with C++ so I probably won't get anywhere. Documenting what I find anyway in case it'll be useful. So far:

1. Created a test case for this scenario (d1d80da7fcd783fc150df04f2efa2b72b0a50e89). The case itself is just a copy of [this test case](https://github.com/oven-sh/bun/blob/687e31dc3a16e76926f0eb06155c5357741b05ab/test/js/bun/test/mock-fn.test.js#L493-L515) but just uses a function imported from a fixture file. It fails as expected.
2. Suspect the problem is somewhere here: https://github.com/oven-sh/bun/blob/687e31dc3a16e76926f0eb06155c5357741b05ab/src/bun.js/bindings/JSMockFunction.cpp#L570-L659

**Comment by coratgerl** [comment]
Yes I also look the issue few days ago, I think the problem is that the function is not in the globalContext because it's is in a different file. We need to find the right globalContext I think but I am not an expert on JavascriptCore so I am not sure about this.

**Comment by Jarred-Sumner** [comment]
This happens because the ES Module namespace object symbol table needs to be mutated to update the binding for the ESM export to the new wrapped value
