### ISSUE TITLE
error: Cannot find module "" from "..." and redefining require variable

### ISSUE THREAD

**Issue by matteopolak** [oven-sh/bun#453]
The package `tiny-typed-emitter` has nothing special about it, it was just the package causing the error when I was attempting to use the package `@discordjs/voice`.

Declaring a variable `require` results in a collision:

`test.mjs`
```js
import { createRequire as topLevelCreateRequire } from 'module';
import { TypedEmitter as TypedEmitter7 } from 'tiny-typed-emitter';

const require = topLevelCreateRequire(import.meta.url);
```

`bun test.mjs`
```
1 | var { createRequire: topLevelCreateRequire } = import.meta.require("node:module");
   ^
 ReferenceError: Cannot access uninitialized variable.
      at /root/binky/test.mjs:1:0
```

And switching around a few lines...
```js
import { createRequire as topLevelCreateRequire } from 'module';

const require = topLevelCreateRequire(import.meta.url);

import { TypedEmitter as TypedEmitter7 } from 'tiny-typed-emitter';
```

`bun test.mjs`
```
error: Cannot find module "" from "file:///root/binky/test.mjs"
```

Replacing the import statement of `tiny-typed-emitter` with `require('tiny-typed-emitter')` yields the error
```
error: Cannot find package "tiny-typed-emitter" from "file:///root/binky/test.mjs"
```

Which is strange, as if I `require`/`import` `tiny-typed-emitter` by itself it works correctly?
The package `tiny-typed-emitter` is located in my `node_modules` folder which is in the same directory as `test.mjs`.

Bun version: 0.1.2

**Comment by bluwy** [comment]
From what I can tell, when `require` is found, it internally inteprets as CJS (not 100% sure), and doesn't hoist imports. You can think of `import 'tiny-typed-emitter';` being `require('tiny-typed-emitter')` but because `const require` is defined later you get the first error.

For the second error, `createRequire` with strings doesn't work correctly. `createRequire(new URL(import.meta.url))` worked for me instead.
