### ISSUE TITLE
How to start bun repl with a file

### ISSUE THREAD

**Issue by pannous** [oven-sh/bun#4706]
### What is the type of issue?

Documentation is confusing

### What is the issue?

Even with bun repl --help and  bun repl > .help I couldn't work out how to start bun repl with a file.

**Comment by typescriptlover** [comment]
I know in Node.js you can .load a script file in the repl, but I don't think it's supported in bun yet.

The only way to be able to access it inside the repl is if you import it or require it, but then you'd have to export everything so u can access it inside the repl.

**Comment by jhmaster2000** [comment]
Indeed, its just not supported yet, but will be in the future (planned), marking this as a feature request.

**Comment by jhmaster2000** [comment]
REPL version 2.1.1+ implements `.save` and `.load` like node repl has, although `.load` is marked as experimental due to suffering from limitations the repl itself already currently had, namely poor top-level await support, but most simple scripts should work. This will naturally improve as we repl's core transpiler and runtime logic is improved.

(When trying to use these features please ensure you really are on REPL 2.1.1+ with `.info`, if you are outdated or if `.info` is not a command, please see https://github.com/jhmaster2000/bun-repl/issues/7#issuecomment-1718643970)

**Comment by bgmort** [comment]
What's the status of this in 2024? I found `bun repl -e ./replstuff`, but that exits just like `bun -e ./replstuff`. I was expecting it to stay interactive like `node -r ./replstuff`.
