### ISSUE TITLE
Inconsistency Between bun install and npm install on some packages

### ISSUE THREAD

**Issue by tanerijun** [oven-sh/bun#4707]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Start a project using Bun, run `bun i argon2`, then check `node_modules/argon2`.
Start a project using NPM, run `npm i argon2`, then check `node_modules/argon2`.
Compare the results

### What is the expected behavior?

The content of `node_modules/argon2` is the same as when it's installed using both Bun and NPM

### What do you see instead?

The content some dependencies is different when installed with Bun and NPM. 

For example, the package `argon2`. When installed using `bun i`,  the file `node_modules/argon2/lib/binding/napi-v3/argon2.node` is not there, but it is installed correctly by `npm i`.

### Additional information

Other than `argon2`, `better-sqlite3` seems to have the same issue (saw a similar error, but haven't tested it myself)

**Comment by tanerijun** [comment]
It works as expected if the dependencies is added to trustedDependencies as per the instructions [here](https://bun.sh/docs/cli/install#trusted-dependencies). But is really the intended behavior?

**Comment by tvarwig** [comment]
I found this issue after having the same issue myself. Docs make sense. `argon2` looks to have a `postInstall` and runs a python script and there is some c++ in there too. I agree with the statement on the docs that "These scripts represent a potential security risk". Since `argon2` is maintained looks to be a good reason to have it under `trustedDependencies`. You don't want to have some bad package to run arbitrary code in python or any binary on your computer. I believe that bun is doing good in this. npm, yarn and pnpm should follow this.

Take a look at the [OWASP NPM Security Cheat Sheet - Minimize attack surfaces by ignoring run-scripts](https://cheatsheetseries.owasp.org/cheatsheets/NPM_Security_Cheat_Sheet.html#3-minimize-attack-surfaces-by-ignoring-run-scripts)

**Comment by tanerijun** [comment]
Yeah, it's great in retrospect. One suggestion for bun is to show a message in CLI when postinstall is not run, and suggest user to put the dependency in `trustedDependencies` if they're sure. Otherwise, some people might think it's bug on bun's side

**Comment by Electroid** [comment]
We recently fixed some issues where `bun install` would download a slightly different version of packages. Try running `bun upgrade --canary` and retrying. If you still experience this issue, let us know and we'll re-investigate.

For `argon2` specifically, that will depend on: https://github.com/oven-sh/bun/issues/4959
