### ISSUE TITLE
The `bun create` with a local template doesn't work.

### ISSUE THREAD

**Issue by yskszk63** [oven-sh/bun#4767]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Run `bun create` with a local template.

### What is the expected behavior?

A project is created from a local template.

### What do you see instead?

```bash
$ cat /tmp/tmp.XpmD9AznVC/package.json
{ "name": "tmp.XpmD9AznVC" }
$ bun create /tmp/tmp.XpmD9AznVC
Fetching package.json... 

error: "/tmp/tmp.XpmD9AznVC" was not found. Here are templates you can use:

  bun create apollo-server tmp.XpmD9AznVC

  bun create bun-bakery tmp.XpmD9AznVC

  bun create discord-interactions tmp.XpmD9AznVC

  bun create elysia tmp.XpmD9AznVC

  bun create elysia-buchta tmp.XpmD9AznVC

  bun create hono tmp.XpmD9AznVC

  bun create kingworld tmp.XpmD9AznVC

  bun create react tmp.XpmD9AznVC

  bun create react-ssr tmp.XpmD9AznVC

  bun create stric tmp.XpmD9AznVC

  bun create svelte-kit tmp.XpmD9AznVC

  bun create websi tmp.XpmD9AznVC

$
```

**Comment by KalZyyrk** [comment]
i have the same problem
i try with the the directory .bun-create and the environment variable BUN_CREATE_DIR
with the path, nothing work

**Comment by hassanallaham** [comment]
i have the same problem:
### What version of Bun is running?
```
$ bun -v
1.0.1
```

### What platform is your computer?
Ubuntu 20.04.6 LTS 64-bit

### What steps can reproduce the bug?
I have the needed path $HOME/.bun-create in my file system and there is a template created according to the docs:
```
$ cat $HOME/.bun-create/my-bun-template/package.json
{
    "name": "my-bun-template",
    "version": "0.0.1",
    "main": "index.js",
    "dependencies": {
        "cross-env": "*",
        "express": "*",
        "morgan": "*"
    },
    "bun-create": {
        "preinstall": "echo 'Installing...'",
        "postinstall": [
            "echo 'Done!'",
            "echo 'Go ahead'"
        ],
        "start": "bun run echo 'Hello world!'"
    }
}

```
I have the needed env variable:
```
$ env | grep "BUN_CREATE_DIR"
BUN_CREATE_DIR=/home/user/.bun-create
```

Run bun create with a local template:
```
$  bun create my-bun-template bbb
  🔍 create-my-bun-template [1/1] 
error: package "create-my-bun-template" not found registry.npmjs.org/create-my-bun-template 404
```

and if I try:
```
$  bun create /my-bun-template bbb
error: "/my-bun-template" was not found. Here are templates you can use:

  bun create apollo-server bbb

  bun create bun-bakery bbb

  bun create discord-interactions bbb

  bun create elysia bbb

  bun create elysia-buchta bbb

  bun create hono bbb

  bun create kingworld bbb

  bun create react bbb

  bun create react-ssr bbb

  bun create stric bbb

  bun create svelte-kit bbb

  bun create websi bbb

  bun create my-bun-template bbb

  bun create my-bun-template bbb

```
What is the expected behavior?
A project is created from a local template.

What do you see instead?
1- in case:
```
$  bun create my-bun-template bbb
  🔍 create-my-bun-template [1/1] 
error: package "create-my-bun-template" not found registry.npmjs.org/create-my-bun-template 404

```
Which means bun was trying to get the template from **npm registry** and not from .bun-create directory 

2- in case:
```
$  bun create /my-bun-template bbb
error: "/my-bun-template" was not found. Here are templates you can use:

  bun create apollo-server bbb

  bun create bun-bakery bbb

  bun create discord-interactions bbb

  bun create elysia bbb

  bun create elysia-buchta bbb

  bun create hono bbb

  bun create kingworld bbb

  bun create react bbb

  bun create react-ssr bbb

  bun create stric bbb

  bun create svelte-kit bbb

  bun create websi bbb

  bun create my-bun-template bbb

  bun create my-bun-template bbb
```
  
Which means: In this case, Bun was able to find the template folder (although it is strange output because it mentioned it two times as seen above in the last two lines of the output) but when it was trying to copy the template folder it expected the folder name "/my-bun-template" (with forward slash) as seen in the error line above

**Comment by Lsnsh** [comment]
Use the `./` prefix indicates the use of a local template, like `bun create ./foo bun-foo`:

```bash
➜  playground bun create ./foo bun-foo

$ /opt/homebrew/Cellar/bun/1.0.2/bin/bun run echo 'Installing...'
[package.json] Detected React - added "react-refresh"
'Installing...'

$ bun install
bun install v1.0.2 (37edd5a6)
  🔍 Resolving [1/2]
[44.00ms] git
 + react-refresh@0.10.0
 + react@17.0.2
 + react-dom@17.0.2

 7 packages installed [1.99s]

[1.99s] bun install


$ /opt/homebrew/Cellar/bun/1.0.2/bin/bun run echo 'Done!'
'Done!'

[2.04s] bun create /Users/lsnsh/.bun-create/foo

Come hang out in bun's Discord: https://bun.sh/discord

-----

A local git repository was created for you and dependencies were installed automatically.

Created foo project successfully

# To get started, run:

  cd bun-foo
  bun run echo 'Hello world!'

➜  playground cd bun-foo
➜  bun-foo git:(main) ✗ bun run index.js
Hello World!
```


And need necessary to ensure that the JSON format of the `package.json` file is correct, otherwise the hook will not work properly and will eventually return a blank `package.json` file.

bad ❌:

```json
{
  "name": "foo",
  "version": "0.0.1",
  "main": "index.js",
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "bun-create": {
    "preinstall": "echo 'Installing...'", // a single command
    "postinstall": ["echo 'Done!'"], // an array of commands
    "start": "bun run echo 'Hello world!'"
  }
}
```

good ✅:

```json
{
  "name": "foo",
  "version": "0.0.1",
  "main": "index.js",
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "bun-create": {
    "preinstall": "echo 'Installing...'",
    "postinstall": ["echo 'Done!'"],
    "start": "bun run echo 'Hello world!'"
  }
}
```

---

Another point to note:

> ⚠️ Warning — Unlike remote templates, running bun create with a local template will delete the entire destination folder if it already exists! Be careful.

---

This is the conclusion I have reached after about two hours of trying, and I hope it will be helpful.

The [official documents](https://bun.sh/docs/templates#from-a-local-template) and error prompts need further improvement.

**Comment by pierre-cm** [comment]
I believe this issue was introduced [here](https://github.com/oven-sh/bun/pull/4468/files#diff-0213d803b050248119f629ea8f3e9dc3a9dd5fc1c78cd3176ccdabebb6a1b4e7R1457-R1473).

While I don't understand the full motivation behind the use of bunx in the create command, it appears the problem arises because the new [use_bunx](https://github.com/oven-sh/bun/blob/f297b95436b49573cdb6caf21debf4f765e90b43/src/cli.zig#L1541) constant does not account for local folders scenarios (should be false in that case).

> @Lsnsh 
> Use the `./` prefix indicates the use of a local template, like `bun create ./foo bun-foo`:

This workaround works only because we introduce `/` in the template name, setting use_bunx constant to false.

I may attempt to provide a fix soon.
