### ISSUE TITLE
`bun create` to be compatible with `npm create`

### ISSUE THREAD

**Issue by gi-dellav** [oven-sh/bun#485]
The feature that I'm proposing is the support for `bun create` to create project using NPM packages.

For example, with npm this `npm create vite@latest` can be used to create a project using the latest version of vite, while bun doesn't support npm for his `create` command.

I realize that this project is still in its infancy, but I wanted to say to every developer of the project that your work is truly amazing.

**Comment by birkskyum** [comment]
`npm create` is a simple alias for `npx create-`, so if you write `npx create-vite@latest` it's the same - and that you can do with bun already:

`bun x create-vite@latest`, or for now to make sure you use bun `bun --bun x create-vite@latest`

  `bun create` is not a simple alias like that, and does it's on thing entirely... would arguably be a lot less confusion if it was a simple alias in the same way that npm is, and that the current `bun create` is renamed to something else that isn't overloaded like `bun generate` or `new`, `make`, `example`, `begin`. Since the files comes from the `examples` folder, maybe `example` is the most obvious.
  
  @Jarred-Sumner , if the aim is npm compat, maybe this is worth considering before the 1.0 locks down the APIs. Many many docs use the `npm create` shorthand, and therefore people will try to run `bun create` and get unexpected outcome
  
Alternatively, a new create script for these examples could be made on par with all the other ones, so that it would be executed with `bun x create-bun-example`, and due to the alias it would then be `bun create bun-example`, and then select i.e. react in the cli.
