### ISSUE TITLE
create react app error

### ISSUE THREAD

**Issue by same-101** [oven-sh/bun#4864]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.15.117-19680-g54e910f94133 x86_64 unknown

### What steps can reproduce the bug?

no code snippet

### What is the expected behavior?

```
<emoji> <text> <prog>
```

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/117522827/82d0b0f4-220c-4bd7-a752-b868624b868c)

### Additional information

no thats it

**Comment by AndreaZero** [comment]
You should use
` bun create vite@latest [your-app-name]`
 instead of 
`bun create react-app [your-app-name]`

**Comment by TreeOfLearning** [comment]
> You should use ` bun create react [your-app-name]` instead of `bun create react-app [your-app-name]`

See #4762 and #4646

**Comment by same-101** [comment]
> You should use ` bun create vite@latest [your-app-name]` instead of `bun create react-app [your-app-name]`

but vite gets unresponsive when you choose react

**Comment by colinhacks** [comment]
Apologies for the confusion

TLDR: `bun create react` is not longer a valid command. We recommend using `bun create vite` or `bun create react-app` instead.

Previously, bun create used an internal list of sample projects that we maintained. We've since switched it to match npm and others, so `bun create <template>` equivalent to running `bunx create-<template>`. Since there's no `create-react` package on npm, the command fails.

If you run `npm create react` or `yarn create react` you'll see the same error.

## No longer valid

```sh
$ bun create react
```

### Use this instead

```sh
$ bun create vite
$ bun create react-app
```

**Comment by same-101** [comment]
# NOTE
nevermind I installed Node.js and it worked
