### ISSUE TITLE
Repl errors on `import.meta.resolve` and `require.resolve`

### ISSUE THREAD

**Issue by AaronFriel** [oven-sh/bun#4866]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Executing the Bun repl to resolve an import to a path via `require.resolve`:

```
$ bun repl -e "console.log(require.resolve('./index.ts'))"
TypeError: require.resolve is not a function. (In 'require.resolve('./index.ts')', 'require.resolve' is undefined)
```

Or `import.meta.resolveSync` per [Bun docs on import.meta](https://bun.sh/docs/api/import-meta):

```
$ bun repl -e "import.meta.resolveSync('index.ts');"
SyntaxError: import.meta is only valid inside modules.
```

### What is the expected behavior?

The Node CLI behaves like so:

```
$ node -e "console.log(require.resolve('./index.ts'))"
/tmp/tmp.Eax10ed4vY/index.ts
```

### What do you see instead?

An error.

### Additional information

This is a useful tool for non-JavaScript tools to locate an import path, to run a script in Node or Bun. For example, Pulumi locates the `@pulumi/pulumi/cmd/run` script in this manner:

https://github.com/pulumi/pulumi/blob/d44f3fd7635ed1572c933a5a2a3b2a9c6ca97ae8/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L155-L164

**Comment by v3nntrnx** [comment]
cc @jhmaster2000

**Comment by jhmaster2000** [comment]
`import.meta` is expected, it does not work in nodejs repl either.

`require.resolve` is a good catch, `require()` is polyfilled into the repl in order to work in its context and I forgot to copy its properties over, will be fixed by tomorrow.

**Comment by AaronFriel** [comment]
I'd expect import.meta to work if import works - not sure if it does, but given the promise of Bun working in a mode agnostic to ESM or CommonJS, shouldn't both work?

I believe with the right flags `import.meta.resolve` should work in the Node repl or `node -e` which executes a script passed as an argument.

**Comment by jhmaster2000** [comment]
It's not about `import.meta.resolve`, but rather `import.meta` itself, it's not a "meta" property on an `import` object as many people are misled by the fancy syntax into believing, `import` is a keyword, not an object, `import.meta` therefore is also a singular magic keyword identifier referring to an object with a value that is resolved by semantics relative to the file the token is used inside. Since REPLs are not files, there is no semantics rule for them to have `import.meta` itself.

For reference see [`import.meta` on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta)

There is no flag in Node.js to have `import.meta` work in their REPL, only to add `resolve` to `import.meta` in places where `import.meta` already works.

**Comment by AaronFriel** [comment]
@jhmaster2000 Thanks, that's interesting background, I wasn't aware of the implementation details behind `import.meta`.

Taking a step back though; I'd expect that if this works in Node (v20.5.1):

```
$  node --experimental-import-meta-resolve --input-type=module -e "console.log(import.meta.resolve('./index.js'))";
file:///home/friel/index.js
```

And Bun advertises:

> No more module madness
>
> Forget the complicated rules around CommonJS, ESM, file extensions, resolution priority, and `package.json` configurations. With Bun, it just works.

Then I think it's consistent to expect that the same script should work in Bun as in Node, and ideally without `--input-type=module` or other experimental flags.

**Comment by Jarred-Sumner** [comment]
`import.meta` should work in the repl. We expose useful functionality on there. It is a bug that it does not work. It should not need flags either.

The current implementation of the repl is very hacky. It's just `bunx bun-repl` and `bun-repl` isn't exactly part of bun currently. Please don't consider it to be representative of the stability of Bun overall. We added this alias last-minute before 1.0

**Comment by jhmaster2000** [comment]
@AaronFriel Both `require.resolve` and `import.meta` are now supported in the REPL with a little transpiler magic.

Unfortunately `await import.meta.resolve(...)` is not yet usable due to bad interaction between the `import.meta` transpiler magic and the only partial top-level await support, but `import.meta.resolveSync(...)` can be used instead.

Let me know here if you encounter any issues using these then we can re-open the issue if so.
