### ISSUE TITLE
BigInt prints as undefined at REPL

### ISSUE THREAD

**Issue by andyferris** [oven-sh/bun#4872]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.15.0-83-generic x86_64 x86_64

### What steps can reproduce the bug?

Typing a bigint, or any expression resulting in a bigint, at the REPL results in the value `undefined` at the REPL. 

Here's me playing around (literally a copy of my first time using Bun, was wondering why the REPL doesn't show _any_ output for a while):

```
$ bun repl
Welcome to Bun v1.0.0
Type ".help" for more information.
> const x = 1n
undefined
> x
undefined
> console.log(x)
1n
undefined
> 1n
undefined
> 1
1
> "abc"
'abc'
> new Map()
Map(0) {}
```

### What is the expected behavior?

```
> 1n
1n
```

### What do you see instead?

```
> 1n
undefined
```

### Additional information

Thanks for Bun! I was excited to try it out and literally this was the first thing I typed at the REPL :)

**Comment by jhmaster2000** [comment]
This was caused by a weird regression bug in the underlying inspector API, that bug remains but a workaround for it has been implemented on the REPL so bigints should work again now. Thanks for the report!

(If you still encounter the issue please clear the directory at `bun pm cache` and try again)
