### ISSUE TITLE
Request to separate Bun into two components: Bun and Bun Package Manager

### ISSUE THREAD

**Issue by gbourant** [oven-sh/bun#4916]
### What is the problem this feature would solve?

The current implementation of Bun as a single executable file, serving as both a runtime and package manager, poses security and efficiency concerns. Users may want to use Bun solely as a package manager without the runtime environment, reducing the attack surface and improving safety.

### What is the feature you are proposing to solve the problem?

I propose separating Bun into two distinct components:

Bun Executable (Current State): This component remains as-is.

Bun Package Manager (npm like): A standalone version of the Bun package manager for users who only need package management capabilities without the runtime environment. This component allows users to perform package-related tasks (e.g., install, update, and publish packages) without any additional runtime functionality.

By separating Bun into these two components, users can tailor their Bun usage to their specific needs, enhancing security by reducing the attack surface and improving efficiency for different types of projects.

P.S. Also there can be a third option Bun Runtime without the package manager like the nodejs.

**Comment by Yonben** [comment]
I wrote a few answers to this but in the end, I'm really on the verge. I do believe in the benefits of separating concerns. However I feel _ideally_ Node would be all what Bun is at once. I believe a healthier Node would be a runtime, a test runner, and a package manager. Think Rust or Go (even though Rust Cargo is separated like you proposed).

Overall, I believe most of what Bun does is good, and would feel comfortable extracting the package manager, but not more than that. Just a random opinion ✨

**Comment by Pomax** [comment]
As something that might fit in here too, making `bun` be its own version manager so folks won't need the confusion we currently have with concurrent Node versions installed through wildly different processes would be fantastic. `bun use 1.1` instead of needing a third party tool definitely feels in line with the goal of being a drop in replacement for Node, but... better.

**Comment by theoparis** [comment]
I agree that making Bun more modular (possibly using the zig package manager) would be helpful, but I'm not sure how easy this would be considering that the zig code is all tied together (from what I've seen).

I don't see why this issue was downvoted, since it could still be a single executable if the package manager is a separate zig module.

**Comment by Jarred-Sumner** [comment]
We aren't going to do this
