### ISSUE TITLE
`manifest.json` returns 404 with `bun dev` in the react example

### ISSUE THREAD

**Issue by tom-sherman** [oven-sh/bun#494]
<img width="1253" alt="Shows the error in the chrome dev tools" src="https://user-images.githubusercontent.com/9257001/178107438-b666d1b5-7ea6-42d6-82f0-472d917ba2ef.png">

**Comment by scriptyvijay** [comment]
for now, you can just comment menifest.json file in index.html then it'll run perfectly without any issue.

**Comment by khajimatov** [comment]
I have the same issue. I created react project with `bun create react` on my WSL(Ubuntu 20.04), I got this message after `bun dev`:

![image](https://user-images.githubusercontent.com/62846961/179310276-d3347add-cb94-45b7-b628-f84dd424f274.png)

After doing some research, I think maybe the reason for this bug is in these lines of code(?) [[link](https://github.com/oven-sh/bun/blob/main/src/http/mime_type.zig)](https://github.com/oven-sh/bun/blob/main/src/http/mime_type.zig):

![image](https://user-images.githubusercontent.com/62846961/179311261-21a28896-67bb-4060-be5d-187909ab2c84.png)

In the second screenshot, I moved if conditions of "octet-stream" and "wasm" into `if (strings.eqlComptimeIgnoreLen(category_, "application")) {` block, because for example, "html", "css", "plain" they were placed in same if condition(`if (strings.eqlComptimeIgnoreLen(category_, "text")) {`).

![image](https://user-images.githubusercontent.com/62846961/179312445-d2fcd9b8-ac74-4cdc-ab81-8dce7a827ee5.png)

I don't know If I'm right or wrong, just wanted to suggest some solutions. Sorry If I'm wrong in my assumptions or getting out of topic.

**Comment by lirilant** [comment]
I moved all files but index.html away from React's public folder. And created manifest.webmanifest also.

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
