### ISSUE TITLE
Error in bcrypt: module bcrypt_lib.node not found

### ISSUE THREAD

**Issue by mostafaSalah12** [oven-sh/bun#4969]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

- Create a node app
- run `npm i bcrypt`  then run it with `bun app.js`
- you will get error  _**Cannot find module**_ even if run `bun install`
### What is the expected behavior?

the app should run without any errors

### What do you see instead?

error: Cannot find module "/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" from "/node_modules/bcrypt/bcrypt.js"

**Comment by gmanninglive** [comment]
Hey @mostafaSalah12 as much as it's not direct answer to your issue. Bun does expose bcrypt and argon apis via `Bun.password` see: https://bun.sh/guides/util/hash-a-password

I replicated your issue, and got past the `Cannot find module` error by taking these steps https://github.com/kelektiv/node.bcrypt.js/issues/800#issuecomment-628342935. However I then got a segmentation fault, which could be due to my platform.

**Comment by quinnturner** [comment]
bcrypt is a native module. While this is a guess, Bun might not build the native module. You may have to add it to the trusted dependencies list of modules https://bun.sh/docs/cli/install#trusted-dependencies

**Comment by mostafaSalah12** [comment]
> Hey @mostafaSalah12 as much as it's not direct answer to your issue. Bun does expose bcrypt and argon apis via `Bun.password` see: https://bun.sh/guides/util/hash-a-password
> 
> I replicated your issue, and got past the `Cannot find module` error by taking these steps [kelektiv/node.bcrypt.js#800 (comment)](https://github.com/kelektiv/node.bcrypt.js/issues/800#issuecomment-628342935). However I then got a segmentation fault, which could be due to my platform.

It solves my problem. Thanks.

**Comment by Electroid** [comment]
We need to fix support for bcrypt: #299
