### ISSUE TITLE
node:os availableParallelism() not implemented

### ISSUE THREAD

**Issue by yschroe** [oven-sh/bun#4986]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

The [`availableParallelism()`](https://nodejs.org/api/os.html#osavailableparallelism) method seems to be missing from the node:os module.

#### test.js
```javascript
import { availableParallelism } from 'node:os';

console.log(availableParallelism());
```

`node test.js` -> "8"

`bun test.js` -> "SyntaxError: Import named 'availableParallelism' not found in module 'os'."

I checked the [compatibility overview page ](https://bun.sh/docs/runtime/nodejs-apis) and node:os is marked as fully implemented, so I guess this is a bug.

### What is the expected behavior?

The function should return the available number of threads/parallelism of the system.

### What do you see instead?

SyntaxError: Import named 'availableParallelism' not found in module 'os'.

**Comment by jdmarshall** [comment]
I had some eyeballs on how this played out in Node.

Essentially the question is how many worker threads or cluster processes do I want to spin up for a task? That's proportional to how many CPUs are available, and that data can be incorrect in Docker, because cgroups doesn't really control what you can see in this regard. You know the host OS has 8 CPUs, you don't know how many of them are given over for your use. And this can be comically incorrect when using Docker Desktop, which doles out a mere fraction of the CPUs.

the unix command `nproc` typically gets the correct answer, and if you look around there's advice on SO that says this is the equivalent on OS X:

`sysctl -n hw.logicalcpu`

**Comment by WingLim** [comment]
Can I take and work on this?

**Comment by WingLim** [comment]
> I had some eyeballs on how this played out in Node.
> 
> Essentially the question is how many worker threads or cluster processes do I want to spin up for a task? That's proportional to how many CPUs are available, and that data can be incorrect in Docker, because cgroups doesn't really control what you can see in this regard. You know the host OS has 8 CPUs, you don't know how many of them are given over for your use. And this can be comically incorrect when using Docker Desktop, which doles out a mere fraction of the CPUs.
> 
> the unix command `nproc` typically gets the correct answer, and if you look around there's advice on SO that says this is the equivalent on OS X:
> 
> `sysctl -n hw.logicalcpu`

In nodejs, they use libuv's [uv_available_parallelism()](https://docs.libuv.org/en/v1.x/misc.html#c.uv_available_parallelism) to get the right data for different platform, I wonder if bun should use the same way or implement by ourselves?

**Comment by jdmarshall** [comment]
> On Linux, inspects the calling thread’s CPU affinity mask to determine if it has been pinned to specific CPUs.
>
> On Windows, the available parallelism may be underreported on systems with more than 64 logical CPUs.
>
> On other platforms, reports the number of CPUs that the operating system considers to be online.

My half-informed opinion is yes. And from a principle of least surprise standpoint, this may be a spot where being bug-compatible on 'other platforms' is disappointing but at least not a nasty surprise.
