### ISSUE TITLE
`length` property is missing in the object when printed with `console.log`

### ISSUE THREAD

**Issue by pokedotdev** [oven-sh/bun#5054]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

`console.log` does not print the `length` property in console when there is more than one property in the object.

```ts
// index.ts
console.log({
  length: 1,
  foo: "bar",
});
console.log({
  length: 1,
});
```
run `index.ts`: 
```sh
$ bun index.ts
{
  foo: "bar"
}
{
  length: 1
}
```

### What is the expected behavior?

show the `length` property

run `index.ts`: 
```sh
$ bun index.ts
{
  length: 1,
  foo: "bar"
}
{
  length: 1
}
```

### Additional information

nodejs output
```sh
$ tsx index.ts 
{ length: 1, foo: 'bar' }
{ length: 1 }
```

**Comment by Axiean** [comment]
The behavior you're observing is due to how Node.js handles object logging in the console. When you log an object using `console.log()`, Node.js often optimizes the output for readability by omitting certain properties that it considers less informative.

In your example:

```javascript
console.log({
  length: 1,
  foo: "bar",
});
```

Node.js recognizes the `length` property, but it doesn't display it in the console because it's a common property for arrays, and the object you're logging doesn't have any array-like behavior. It displays the `foo` property because it's user-defined and provides more context.

However, in the second example:

```javascript
console.log({
  length: 1,
});
```

Node.js decides to display the `length` property because it's the only property in the object, and there's no other contextual information to display.

This behavior is specific to how Node.js handles object logging and doesn't affect the actual properties or behavior of the object in your code. If you need to see the `length` property explicitly in the console output, you can convert it to a string or add a label:

```javascript
console.log({
  "length": 1,
  foo: "bar",
});
```

This way, Node.js will display the `"length"` property in the console output.

**Comment by jbrower2** [comment]
@Axiean I don't believe any of that is correct. Tested on Node.js v20.5.1:
```
$ node
Welcome to Node.js v20.5.1.
Type ".help" for more information.
> console.log({ length: 1 })
{ length: 1 }
undefined
> console.log({ length: 1, foo: "a" })
{ length: 1, foo: 'a' }
undefined
```
Moreso, quoting a property in an object literal doesn't have any impact on how it's interpreted.

**Comment by Jarred-Sumner** [comment]
```js
❯ bun lengthy.js
{
  length: 1,
}
```

Fixed some time ago
