### ISSUE TITLE
Mentioning the requirement of AVX2 support on either the website or README

### ISSUE THREAD

**Issue by belowdecent** [oven-sh/bun#5158]
### What is the type of issue?

Something else

### What is the issue?

There are no mentions of the requirement of AVX2 instructions on either the website or README, the only place I have yet found that is reasonably visible where that is mentioned is the "Bun priorities" on Github issues.

That I assume is not the first place (if even a place) a person looks through before deciding to give project a go.
It'd be very nice if there was a mention of this requirement somewhere along the installation section, because it really throws a person off when the first thing bun does is to unexpectedly die.

I see that supporting older hardware is on the list of priorities, which is very commendable. Still though, at least while this is not the case, it'd be nice to have a warning.

**Comment by Electroid** [comment]
Bun has a "baseline" build, which does not require AVX2. The install script should check and install the right binary. Did that not work for you?

Either way, we can explain this in the docs.

**Comment by belowdecent** [comment]
Yeah, it did not for some reason

**Comment by belowdecent** [comment]
I think I might have found the issue.
This line
```if [[ $(cat /proc/cpuinfo | grep avx2) = '' ]]; then```

**Comment by belowdecent** [comment]
no i was mistaken, but for some reason despite condition being true for my pc, i assume i got the wrong version of bun

**Comment by belowdecent** [comment]
after manually installing the baseline version, it crashes, once again mentioning illegal hardware instruction
is there a way to check, which instructions my machine considers illegal?
i am trying to run bun on an old processor: Intel Core 2 Duo T5870, so it might be that the problem is not with AVX2 at all

**Comment by codenius** [comment]
Same issue with Intel Core 2 Duo P8600. Some features work, like `bun run` for node based scripts or help, but runtime i.e. via `bun run -b` and package mangament (`bun install`) not. They either fail silently, in case of `bun run -b` don't start the actual script or throw an `Illegal instruction (core dumped)` error.

I manually installed the `baseline` version, but nothing changed.

**Comment by algj** [comment]
My laptop itself was released in 2022-02-19 (81WB IdeaPad 3 15IML05), and it's super disappointing that I cannot use bun. I really do agree that it should be mentioned somewhere.

**Comment by Jarred-Sumner** [comment]
You can use bun’s baseline build 

If you install via `curl https://bun.sh/install | bash` this problem should go away 

the baseline build still requires CPUs with MMX/SSE4.2, which most after 2012 do support

**Comment by Pigges** [comment]
Any update on this? Because no matter what I do, I keep getting `Illegal instruction` when running `bun install`.

**Comment by Jarred-Sumner** [comment]
Using AVX2 is not a requirement. We provide `baseline` builds of Bun which support CPUs from 2009 or later (nehalem). Installing bun via our recommended installation methods: `npm install -g bun`, `curl https://bun.sh/install | bash`, `brew install oven-sh/bun` all feature-detect to choose the correct version of Bun.

**If you're running into this issue and installing Bun manually, please use the version of Bun which mentions `-baseline` in the name**

To download the `baseline` build of Bun manually, use this link: https://github.com/oven-sh/bun/releases/download/latest/bun-linux-x64-baseline.zip. `bun upgrade` will automatically upgrade with the baseline build of Bun.

If you continue to run into "Illegal Instruction" errors even with the baseline build, it most likely means you're using a CPU emulator (such as qemu) and it is not configured to enable necessary CPU instructions. This will cause issues not just with Bun, but with many other programs you might run on your machine. 

If you find that the non-baseline version of Bun is in use despite the current machine not supporting AVX2/AVX, then please open a new issue and include the exact steps used to install Bun. 

I am closing this as not planned because the original premise (that bun requires AVX2) is not accurate
