### ISSUE TITLE
bun ignoring promise.then, works with top-level await

### ISSUE THREAD

**Issue by ankur-arch** [oven-sh/bun#5220]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

1. Pull this [repo](https://github.com/incacola/bun-playground)
2. Create an `.env` file and add a PostgreSQL database connection string
    ```.env
    DIRECT_URL="postgresql://postgres:postgres@localhost:5432/bun-tester"
    DATABASE_URL="postgresql://postgres:postgres@localhost:5432/bun-tester"
    ```
3. Run `bunx prisma migrate dev`
4. Run `bunx prisma db seed`

### What is the expected behavior?

When the `bunx prisma db seed` command is executed, the output should be

```bash
Environment variables loaded from .env
Running seed command `bun prisma/seed.ts` ...
[0.04ms] ".env"
There are 6 users in the database.

🌱  The seed command has been executed.
```

It seems to be ignoring the prisma query inside the main function in the `seed.ts` file. 

### What do you see instead?

```bash
Running seed command `bun prisma/seed.ts` ...
[0.04ms] ".env"

🌱  The seed command has been executed.
```

### Additional information

This only works if I add a `top-level await` when invoking main in the `seed.ts` file.

```typescript
await main()
.catch((e) =>{
  console.log(e);
  process.exit(1)
})
.finally(() => {
  prisma.$disconnect();
})
```

**Comment by merlinaudio** [comment]
I'm on 1.0.3 and this works:

```ts
new Promise(ok => setTimeout(ok, 1000)).then(() => console.log("this will print after 1s"));
```

Does this still occur for you? I remember having had this issue too.

If it still occurs on 1.0.3, two things come to mind that could be causing this:

- this could be triggered because some transpiler issue with `async function`
- or it could be triggered because [Prisma's Promises are not actual Promises](https://github.com/prisma/prisma/issues/18664). They have their own `Promise` implementation

**Comment by ankur-arch** [comment]
@merlindru, thanks for getting back to me. 
It's working for me in 1.0.3 😄 .
