### ISSUE TITLE
Make `.env` consistent between runtime and test runner

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5230]
Bun runtime uses the following order for using env:
1. .env.local (first)
2. NODE_ENV === "production" ? .env.production : .env.development
3. .env

Works well except when testing. Running `Bun test`, it only loads .env

Is there a way for Bun test to explicitly use another env file?

_Originally reported on Discord: [`env during testing`](https://discord.com/channels/876711213126520882/1151123173354524775/1151123173354524775)_

**Comment by dylan-conway** [comment]
you should be able to use the `.env.test` file when `NODE_ENV=test`

**Comment by danielstaleiny** [comment]
Related to this [.env issue](https://github.com/oven-sh/bun/issues/4594#issuecomment-1716371991) . I can also see that in v1.0.1 .env.test | .env.development is not loaded correctly based on NODE_ENV environment. 


I can also confirm that it still not working on version 1.0.2

Command `bun test` yields NODE_ENV=undefined.  I believe it should be set to 'test'.

**Comment by Electroid** [comment]
When running `bun test`, the environment variable should be `NODE_ENV=test`. But that is currently broken, and being tracked here: https://github.com/oven-sh/bun/issues/4118

**Comment by april83c** [comment]
why is this closed? .env.local is still not loaded during tests... is this intentional?

**Comment by Jarred-Sumner** [comment]
@april83c setting NODE_ENV=test in bun test by default was tracked in https://github.com/oven-sh/bun/issues/4118 and since been completed. This issue was closed as a duplicate. 

It sounds reasonable to load .env.test.local || .env.local in test, depending on what other tools do to verify we aren’t introducing unexpected behavior. Can you file a new issue with this feature request?
