### ISSUE TITLE
Transpiler stack overflow when loading `aws-csdk-lib`

### ISSUE THREAD

**Issue by soulman-is-good** [oven-sh/bun#5398]
### What version of Bun is running?

- 1.0.1
- 1.0.2
- 1.0.3

### What platform is your computer?

- Linux 5.4.254-175.358.amzn2int.x86_64 x86_64 x86_64
- Linux 5.10.192-182.736.amzn2.x86_64 x86_64 x86_64 (last Amazon AL2 EC2 AMI)

NOTE: This bug is NOT reproducible on:
- Linux 4.15.0-20-generic x86_64 x86_64
- Linux 5.4.0-1103-aws x86_64 x86_64 (ami-0d7fd770997502624)
- Linux 5.14.21-150500.53-default x86_64 x86_64
- Linux 5.15.0-58-generic x86_64 x86_64
- Linux 6.2.14-300.fc38.aarch64 aarch64 aarch64

### What steps can reproduce the bug?
```
mkdir test-bun-aws-cdk-lib-bug && \
cd test-bun-aws-cdk-lib-bug && \
bun add aws-cdk-lib constructs && \
echo 'import cdk from "aws-cdk-lib"; cdk;' > index.ts && \
bun run .
```

### What is the expected behavior?

exit with status 0

### What do you see instead?

[1]    30502 segmentation fault  bun run .

### Additional information

Would be great to understand what causes segmentation fault

**Comment by Electroid** [comment]
Thanks for reporting this, we're taking a look.

**Comment by bitfrost** [comment]
I am seeing this as well in github action runner's ubuntu-latest images as well.

**Comment by soulman-is-good** [comment]
Tested on
- 1.0.2
- 1.0.3

Still does not work. 
Disclaimer: I'm not tracking changes in the code base. Just tested and reported.

**Comment by itsyoboieltr** [comment]
this issue still persists

**Comment by weklund** [comment]
Is the root cause known for this?  Have experienced this issue as well.

**Comment by Electroid** [comment]
Could you provide an exact EC2 instance type and AMI for us to try? I tried and it works successfully:
* t3.xlarge / [ami-0830c9faf0efc29ff](https://us-west-1.console.aws.amazon.com/ec2/home?region=us-west-1#ImageDetails:imageId=ami-0830c9faf0efc29ff)
* t2.micro / [ami-0830c9faf0efc29ff](https://us-west-1.console.aws.amazon.com/ec2/home?region=us-west-1#ImageDetails:imageId=ami-0830c9faf0efc29ff)

**Comment by bitfrost** [comment]
This may have been fixed in later versions of the cdk
Here is a crash (repo based on what I was seeing earlier, I pinned back to 2.96.2 (cdk)
https://github.com/bitfrost/bun-cdk-segfault/actions/runs/8273896169/job/22638421158
Latest cdk works:
https://github.com/bitfrost/bun-cdk-segfault/actions/runs/8273927719/job/22638499932

**Comment by bitfrost** [comment]
Hmm, after updating an internal repo using the cdk to latest I am still getting 
error: script "build-demo" was terminated by signal SIGSEGV (Address boundary error)
/home/runner/work/_temp/31c4f6f5-d52d-4733-a8[14](https://github.com/bitfrost/zenfumi/actions/runs/8274085297/job/22638907319#step:7:15)-301888c983eb.sh: line 1:  3264 Segmentation fault      (core dumped) bun build-demo
I will see if I can pull a working crash into my dummy repo above for you.

**Comment by bitfrost** [comment]
Actually,  this is gone in my internal repo too post updates to latest bun and latest cdk libs. Pretty sure I just missed updating 1 package.json when I tested earlier

**Comment by andreif** [comment]
The referenced issue above contains Dockerfile to reproduce with the latest versions. It's using oven/bun.

Actually, I'll just paste it here too:

```dockerfile
FROM --platform=linux/aarch64 oven/bun
RUN bun install -g aws-cdk
RUN bun x cdk init app --language typescript
RUN bun install
RUN sed -i 's/npx ts-node --prefer-ts-exts/bun/g' cdk.json
CMD ["x", "cdk", "synth"]
```

**Comment by Zeryther** [comment]
Can confirm this still happens under Bun v1.1.2

**Comment by andreif** [comment]
@Electroid Could you shed some light on why it fails so we know what to wait for?

**Comment by donflopez** [comment]
Same error here:

**[1]    20134 segmentation fault  bun run ./lib/cli.ts**

I'm using Amazon Linux 2 on Graviton.

**Comment by Jarred-Sumner** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/8021

**Comment by paperdave** [comment]
this is an early wip but i got a patch that makes it work. it's not perfect but i expect this to be up for review by tomorrow and available later. apologize for the extreme delay for this one.

`import * as aws from 'aws-cdk-lib'; aws`

<img width="743" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/961618b2-6408-4d09-9320-dfe25878d19a">

i do want to explain briefly what has gone wrong here, since only the issue title was changed, but ive been aware for a while that it's a stack overflow within `simplifyUnusedExpr`, which is used during minification (given an expression that has it's result discarded, attempt to minimize it). aws-cdk-lib happens to have an extremely nested comma operator which causes this to stack overflow. the correct solution is to rewrite this as a nonrecursive method, which is not trivial.
