### ISSUE TITLE
bun did not await result from exec

### ISSUE THREAD

**Issue by gaoxiaoliangz** [oven-sh/bun#5530]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

main.js
```js
import { exec as _exec } from "node:child_process";
import { promisify } from "node:util";

const exec = promisify(_exec);

async function main() {
  console.log(1);
  await exec("ls");
  console.log(2);
}

main();
```

bun main.js

### What is the expected behavior?

logs
1
2

### What do you see instead?

logs
1

### Additional information

When run with node, it logs correctly. And when I put await before the execution of main(), it works nicely.

**Comment by dead** [comment]
For some reason if you change the code to:

```js
import { exec as _exec } from "node:child_process";
import { promisify } from "node:util";

const exec = promisify(_exec);

async function main() {
  console.log(1);
  await exec("ls");
  console.log(2);
}

await main();
```

it works as expected

**Comment by muxahuk** [comment]
```javascript
import { exec as _exec } from "node:child_process";
import { promisify } from "node:util";

const exec = promisify(_exec);

async function test2() {
    console.log(3);
    await exec("ls");
    console.log(4);
}

async function test1() {
    console.log(1);
    test2();
    await exec("ls");
    console.log(2);
}

test1();
```
prints

```bash
bun run test.ts
1
3
4
```
this works strange

node prints
```bash
node test.mjs
1
3
2
4
```

also

```javascript
import { exec as _exec } from "node:child_process";
import { promisify } from "node:util";

const exec = promisify(_exec);

const execPromiseHoisted = exec('ls');

async function test2() {
    console.log(3);
    await execPromiseHoisted;
    console.log(4);
}

async function test1() {
    console.log(1);
    test2();
    await execPromiseHoisted;
    console.log(2);
}

test1();
```
bun prints
```bash
1
3
```
node prints
```bash
1
3
4
2
```

**Comment by yschroe** [comment]
Edit: Welp, bad timing. At least I learned something.😅

I had a little look into this and to me it seems that the main thread is being terminated too early and the execution is stopped before the promise is resolved.

There are quite a few functions being called internally, but I'll try to summarize:

1. `exec("ls")` is called.
2. `Bun.spawn(...)` is used to start a new child process. 
3. Bun.spawn is calling an `onExit()` callback when the task inside the child_process is done. 
4. On process.nextTick: The exit handler `#handleOnExit()` is called.
5. A "close" event is being emitted.
6. The callback passed to `exec(...)` is called. Since this callback is optional, in those cases a dummy function is created internally.
7. The callback triggers `resolve()` on the Promise.

When I execute the test script from the issue I see that only the functions up to step 3 are called. Step 4 is called on process.nextTick so I guess the process has already stopped before that?
![image](https://github.com/oven-sh/bun/assets/5794325/5254f31d-149b-455d-82f4-51844e69dd26)


For `exec(...)` actually a custom function is used, when promisify is called. If I add a `setTimeout(() => {}, 500);` in this custom function, just to keep the process running a bit longer, I can see that all 7 steps from above are executed and the value "2" is also written to the console.

#### child_process.js
```javascript
const customPromiseExecFunction = orig => {
  return (...args) => {
    let resolve;
    let reject;
    const promise = new Promise((res, rej) => {
      resolve = res;
      reject = rej;
    });
    
    // this line "fixes" the problem
    setTimeout(() => {}, 500);

    promise.child = orig(...args, (err, stdout, stderr) => {
      console.log("callback passed to exec() called!");
      if (err !== null) {
        err.stdout = stdout;
        err.stderr = stderr;
        reject(err);
      } else {
        console.log("Resolving promise.");
        resolve({ stdout, stderr });
      }
    });
    return promise;
  };
};
```
![image](https://github.com/oven-sh/bun/assets/5794325/3c981bf2-f30c-4371-a34a-862806f030bf)

But here I am stuck, because I don't know where and how the processes are managed internally.

**Comment by Jarred-Sumner** [comment]
<img width="420" alt="image" src="https://github.com/oven-sh/bun/assets/709451/9b02a654-bd47-4a8d-a92d-3c2f4174c934">

This is fixed in canary by @cirospaciari 

Please run `bun upgrade --canary` if you don't want to wait

**Comment by bony000** [comment]
I have same issue
Which node version you use?
