### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by sirber** [oven-sh/bun#560]
### Version

nope

### Platform

Linux sirber-netbook 5.18.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jul 2 15:56:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

just launch "bun" from the commandlinealwa

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

dunno yet

### What do you see instead?

Illegal instruction (core dumped)

### Additional information

CPU is an Intel Celeron N4020

**Comment by vrmiguel** [comment]
Did you try following what's written in the README?

https://github.com/oven-sh/bun#illegal-instruction-core-dumped

**Comment by sirber** [comment]
that worked, thanks!
![image](https://user-images.githubusercontent.com/3911428/178175949-32138044-9c1e-4693-9a0e-fd41c661ec33.png)

**Comment by xenogew** [comment]
I also found the same issue, I'm not sure is it related here or not, but let's me share what I found.

Sorry if I trouble by replied to `closed` issue.

## Version

0.1.4

## Platform

Linux: Pop_OS 22.04  LTS

## What steps will reproduce the bug?

just launch "bun" from the command line.

## How often does it reproduce? Is there a required condition?

always

## What is the expected behavior?

dunno yet

## What do you see instead?

```
Illegal instruction (core dumped)
```

## Additional information

CPU is an Intel Celeron N5095 @ 2.00 GHz x 4

And solution which be recommended here
https://github.com/oven-sh/bun#illegal-instruction-core-dumped

It didn't found the resource how to solve? Does the link exists?
