### ISSUE TITLE
`performance.now()` returns `NaN` when called extremely fast

### ISSUE THREAD

**Issue by jack-weilage** [oven-sh/bun#5604]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49
1.0.3+0a318ecca14ab1e71aa60ae8eadbd16343b3a3ea

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64
Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a file with a loop checking `performance.now()`

```ts
let i = 0
while (true) {
  const now = performance.now()

  if (Number.isNaN(now)) {
    console.log(i)
  }

  i++
}
```

2. Run with `bun run file.js`

### What is the expected behavior?

The loop should never log anything, as `performance.now()` should never return `NaN`.

When run in the browser or via `node bug.js`, the loop continues forever.

### What do you see instead?

```bash
bun run bug.js
932599
2521622
8352525
9482475
12140024
16258548
16422489
16584413
18517983
19007226
20344855
20887794
26493524
27206784
28011873
28498102
29000819
31453228
37471626
^C
```

The loop logs once every ~1m calls on average, with a max of ~10m calls and min of ~100k calls.

### Additional information

This bug ruins benchmarks which use `performance.now()`.

**Comment by Jarred-Sumner** [comment]
Likely a DOMJIT issue, potentially with FTL.

**Comment by pan93412** [comment]
> Likely a DOMJIT issue, potentially with FTL.

Unreproducible in Safari Technology Preview, so I suppose that this issue is not from WebKit.

![CleanShot 2023-09-17 at 18 33 45@2x](https://github.com/oven-sh/bun/assets/28441561/28cf74e9-ae2d-4a44-86e4-e68b01b3f256)

I added the `std::cout` debug statement in `functionPerformanceNowBody()`:

![CleanShot 2023-09-17 at 18 35 14@2x](https://github.com/oven-sh/bun/assets/28441561/816d6e77-04d8-4052-8340-d0dc0aab295a)

And I found that it only triggers when the `time` from `Bun__readOriginTimer(global->bunVM())` is divisible by `1000000`:

<details>
<summary>Code for test</summary>

```js
for (let i = 0; i < 11451400; i++) {
    const now = performance.now();
    if (Number.isNaN(now)) {
      console.log("Triggered")
    }
}
```

</details>

![CleanShot 2023-09-17 at 18 31 33@2x](https://github.com/oven-sh/bun/assets/28441561/ea57e692-d56e-44ed-bab8-1e3086ca6b6a)

![CleanShot 2023-09-17 at 18 31 47@2x](https://github.com/oven-sh/bun/assets/28441561/f08d8530-fcec-420a-b263-90d154ae46cc)

![CleanShot 2023-09-17 at 18 31 58@2x](https://github.com/oven-sh/bun/assets/28441561/db385081-5710-48a1-8a3c-40360edf77b5)

However, not all numbers divisible by `1000000` triggers this bug:

![CleanShot 2023-09-17 at 18 33 12@2x](https://github.com/oven-sh/bun/assets/28441561/f99d28fd-6976-4d33-b636-15ce5581e685)

Hope this helps. (The testcase can be seen at https://github.com/oven-sh/bun/pull/5614)

**Comment by Jarred-Sumner** [comment]
Bun's implementation of `performance.now` is custom and Safari's `performance.now` doesn't use DOMJIT. This appears to have begun in at least Bun v0.2.0 (but not Bun v0.1.1)

Declaration:

https://github.com/oven-sh/bun/blob/0404d09cc74d865c09a9c4fa965d078035d07027/src/bun.js/bindings/ZigGlobalObject.cpp#L2112-L2126

Implementation:

https://github.com/oven-sh/bun/blob/0404d09cc74d865c09a9c4fa965d078035d07027/src/bun.js/bindings/ZigGlobalObject.cpp#L2069-L2073

My current thinking is that `SpecBytecodeDouble` is not properly supported in DOMJIT.  Or that `DFG::AbstractHeapKind::SideState` is wrong. 

Do any ideas come to mind @Constellation?

**Comment by dylan-conway** [comment]
`jsNumber` will cast to `int32_t` if possible, giving the value a number tag instead of encoding as a double. I'm guessing DOMJIT `SpecBytecodeDouble` signatures don't work unless the value is always encoded as a double. One fix would be changing `jsNumber` to `jsDoubleNumber` in `functionPerformanceNowBody`
