### ISSUE TITLE
Can bun-types be installed as @types/bun ?

### ISSUE THREAD

**Issue by alexsch01** [oven-sh/bun#5674]
### What is the problem this feature would solve?

With ```@types/node``` package, VSCode just works with no tsconfig.json required 

### What is the feature you are proposing to solve the problem?

If possible, have a ```@types/bun``` package instead of ```bun-types```

**Comment by Electroid** [comment]
Not right now, but we want to support this.

**Comment by aryzing** [comment]
Seems this would be more of a "we'll take care of this asap" rather than "not right now"? Don't just about all projects have packages using `@types/*` (which using `types: ["bun-types"]` [disables](https://www.typescriptlang.org/tsconfig#types)) or use standard `lib` (which `bun-types` [disables](https://github.com/oven-sh/bun/blob/main/packages/bun-types/header.txt#L5))?

**Comment by chribjel** [comment]
This should definitely be prioritized, as adding `types: ["bun-types"]` makes for example `window` in a nextjs-prject throw an error `Cannot find name 'window'`

**Comment by Thinkscape** [comment]
This is breaking Next.js apps in several ways, not just `window is undefined`.
This is a major interop issue.
Have a look here: https://github.com/vercel/next.js/issues/58360

**Comment by alexsch01** [comment]
It's completed now!

**Comment by mrdomino** [comment]
Urgh. Bad news: this does not work. Adding `@types/bun` to my `package.json` causes the `lib` line to be ignored in `tsconfig.json`, causing none of the standard dom types to be available.

I am guessing this is because `index.d.ts` says `<reference types="bun-types" />`. It needs to say something else. `typeRoots` works better in `tsconfig.json` fwiw.

**Comment by mrdomino** [comment]
Or I guess, this does technically deliver what this issue requested (there is a `@types/bun` package), but it exacerbates, and does not resolve, #4890.

**Comment by mrdomino** [comment]
One option might be to just replace `@types/bun` with the current contents of `bun-types`, and make `bun-types` do a `<reference types="@types/bun" />`.

**Comment by alexsch01** [comment]
@mrdomino ahh I only tested it without a tsconfig.json file

But this issue makes sense to be closed

**Comment by colinhacks** [comment]
This isn't quite completed until this PR lands in `bun-types@latest`:  https://github.com/oven-sh/bun/pull/7670 which will happen when the next Bun release happens. The new `@types/bun` package is a shim that loads `bun-types`.

That PR reworks the types so that `lib` is properly loaded, and incorporates the official `@types/node` types as a dependency. 

We don't recommend using `@types/bun` yet

**Comment by Thinkscape** [comment]
Just switched from `types: ["bun-types"]` to `@types/bun` and it worked wonders for all the dom-related type errors.

<img width="299" alt="image" src="https://github.com/oven-sh/bun/assets/270528/f6827bd1-ca1f-4bd0-b12c-45811074e728">
<br />
<img width="452" alt="image" src="https://github.com/oven-sh/bun/assets/270528/5aa06915-339a-44df-abba-97516480b0eb">
<br />
<img width="462" alt="image" src="https://github.com/oven-sh/bun/assets/270528/b45c843f-0f07-4296-b1f1-62597f00a660">

Much appreciated @colinhacks and the Bun team ❤️
