### ISSUE TITLE
Sveltekit typescript support doesn't work

### ISSUE THREAD

**Issue by wineTGH** [oven-sh/bun#5677]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 6.1.0-12-amd64 x86_64 Debian 12

### What steps can reproduce the bug?

+ Follow guide on bun site for sveltekit project
+ Use typescript syntax
+ try to run project with bun --bun run dev
+ Get punched in the face by an errror

### What is the expected behavior?

Just work™

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/66317493/5499a2bb-fc1a-4297-86e5-9c669edfd414)

**Comment by piotr-glownia-wrx** [comment]
I believe svelte-kit sync is not triggering properly. When I ran it manually I got:

![image](https://github.com/oven-sh/bun/assets/46427339/a5d7a738-7a74-41d2-a354-442d281745cd)

**Comment by joyfulcat** [comment]
I always get this error on new projects, though it forces dependencies re-optimization automatically which seems to fix it.


![Screenshot from 2023-09-22 14-48-11](https://github.com/oven-sh/bun/assets/121145249/0a987a54-0354-4ab6-a5a9-d93574a758fd)

**Comment by codinkai** [comment]
I also have problems using sveltekit, typescript and bun, together.

See https://github.com/sveltejs/kit/issues/10802

**Comment by notramo** [comment]
It always appears when running a project the first time. The tsconfig file is generated by SvelteKit, but needed to run SvelteKit. It is generated after the error is printed, and next time the dev server is started, it will work.
It can be fixed by restarting the Vite dev server or running `bun run svelte-kit sync` before starting the dev server the first time.

The `@sveltejs/kit` package postinstall script seems to run `svelte-kit sync` automatically. However, Bun was not running postinstall scripts unless added to `trustedDependencies`. The 1.0.17 Bun release enables postinstall by default for the top 500 packages. I guess SvelteKit is in this list, as **I could not reproduce it with the latest release.**

**Comment by wineTGH** [comment]
I checked this again. On version 1.0.21 everything works as it should be.
![image](https://github.com/oven-sh/bun/assets/66317493/fd37664c-c470-43e1-b88f-4da869df3cbf)

**Comment by ghost** [comment]
I've never had problems with SvelteKit, TypeScript, and Bun, make sure you have the Svelte extension installed and that in the settings the TypeScript mode for Svelte is enabled.

**Comment by notramo** [comment]
@wineTGH I think this issue can be closed now.
