### ISSUE TITLE
Support exports.default over exports.node in package.json

### ISSUE THREAD

**Issue by ayonli** [oven-sh/bun#5724]
### What is the problem this feature would solve?

This feature will allow Bun to directly import TypeScript source code from **node_modules** instead of importing the transpiled code.

### What is the feature you are proposing to solve the problem?

For example, in my library, I have this config in my **package.json**

```json
{
    "exports": {
        "default": "./index.ts",
        "node": {
            "require": "./cjs/index.js",
            "import": "./esm/index.js"
        }
    }
}
```

Node.js favors `exports.node` over `exports.default`, which is good. But Bun shouldn't, Bun should use `exports.default` which allows it to import TS files directly.

This feature will encourage library developers to publish libraries with source code, and allow the library user to choose how they want to run the code, whether directly, or after bundled. This option is favored in Deno and Golang, and Bun should support it, whether from the perspective of a TS runtime or an all-in-one bundler.

### What alternatives have you considered?

There are no alternatives, this is the best I can think of.

**Comment by paperclover** [comment]
node doesn't favor exports.node over exports.default. it follows the conditions from top to bottom until a match happens. your config for me matches default before node since it is listed in that order: 
![image](https://github.com/oven-sh/bun/assets/24465214/a6271618-f4ad-40c6-81c5-6ffd200805a8)

Bun will match "node" as a vaild condition because it supports node.js packages.

you want to add the "bun" condition before the node one, which can point to typescript source.
