### ISSUE TITLE
Illegal Instruction WorkAround is not very good

### ISSUE THREAD

**Issue by coffeeispower** [oven-sh/bun#575]
Adding the workaround in the README works for now, but is not ideal. `bun` should be able to adapt and not use instructions that are not supported by the processor instead of crashing and forcing users to use external tools to work around things, avoiding the performance penalities and any possible irregularity.

_Originally posted by @JeDaYoshi in https://github.com/oven-sh/bun/issues/356#issuecomment-1180233187_

**Comment by mikrosystheme** [comment]
I think that Bun cannot directly adapt to missing CPU instructions. It has to provide different builds that are compiled with the appropriate flag (something like `-mno-avx2`) for each supported platform, and detect at install time which one to pull. I agree that the workaround is doing more harm than good, since one of the selling points of Bun is speed. I would remove it from the readme, and state clearly that at the moment a CPU that supports AVX2 is required, maybe adding a test in the install script to present the message to the user and abort the installation.

**Comment by coffeeispower** [comment]
Its not like it will make bun unusable or slower in a way that will have no advantage over other runtimes. Certainly there are ways to emulate these instructions, also there are many many people who still have these old intel cpus, and it is a bit unfair.

**Comment by mikrosystheme** [comment]
I don't know the real impact of a translation layer for missing intrinsics, but I think it would be pretty huge and kind of pointless. Better to provide a build for AVX, that are supported by a wider set of CPUs.

**Comment by coffeeispower** [comment]
> I don't know the real impact of a translation layer for missing intrinsics, but I think it would be pretty huge and kind of pointless. Better to provide a build for AVX, that are supported by a wider set of CPUs.

What i mean is like, not kill compatibility for performance, pretty sure its not gonna make much difference anyway

**Comment by NatoBoram** [comment]
Rather than providing an install script, if you provided built binaries for all platforms and let people download the one they needed, I think it would greatly reduce the scope of the solution you need to this problem.

You don't actually need to handle auto updates or to check for CPU features yourself, the project isn't even in its `v1`.

**Comment by FinnRG** [comment]
Duplicate of #67.
