### ISSUE TITLE
Implement `server.url`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#5758]
It's a common pattern to see this:

```js
const server = Bun.serve(...);
const result = await fetch(`http://${server.hostname}:${server.port}/`);
```

But that's cumbersome, and is invalid for IPv6 addresses. Instead, Bun should provide a built-in API for the URL.

```ts
interface Server {
  get url(): URL;
}
```

**Comment by TiBianMod** [comment]
I will love also to have a `URL` instance on the `Request`

```ts
new URL(request.url);
// is very expensive 😢 
```

**Comment by Electroid** [comment]
> I will love also to have a `URL` instance on the `Request`
> 
> ```ts
> new URL(request.url);
> // is very expensive 😢 
> ```

Unfortunately, that would conflict with the standard Web APIs. We have more flexibility with the Bun APIs.

**Comment by TiBianMod** [comment]
or we can do something like this (url as a second/third parameter)
> I think server is second parameter

```ts
const server = Bun.serve({
  port: 3000,
  fetch(request: Request, url: URL) {
    ///
  },
});
```

the matching of routes etc is based on the URL, (search,  searchParams, pathname... etc), so we need a fast way having all URL info without losing performance.

```ts
const server = Bun.serve({
  port: 3000,
  fetch(request: Request) {
    const url = new URL(request.url);
    // this will have more than 20 percent impact on performance
  },
});
```

> and with the release of v0.8.1 we also have impact on performace with the draining on microtasks and url parser.

**Comment by GabrielDougherty** [comment]
Hi @Electroid since you asked me to try my hand at one of the issues marked "good first issue" I tried implementing this issue in https://github.com/oven-sh/bun/pull/6064. I haven't ever written Zig before and so I need to review the ownership/memory usage of my changes definitely. But I was wondering if my general approach of making JavaScript bindings to url.zig is wrong? Should I be binding to JavaScriptCore instead?
