### ISSUE TITLE
Unable to acquire sequelize connection

### ISSUE THREAD

**Issue by dereke** [oven-sh/bun#5902]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Save this code to 'sequelize.js' (install sequelize)

```js
import { QueryTypes, Sequelize } from "sequelize";

const sequelize = new Sequelize(null, null, null, {dialect: 'postgres'});
console.log(await sequelize.query('select 1;', {type: QueryTypes.SELECT}))
await sequelize.close()
```

Run it with `DEBUG=sequelize* bun sequelize.js`
The process will hang and the query will not run.

The output will look like this:
```
  sequelize:pool pool created with max/min: 5/0, no replication +0ms
  sequelize:connection:pg connection acquired +0ms
```

Run the same code with node:
`DEBUG=sequelize* node sequelize.js`

```js
  sequelize:pool pool created with max/min: 5/0, no replication +0ms
  sequelize:connection:pg connection acquired +0ms
  sequelize:connection:pg connection acquired +22ms
  sequelize:pool connection acquired +77ms
  sequelize:sql:pg Executing (default): select 1; +0ms
Executing (default): select 1;
  sequelize:sql:pg Executed (default): select 1; +2ms
  sequelize:pool connection released +5ms
[ { '?column?': 1 } ]
  sequelize:pool connection drain due to process exit +1ms
  sequelize:pool connection destroy +2ms
``

### What is the expected behavior?

The code should connect to the database, run the query and close the connection.

### What do you see instead?

The process hangs.

### Additional information

_No response_

**Comment by scarabcoder** [comment]
Running into this same issue. 
As far as I can tell, it seems to be an issue with disconnecting from the Postgres server, when Sequelize boots up it does a Postgres version check, then disconnects, but the disconnect callback from the version check query is never being called, so it just hangs.

**Comment by scarabcoder** [comment]
A bit more debugging, it appears this event is not being emitted when Stream#end is called: https://nodejs.org/api/stream.html#event-close

This appears to be an issue in the pg library, not Sequelize itself. 

Here's an excerpt of the code from node_modules/pg/lib/connection.js, the connect() function to open a new connection to Postgres server:

```JavaScript
connect(port, host) {
    var self = this

    this._connecting = true
    this.stream.setNoDelay(true)
    this.stream.connect(port, host)

    this.stream.once('connect', function () {
      if (self._keepAlive) {
        self.stream.setKeepAlive(true, self._keepAliveInitialDelayMillis)
      }
      self.emit('connect')
    })

    const reportStreamError = function (error) {
      // errors about disconnections should be ignored during disconnect
      if (self._ending && (error.code === 'ECONNRESET' || error.code === 'EPIPE')) {
        return
      }
      self.emit('error', error)
    }
    this.stream.on('error', reportStreamError)

    this.stream.on('close', function () {
      self.emit('end')
    })
...
```

The stream.on('close') never gets called when the stream closes. 
If I modify Sequelize to forcibly destroy the connection instead of gracefully end() it, then Sequelize works just fine and is able to make queries/create tables/etc. 
I'm not sure if this is an issue with the connection not closing, or just that the stream isn't emitting the close event. 

Finally, here's how `pg` creates the Stream object:

```JavaScript
module.exports.getStream = function getStream(ssl) {
  const net = require('net')
  if (typeof net.Socket === 'function') {
    return new net.Socket()
  } else {
    const { CloudflareSocket } = require('pg-cloudflare')
    return new CloudflareSocket(ssl)
  }
}
```

**Comment by scarabcoder** [comment]
It does appear that calling WritableStream#destroy does close the connection and emit the `close` event, but WritableStream#end does not emit the `close` event (possibly because it isn't closing the stream).

**Comment by scarabcoder** [comment]
Looks like the only time the "close" event is emitted is when the stream is destroyed, so it doesn't get called when the stream is ended. 
This is the only place I can the close event being emitted:
https://github.com/oven-sh/bun/blob/main/src/js/node/stream.js#L1820

However the "end" event does get called when you call Stream#end. Might be a bug with `pg` using the `close` event instead of the `end` event, or Bun is supposed to be calling the `close` event when the stream is ended in addition to the `end` event. I'm not sure what the expected functionality is there.

**Comment by scarabcoder** [comment]
I believe this is related to the second half of this issue: https://github.com/oven-sh/bun/issues/4733

**Comment by scarabcoder** [comment]
It would seem that Bun Sockets call only the `end` event when a Writable/ReadableStream is ended, but not the `close` event. If the stream is a WritableStream only (such as `fs.writeFile`)  then both the `close` and `end` events are emitted. If it's both a readable and writable stream, only `end` is emitted. 

Here's a script demonstrating that, you get a different output in Bun vs Node:

```JavaScript
import net from "node:net";

/**
 Open a socket on port 8080, connects to socket, waits 1 second, then ends the connection
 */

// Server
net.createServer(function (socket) {
    console.log("Received client connection");
}).listen(8080);

// Client
const s = net.Socket();
s.connect(8080);

s.on("close", () => { // This event never happens in Bun, but does in Node
    console.log("Socket closed");
})

s.on("end", () => {
    console.log("Socket ended")
})

setTimeout(() => {
    s.end();
}, 1000)
```

**Comment by pjb3** [comment]
Can confirm this is still an issue on bun 1.0.6
