### ISSUE TITLE
Inserting before an array is very slow compared to nodejs

### ISSUE THREAD

**Issue by zhaoyuqiqi** [oven-sh/bun#6094]
### What is the problem this feature would solve?

`const a = []
for (let i = 0; i < 10000; i++) {
  a.unshift(i)
}
a.length = 0;
`

### What is the feature you are proposing to solve the problem?

To run faster

**Comment by pepper-lees** [comment]
FWIW, on my system (Windows 11, Ubuntu WSL, Ryzen 5800X) Bun takes just about 30-50% longer to run that benchmark than NodeJS. (7ms vs 4.5ms for 10k iterations, 650ms vs 500ms for 100k iterations). 

But there must be something weird going on with Bun's implementation of JSC, because I tested on Epiphany Browser (Webkit-based) and it runs the 10k iterations in 1ms and 100k iterations in 6ms. Firefox runs the code in similar time to Epiphany, but running the code in Chromium has about the same (bad) performance as Node.

**Comment by jdalton** [comment]
Micro benchmarks can be tricky. Engine perf characteristic differences of lower-level things can be expected. 
Looks like a known JSC todo work-item: https://bugs.webkit.org/show_bug.cgi?id=202669

**Comment by jdalton** [comment]
V8 has had lots of time to be influenced by Node use-case scenarios. JSC will have some catch-up here.

**Comment by pepper-lees** [comment]
> Looks like a known JSC todo work-item: https://bugs.webkit.org/show_bug.cgi?id=202669

This doesn't explain why Epiphany (which I'm 99% sure is Webkit-based) runs the same benchmark as quickly as Firefox, while Bun is about as slow as Node. Can someone test in Safari, just to make sure of the results?

**Comment by simylein** [comment]
I get the following on Safari 17:
1000 => 0ms +-0
5000 => 4ms +-1
10000 => 15ms +-1
50000 => 285ms +-4
100000 => 1156ms +-10

**Comment by pepper-lees** [comment]
> I get the following on Safari 17: 1000 => 0ms +-0 5000 => 4ms +-1 10000 => 15ms +-1 50000 => 285ms +-4 100000 => 1156ms +-10

Thanks for testing; just to verify, could you also check and see if Bun's performance on your system is the same as Safari?

**Comment by simylein** [comment]
I get the following on bun 1.0.3:
1000 => 0.25ms +-0.05
5000 => 3.9ms +- 0.5
10000 => 14ms +- 4ms
50000 => 256ms +- 5ms
100000 => 990 +- 10ms
