### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by TrackZone1** [oven-sh/bun#6145]
### What is the problem this feature would solve?

Add the file "bun.lockb" to the gitignore

### What is the feature you are proposing to solve the problem?

Add the file "bun.lockb" to the gitignore

**Comment by Electroid** [comment]
`bun.lockb` should not be in the gitignore, same reason you do not want your `package-lock.json` to be in gitignore.

**Comment by TrackZone1** [comment]
If I don't want the `package-lock.json` and `bun.lockb` to be included in my github project, I'd prefer it to be the default.

**Comment by TrackZone1** [comment]
this distorts the number of line additions in my merge request

**Comment by Electroid** [comment]
You can edit the `.gitignore` file for your project, but we will keep this as the default.

**Comment by Inplex-sys** [comment]
Tbh i never saw someone saving a package-lock.json 💀

**Comment by TrackZone1** [comment]
not to mention the conflicts in the mr

**Comment by stefnotch** [comment]
@SystemVll @TrackZone1 You might already know this by now, but for posterity: 
Projects will often include lockfiles in their repository for reproducibility. It gives you the ability to go to any commit and perfectly reproduce the setup at that point in time.

You can see it in action in a lot of tools
- https://github.com/vitejs/vite - pnpm-lock.yaml
- https://github.com/angular/angular - pnpm-lock.yaml
- https://github.com/facebook/react - yarn.lock
- https://github.com/vuejs/core - pnpm-lock.yaml (yeah big projects really like using anything other than slow npm)

Bun's lockfile used to be a real hassle because it was binary. So merge conflicts were extra fun to resolve. Luckily they fixed that by moving to a text based file https://bun.com/blog/bun-lock-text-lockfile
