### ISSUE TITLE
Error request:  ConnectionClosed: The socket connection was closed unexpectedly

### ISSUE THREAD

**Issue by hornta** [oven-sh/bun#6197]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Running the same script in node and bun gives different result. It works as expected in Node but not in Bun. It also works as expected in cURL. This is what I receive in Bun:

```
Error request:  ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
 path: "https://appapi2.test.bankid.com/rp/v6.0/auth"
```
The code can be found in one of these replit

[Bun replit](https://replit.com/@junk8/ZanyRemoteLoaderprogram)
[Node replit](https://replit.com/@junk8/node)
```
curl -X POST -d '{"endUserIp":"123.123.123.123"}' --cacert test.ca --cert FPTestcert4_20230629.p12:qwerty123 https://appapi2.test.bankid.com/rp/v6.0/auth --cert-type P12 --header "Content-Type: application/json"
```

I also tried using axios to make the request and passing it an https.Agent but it's **not** working. I get the same error as with Bun so the bug must be within the node:https module.
```ts
const response = await axios.post(
  bankIDTestHostname + options.path,
  JSON.stringify(options.data),
  {
    headers: { "Content-Type": "application/json" },
    httpsAgent: new nodeHttps.Agent({
      pfx,
      passphrase: "qwerty123",
      ca: testCA,
    }),
  },
);
```

### What is the expected behavior?

It should return a response just as it does in Node.

**Comment by zilayo** [comment]
seems related to #5363

Also receiving this error intermittently when using using Axios.get.

It will work for one request and then randomly not work for the next request.

**Comment by rosszurowski** [comment]
I ran into this tonight too when trying to do uploads to R2 using an S3-compatible client.

I tried [aws4fetch](https://github.com/mhart/aws4fetch) and @aws-sdk/client-s3 in all sorts of arrangements. Trying to use blobs, trying to use streams, converting web streams to node streams and then using those, using Uint8Arrays. It would intermittently happen for every permutation I could think of.

```
ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
path: "https://bucket.r2.cloudflarestorage.com/path/path?partNumber=4&uploadId=AKL9aKtYqW5dclXrsE2whW_VOvaApkWxO9LkAYXt3LehtVafuaS8cahCTjb_ONHI_4advkYI1oUI7HlmwCMTzZc-_-nVy-kgh-gCHbZShgfQTOeYr_RmJp8nokqh0pv4dJaz9yAyzUk5gCVHUIFgiZN4XtaGqn31pPB_nJaNZovQxLiRgDtsf7YBdax0Skd8m9d8IGdat6IYjkBJbJy6t0ruulL0BMW-5bPvyRENlL_4nzmLlfhKaUUi6UrtHsSAVRwS5Nehs1V422rjNqmmgfmUiaE9Bit_1ZxR66iM7Vcp8oprJxxHQSsobj_Tq5ysjEL2uOSPFTBRp_4jwJK-kYto&x-id=UploadPart"
```

I'm on `1.0.19+906f86d6f` on macOS on ARM.

I would have suspected it was something with issues in the implementation of some Node APIs, but aws4fetch doesn't touch any Node APIs — it's all web standards.

**Comment by vigenere23** [comment]
Not related to the `--bun` flag, nor any https/certificate/proxy/whatever special connection. The issue seems to be directly related to the `fetch` implementation of Bun.

In my use case, I run API testing scripts, which only does a small bunch of awaited async fetching with **small** JSON payloads (~20 lines max). Here is the very simplest script that triggers the error :

```ts
let i = 1;
while (true) {
    const response = await fetch("some url")
    console.log(i++, await response.text())
}
```

I've tried some publicly hosted websites and they don't trigger the error (maybe the response time is too slow?) but on a localhost Java API (`http://localhost:8080`) it triggers. If I add a bun `sleep` (like `sleep(0)`), it never triggers the error. When used in a real project, it randomly pops up. But still, my guess is that it's more related to **concurrent requests**, maybe a buffer or a cache that overflows or becomes corrupted somehow. Or it's related to the way some server implementations handle a socket closing that's not handled well with Bun.

**The weirdest thing**: With the example script, it always fails at the **256**th or **512**th. Always. 

P.S.: I'm on 1.0.25 on macOS on ARM, but also does this on the latest bun docker image.

**Comment by cristianvnica** [comment]
Getting this error too, on and off, when doing many concurrent request. 

I'm using v 1.0.30, on linux mint

Update - when running same script with node.js I'm getting this error, maybe it helps debugging: 
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 22 terminated listeners added to [Fetch]. Use emitter.setMaxListeners() to increase limit`

**Comment by Yashrocky96** [comment]
This is still happening on the latest Bun v1.0.35, to be able to recreate the issue with Bun on Linux or Mac. Use the below script

`
echo 'fetch("https://www.saferpay.com/api/health/1", { verbose: false }).then(async(res)=>console.log(await
 res.json())).catch(console.error)' | bun run -
`
