### ISSUE TITLE
Fix redundant JSON parsing in `bun install`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#6225]
Currently, in the following scenarios `bun install` will re-parse already parsed package.json files:
- In a workspace, running `bun install` from a workspace member's package.json
- package.json scripts potentially could re-parse 
- Every workspace package's package.json file

We should add an in-memory cache `HashMap(string (absolute file path), Expr)` that is checked before loading package.json files from disk

**Comment by dylan-conway** [comment]
Workspace `package.json` caching (including the root workspace) was added with #11177.

Although we will potentially parse a package.json twice when a package has scripts, the second parse is necessary because it is verifying the existing package.json in `node_modules`. Also, packages with scripts will only parse for scripts when `hasInstallScript: true` is in their manifest, so I think we can close this as complete.
