### ISSUE TITLE
For monorepo project, bun link in sub packages was always link to root projects.

### ISSUE THREAD

**Issue by jqhr** [oven-sh/bun#6254]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Ubunt 22.04 WSL

### What steps can reproduce the bug?

In monorepo project. there are a a lot of subpackages.
In one subpackage A.Run
```bash
bun link
```
In other project outof monorepo. I want to link it.
```bash
bun link A
```
I found it package A which linked was the monorepo project root.

### What is the expected behavior?

Link A, not the root.

**Comment by robertherber** [comment]
I'm experiencing the same. For me it's a link between two monorepos and the link wrongly points to the root of it's monorepo.

Since I tried linking 6 packages I started seeing this error at install:
<img width="306" alt="Screenshot 2023-10-16 at 10 42 22" src="https://github.com/oven-sh/bun/assets/1467411/aa12112c-791c-477e-b072-b3759030ff6b">

And this is what the lockfile looks like:
<img width="371" alt="Screenshot 2023-10-16 at 10 43 36" src="https://github.com/oven-sh/bun/assets/1467411/4f5bcda4-7b18-4798-9c8a-7ff294574d7a">

**Comment by chrisdmacrae** [comment]
This is a dealbreaker for monorepo development.

+100

**Comment by chrisdmacrae** [comment]
A workaround right now is to use a `file:` reference as a `devDependency`, but that's terrible DX.

```
bun add file:../monorepo/packages/package-name`
```
