### ISSUE TITLE
Raspberry PI: No such file or directory when trying to run bun

### ISSUE THREAD

**Issue by grzebla** [oven-sh/bun#6383]
### What version of Bun is running?

1.0.4

### What platform is your computer?

Linux 6.1.21-v8+ aarch64 unknown

### What steps can reproduce the bug?

I downloaded bun for `aarch64` from releases page, extracted it and tried to run.
This is what I'm getting:
```
gblachut@raspberrypi:~ $ bun --version
-bash: /home/gblachut/.bun/bin/bun: No such file or directory
```

### What is the expected behavior?

I also run `uname -a`. This is the output:
```
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by TiranexDev** [comment]
It means that the executable does not match your CPU archeticture

**Comment by v3nntrnx** [comment]
can you try to run "file /home/gblachut/.bun/bin/bun" and logging the output here?

**Comment by grzebla** [comment]
Sure, this is what I get:
```
gblachut@raspberrypi:~ $ file /home/gblachut/.bun/bin/bun
/home/gblachut/.bun/bin/bun: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[xxHash]=39459b35aacdf1fc, stripped
```

**Comment by andreluis-oliveira** [comment]
How did you install Bun?

**Comment by Sub0X** [comment]
Getting the same error here.
Ran the commands as shown on the bun website:
```
curl -fsSL https://bun.sh/install | bash
```
Currently on a Raspberry Pi 4B

```
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by grzebla** [comment]
> How did you install Bun?

via `curl -fsSL https://bun.sh/install | bash`

and then tried to replace it with downloading directly aarch64 binary, but I got same error in all scenarios

**Comment by 0mp** [comment]
It could be that you are running with a 32-bit userland. 

For example, even though my `uname -a` reports `aarch64`, `dpkg --print-architecture` reports `armhf`. I suspect that `bun` does not work on my system because the binary installed by the installer is expecting a 64-bit userland, which I don't have installed (e.g., there is no `/lib/ld-linux-aarch64.so.1` on my system).

**Comment by grzebla** [comment]
Oh, I see. Such a disappointment. I think there is no other way.

**Comment by Electroid** [comment]
We are unlikely to support 32-bit architectures. You would need to get a 64-bit Rasberry Pi.

**Comment by perrydillard** [comment]
Raspberry Pi 5 should support Bun, but you have to install using snap. https://snapcraft.io/install/bunjs/raspbian
I just ordered a Pi 5 8GB and plan to run Bun. I'll update this comment when my hardware arrives and I get it installed.

**Comment by ghcpuman902** [comment]
I had the same issue and realized I downloaded the wrong image. Here's how I solved it:

1. **Check if your Raspberry Pi hardware supports ARM64** by running the following command:

   ```bash
   lscpu
   ```

   Look for the following lines:

   ```
   Architecture:             aarch64
   CPU op-mode(s):           32-bit, 64-bit
   ```

   If you see "64-bit" under "CPU op-mode(s):", your Raspberry Pi can run a 64-bit OS.

2. **Verify your current OS architecture** by running:

   ```bash
   dpkg --print-architecture
   ```

   - If it returns `armhf`, you're using a 32-bit image.
   - If it returns `arm64`, you're using the correct 64-bit image, which Bun.js supports.

3. **Download the correct 64-bit OS**: Go to the [Raspberry Pi OS download page](https://www.raspberrypi.com/software/operating-systems/) and download the 64-bit version. To confirm it's 64-bit, hover over the download button and ensure the file name contains "arm64" instead of "armhf".

4. **Install the 64-bit image**: Use Raspberry Pi Imager to install the image:
   - Select "Use custom" in the Imager and choose the 64-bit image file you just downloaded.
