### ISSUE TITLE
Allow bun:sqlite bind parameters to a prepared statement with object

### ISSUE THREAD

**Issue by drag0n-app** [oven-sh/bun#6591]
### What is the problem this feature would solve?

the docs example (https://bun.sh/docs/api/sqlite)
```ts
const query = db.query("SELECT * FROM foo WHERE bar = $bar");
const results = query.all({
  $bar: "bar",
});
```
Binding javascript object directly
```ts
const query = db.query("SELECT * FROM foo WHERE bar = $bar");
const results = query.all({
  bar: "bar",
});
```

### What is the feature you are proposing to solve the problem?

Binding javascript object directly is easier, No need to add key prefixes (: or ? or @) yourself.

### What alternatives have you considered?

refer to https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#binding-parameters

**Comment by drag0n-app** [comment]
Anyone help make it happen?

**Comment by oliverjam** [comment]
Yeah it's awkward having to manually write out every key with a `$` prefix, especially when you're inserting a larger object. It's especially annoying with TypeScript since you end up with identical duplicate types; one for select with normal keys and one for insert with `$` prefixes. Then you have to make sure you keep them in sync...

E.g. here's something I just had to write:

```ts
type Article = {
  slug: string;
  title: string;
  time: number;
  date: string;
  intro: string;
  content: string;
  draft: 0 | 1;
};

type ArticleIn = {
  $slug: string;
  $title: string;
  $time: number;
  $date: string;
  $intro: string;
  $content: string;
  $draft: 0 | 1;
};

function create(article: ArticleIn): Article {
  // ...
}

// ...elsewhere
create({
  $slug,
  $title,
  $time: Number(time),
  $date,
  $intro,
  $content,
  $draft: draft ? 1 : 0,
});
```

Edit: I came up with a silly helper to avoid duplicating types at least 🙃 

```ts
type Dollarize<T> = {
    [K in keyof T as `$${string & K}`]: T[K]
}

type ArticleIn = Dollarize<Article>
//   ^? type ArticleIn = { $slug: string ... }
```
