### ISSUE TITLE
`eslint` Attempted to assign to readonly property

### ISSUE THREAD

**Issue by RodrigoDornelles** [oven-sh/bun#6730]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Linux 5.15.0-86-generic x86_64 unknown

### What steps can reproduce the bug?

```
bun lint
```

### What is the expected behavior?

lint the project

### What do you see instead?

```
 bunx eslint .
  🔍 Resolving... 
Oops! Something went wrong! :(

ESLint: 8.52.0

TypeError: Attempted to assign to readonly property.
Referenced from: /app/.eslintrc.js
    at _loadPlugin (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3441:12)
    at _loadExtendedPluginConfig (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3228:12)
    at _loadExtends (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3146:24)
    at _normalizeObjectConfigDataBody (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3089:23)
    at _normalizeObjectConfigData (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3037:20)
    at loadInDirectory (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2878:20)
    at _loadConfigInAncestors (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3860:10)
    at getConfigArrayForFile (/tmp/eslint--bunx/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3783:8)
    at _iterateFilesRecursive (/tmp/eslint--bunx/node_modules/eslint/lib/cli-engine/file-enumerator.js:463:45)
    at iterateFiles (/tmp/eslint--bunx/node_modules/eslint/lib/cli-engine/file-enumerator.js:300:20)
```

### Additional information

 * **file:** `.eslintrc.js`

```
module.exports = {
    parser: '@typescript-eslint/parser',
    plugins: ['@typescript-eslint'],
    extends: [
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
    ],
    rules: {
    },
    parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
    },
    env: {
        browser: true,
        es6: true,
    },
};
```

 * **file:** `.eslintignore`

```
*.js
.*.js
```

**Comment by RodrigoDornelles** [comment]
this error occours when i try set `plugins` or `extends` via files `.eslintrc.js`/`.eslintrc.json` or using cli flag.

**Comment by redbmk** [comment]
Wouldn't this be more of an eslint/config issue? Bun doesn't have a native `lint` command. What happens if you run `npx eslint .`?

**Comment by lnoss** [comment]
> this error occours when i try set `plugins` or `extends` via files `.eslintrc.js`/`.eslintrc.json` or using cli flag.

Same (with 1.0.7). An ESLint instance gives the same results. https://eslint.org/docs/latest/integrate/nodejs-api

**Comment by mProjectsCode** [comment]
For me the problem was not having `@typescript-eslint/eslint-plugin` installed, which i realized after running it with node, which told me that that dependency is missing. I hope this helps.

**Comment by lucadibello** [comment]
When I run eslint via `bunx` this is the output:

```
Attempted to assign to readonly property.
Referenced from: /workspaces/..../.eslintrc.json
```

On the other hand, by running eslint via `npx`, the output actually displays the underlying error:

```
Failed to load plugin 'prettier' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /Users/lucadibello/Projects/beer-search-engine/beer-search-engine/__placeholder__.js
Referenced from: /Users/lucadibello/Projects/beer-search-engine/beer-search-engine/.eslintrc.json
```

I simply just forgot to install the package `eslint-plugin-prettier`.

**Comment by RodrigoDornelles** [comment]
@Electroid I discovered something that in my opinion is a security problem.

**bun is vulnerable to hijacking and typosquatting**, as it is implicit that when typing a command that does not exist `bun lint` it will look for npmjs to download and execute <https://www.npmjs.com/package/lint>, just like me must be a common mistake.

 * <https://github.com/oven-sh/bun/issues/6728#issuecomment-1781753345>
 
-----
@Jarred-Sumner @dylan-conway @colinhacks

**Comment by adamaveray** [comment]
The underlying problem behind this issue is ESLint trying to overwrite the `message` property of any error thrown during plugin resolution [here](https://github.com/eslint/eslintrc/blob/fb8d7ffbb27214686318a07e16ac8878aaafc805/lib/config-array-factory.js#L1105). Bun throws a special ResolveMessage error object when a dynamic import cannot be resolved rather than a regular Error object, the `message` property of which is read-only unlike in Node. When ESLint attempts to overwrite that property, when using Bun this issue's readonly property assignment error is thrown which causes the unclear error output, obfuscating the underlying issue of an unknown plugin/config being referenced.

Here are the minimum steps to reproduce this issue:

```sh
bun install eslint
echo '{ "plugins": ["unknown-plugin"] }' > .eslintrc.json

bun --bun x eslint . # Shows unclear error
npx eslint . # Shows understandable error
```

Here is a comparison of the error output under the two engines:

<details>
    <summary>Node Output (Correct)</summary>

    Oops! Something went wrong! :(

    ESLint: 8.57.0

    ESLint couldn't find the plugin "eslint-plugin-unknown-plugin".

    (The package "eslint-plugin-unknown-plugin" was not found when loaded as a Node module from the directory "…".)

    It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

        npm install eslint-plugin-unknown-plugin@latest --save-dev

    The plugin "eslint-plugin-unknown-plugin" was referenced from the config file in ".eslintrc.json".

    If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

</details>

<details>
    <summary>Bun Output (Incorrect, Unclear)</summary>

    Oops! Something went wrong! :(

    ESLint: 8.57.0

    TypeError: Attempted to assign to readonly property.
        at _loadPlugin (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3452:12)
        at <anonymous> (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:815:40)
        at reduce (:1:11)
        at _normalizeObjectConfigDataBody (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:701:112)
        at _normalizeObjectConfigData (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:676:26)
        at loadInDirectory (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:622:111)
        at _loadConfigInAncestors (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1070:57)
        at getConfigArrayForFile (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1036:119)
        at _iterateFilesRecursive (…/node_modules/eslint/lib/cli-engine/file-enumerator.js:131:62)
        at iterateFiles (…/node_modules/eslint/lib/cli-engine/file-enumerator.js:73:47)
</details>

While ideally ESLint would use its own error object/Error instance, for compatibility with NodeJS the  ResolveMessage `message` property should be writeable.

**Comment by Jarred-Sumner** [comment]
Thanks for the investigation @adamaveray. In #9930, I made `ResolveMessage` and `BuildMessage`'s `message` property modifiable. This is not a complete fix, as `BuildMessage` and `ResolveMessage` really should extend `Error` (also so that a `.stack` can be provided and `instanceof Error` works as expected) but this should work as a quick compromise for now. The other downside with this approach is that `console.log` won't reflect the modified `message`, ti will show the original `message` from the `ResolveMessage` because those get a custom formatter  to help us provide a more useful error
