### ISSUE TITLE
mock.module() only works in one test

### ISSUE THREAD

**Issue by mstuercke** [oven-sh/bun#6874]
### What version of Bun is running?

1.0.8+2a405f691e80725fe0b97b93afd3b8cfed13fa5f

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

I have the following setup:
```typescript
// A.ts
import {trim} from 'lodash';
export const a = () => trim('  XXX  ');
```

```typescript
// A.test.ts
import {expect, it, mock} from 'bun:test';
import {a} from './A.ts';

mock.module('lodash', () => ({trim: () => 'mocked'}));

describe('A', () => {
  it('should be mocked', () => {
    expect(a()).toEqual('mocked');
  });
});
```

```typescript
// B.ts
import {trim} from 'lodash';
export const b = () => trim('  XXX  ');
```

```typescript
// B.test.ts
import {expect, it, mock} from 'bun:test';
import {b} from './B.ts';

mock.module('lodash', () => ({trim: () => 'mocked'}));

describe('B', () => {
  it('should be mocked', () => {
    expect(b()).toEqual('mocked');
  });
});
```

The file `A.ts` and the file `B.ts` have the exact same content (except the naming).
The file `A.test.ts` and the file `B.test.ts` have the exact same content (except the naming).

### What is the expected behavior?

Both tests succeed

### What do you see instead?

- `A.test.ts` succeeds
- `B.test.ts` fails
  - The mock of `lodash` didn't work in `B.test.ts`

**Comment by Jarred-Sumner** [comment]
temporary workaround until we figure out a way to make this better

instead of using the string literal `"lodash"`, try `require.resolve("lodash")`

The problem is

The first time this loads, the original `lodash` module was never imported

The second time, it is resolved, that string switches from `'lodash'` to the resolved file path on disk.

But it's not clear if we can actually run the module resolver always. That would introduce another edgecase - what happens if the module deosn't exist because the module you're mocking isn't installed or available in the current environment?

**Comment by mstuercke** [comment]
Seems to work now with Bun `1.0.19`
