### ISSUE TITLE
illegal hardware instruction (core dumped)  bun update

### ISSUE THREAD

**Issue by colinkeenan** [oven-sh/bun#6907]
### What version of Bun is running?

1.0.8+2a405f691e80725fe0b97b93afd3b8cfed13fa5f

### What platform is your computer?

Linux 6.5.9-arch2-1 x86_64 unknown

### What steps can reproduce the bug?

```
bun upgrade
bun update
```

### What is the expected behavior?

Upgrade Bun and  either update any old modules or report that they are already up to date.

### What do you see instead?

```
bun v1.0.8 is out! You're on 1.0.7
[3.39s] Upgraded.
```
and

```
bun update v1.0.8 (2a405f69)
zsh: illegal hardware instruction (core dumped)  bun update
```

### Additional information

Maybe the bug occurs when running `bun update` in a project that doesn't need any updates. Also, I think bun.lockb usually changes when I do `bun upgrade`, but it didn't this time.

**Comment by colinkeenan** [comment]
Also, bun no longer runs my project at all. How can I downgrade to version 1.07?

**Comment by aydink88** [comment]
> Also, bun no longer runs my project at all. How can I downgrade to version 1.07?

download install script 
`curl https://bun.sh/install > install.sh`

make it executable
`chmod +x install.sh`

give the version as argument
`./install.sh bun-v1.0.7`

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.0.9. Please upgrade `curl https://bun.sh/install | bash -s`

If you continue to run into this, leave a comment

**Comment by tobycm** [comment]
@Jarred-Sumner 
Hello, my bun installation is not running anymore, just straight up throwing `illegal hardware instruction (core dumped)`

It was installing fine last versions, run the bun executable fine but any other stuff didn't work because `Illegal instruction`

CPU: Pentium E5300
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 5.15.0-88-generic

Happens on my other machine as well:
CPU: AMD E-450 APU
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 5.15.0-88-generic

Installed bun with `curl https://bun.sh/install | bash -s`:
![image](https://github.com/oven-sh/bun/assets/62174797/5d4e6ca3-2fc4-4000-b137-c707550419dd)


Also should I make a new issue?

**Comment by sistematico** [comment]
Same issue for me.

`Intel(R) Atom(TM) CPU N2600   @ 1.60GHz` on Arch Linux.

```free -m
               total        used        free      shared  buff/cache   available
Mem:            1960         329         855           0         959        1631
Swap:           4095           0        4095
```

#6224
