### ISSUE TITLE
Support "npm:" prefix in imports like deno

### ISSUE THREAD

**Issue by begoon** [oven-sh/bun#6987]
### What is the problem this feature would solve?

Imagine a script:
```javascript
import chalk from "chalk";
```

`bun` runs it as is, no problem. It pulls the external dependency and runs.

To run this script in `deno`, we need to change it to:
```
import chalk from "npm:chalk";
```
Or to add the `packages.json` file with:
```json
{ "dependencies": { "chalk": "^5.3.0" } }
```
Otherwise, deno fails with:
```
error: Relative import path "chalk" not prefixed with / or ./ or ../
```

### What is the feature you are proposing to solve the problem?

`bun` could ignore the "npm:" prefix.

It will allow running this script without any change or extra files in `bun` and `deno`.

**Comment by Electroid** [comment]
Thanks for opening an issue. While this is something we could support, it would be incompatible with Node.js.

**Comment by Malix-Labs** [comment]
@Electroid @Jarred-Sumner
As #9331 mentioned,
Can this current issue be reconsidered and reopened after the surge of [`JSR`](https://jsr.io/)?

**Comment by jordanbtucker** [comment]
This is tangential, but for anyone coming here wondering if JSR can be used with Bun, it can.

For example, let's say you want to use the [`@std/encoding`](https://jsr.io/@std/encoding) library from the Deno Standard Library hosted on JSR. Run the following command in your project directory:

```
bunx jsr add @std/encoding@0.224 # the version is optional
```

Now you can use imports like this:

```ts
import { decodeBase64Url, encodeBase64Url } from "@std/encoding/base64url";
```

This works because `jsr` adds a [scoped registry](https://docs.npmjs.com/cli/v9/using-npm/scope#associating-a-scope-with-a-registry) to `.npmrc` and an [alias](https://docs.npmjs.com/cli/v10/using-npm/package-spec#aliases) to a scoped package as a dependency in `package.json` that looks like this:

```
"@std/encoding": "npm:@jsr/std__encoding@^0.224.3"
```

The following commands are equivalent to running `bunx jsr add @std/encoding@0.224`:

```
npm config -L project set '@jsr:registry' 'https://npm.jsr.io'
npm install @std/encoding@npm:@jsr/std__encoding@0.224
```

---

However, this still doesn't let you use `npm:` and `jsr:` specifiers.

**Comment by Gin-Quin** [comment]
No, there would be no compatibility issue since you can't have ':' symbol in a npm package name.

That would make Bun a superset of Node (again).

Honestly, I think that's a great idea because it makes Bun not dependant to npm.

In my opinion, JSR is to NPM what Bun is to Node, a better version of something that was great some time ago. Bun + JSR would match very well together, being two modern tools for modern JS/TS, especially since Bun can run natively Typescript.

**Comment by Malix-Labs** [comment]
_I'm using JSR and find it fantastic too_

**Comment by Malix-Labs** [comment]
Has someone found a documentation to import and manage JSR dependencies in Bun ?

**Comment by jordanbtucker** [comment]
> About that, has someone found a documentation to import and manage JSR dependencies in Bun ?

https://github.com/oven-sh/bun/discussions/11897

**Comment by miguelvictor** [comment]
+1 on this. It's now hard to defend bun when you have deno 2.0 🥲

**Comment by jordanbtucker** [comment]
> +1 on this. It's now hard to defend bun when you have deno 2.0 🥲

That, and Node is adding more support for TypeScript.

https://github.com/nodejs/node/blob/4d5c885f8a6ba29382e4d0339e0ac8220b1a296b/doc/api/typescript.md

**Comment by kravetsone** [comment]
When Deno drop-in replacement

**Comment by Malix-Labs** [comment]
@kravetsone shipped in Deno 2 which has been released lately, but this is not the subject of this issue

**Comment by greentore** [comment]
This issue is annoying. I wanted to give bun a try and move one of my projects from deno to get native macros, but I really don't want to rewrite my imports just because bun refuses to add basic deno compatibility.

**Comment by Malix-Labs** [comment]
@Electroid, please kindly consider reading this comment: https://github.com/oven-sh/bun/issues/6987#issuecomment-2041438328

**Comment by ymeine** [comment]
@Electroid, I know @Gin-Quin has already raised this, but I'd like to stress that there's no real incompatibility with Node.js. Closing the issue as "not planned" based on a flawed premise — and without any follow-up — risks giving the project a poor reputation and sapping community enthusiasm. Could the team at least revisit this decision?

Here's why it isn't an incompatibility: code written for Node.js is expected to run under Bun, whereas code written for Bun (with its APIs, plugins, macros, etc.) is not expected to run in Node.js — otherwise Bun would be nothing more than a reimplementation. That original objection simply doesn't hold up.

Tagging @Jarred-Sumner too because of duplicate #9331 also marked as "not planned"

**Comment by kravetsone** [comment]
Bun can implement this but without typescript support it would be useless

**Comment by ymeine** [comment]
@kravetsone's message just made me realize I forgot to mention an important point: I am not saying I am in favor of the OP's proposal as is, I just disagree with the way it was discarded.

Supporting prefixes like `npm:` or `jsr:` could lead to many questions (some of which have already been mentioned): 

- should Bun install the packages on the fly? If so, where?
- should those prefixes just be discarded, so Bun would load modules from `node_modules` in any case? It would still be a step towards supporting Deno code (though the dependency would have to be added to `package.json`)
- should it just be handled by plugins, which can then decide?

And indeed, as @kravetsone points out, TypeScript support would be needed: 

- module resolution in IDEs (Deno does this by providing their own [language server](https://docs.deno.com/runtime/reference/lsp_integration/))
- support for external types (Deno supports this [through comments](https://docs.deno.com/runtime/fundamentals/node/#importing-types))

At the very least, this request raises some interesting questions. Maybe the team would prefer moving that to a GitHub discussion?

**Comment by Gin-Quin** [comment]
Ideally, it would be Typescript language server's role to allow URL imports. That would be quite an awesome feature actually, especially if you want to share an api with Typescript typings. Deno is patching a missing feature.

**Comment by Malix-Labs** [comment]
If anything, that's a missing feature in EcmaScript (non-CJS), not in TypeScript

This type of import would need to be usable with vanilla EcmaScript

And the import part is done by the runtime itself (node, bun, deno), not by a language server
