### ISSUE TITLE
error message with Bun.serve for EACCESS is shown as EADDRINUSE

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#7187]
### What platform is your computer?

Linux

### What steps can reproduce the bug?

```
Bun.serve({ fetch(){}, port: 1003 });
```
 

### What is the expected behavior?

```
EACCES: permission denied 0.0.0.0:1003
```

### What do you see instead?

```
EADDRINUSE: Failed to start server. Is port 1003 in use?
```

### Additional information

i think this is an easy fix. grep for this string to see where listen failures are handled

`noinline fn onListenFailed(this: *ThisServer) void {`

grep this line for where i think we start listening
`this.app.listenWithConfig(*ThisServer, this, onListen, .{`

bun.serve is defined in src/bun.js/api/bun.zig by
`pub fn serve(`

**Comment by liz3** [comment]
I don't actually think that this is very easy, because we have no indication of why the socket creation failed, i spend some time looking into this and this goes deep into usockets. the zig side only gets: "we failed to allocate the socket".

Implementing this requires passing up the error which actually occurs.

**Comment by paperclover** [comment]
my bad then, removed gfi tag
