### ISSUE TITLE
Error when parsing keys with hyphen in some JSON files

### ISSUE THREAD

**Issue by Azarattum** [oven-sh/bun#7261]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Linux 5.15.0-101.103.2.1.el8uek.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

When importing/requiring some JSON files that contain hyphens in the keys, Bun can throw a syntax error. Currently can reproduce with files named `tsconfig.json`. Maybe parsing of `tsconfig` is somehow different?

```sh
echo '{ "key-with-hyphen": true }' > tsconfig.json
bun -e 'require("./tsconfig.json")'
```

Results in:
```
SyntaxError: Unexpected token '-'. Expected '}' to end an export list.
      at /home/tsconfig.json:1:2
```

With files named other than `tsconfig.json` everything works as expected:
```sh
echo '{ "key-with-hyphen": true }' > demo.json
bun -e 'require("./demo.json")'
```

### What is the expected behavior?

All JSON files should be treated and parsed the same.

### What do you see instead?

`tsconfig.json` files throw when threre are hyphens in keys.

### Additional information

The issue was discovered with `tsconfig.json` containing a key for `ts-node` configuration (which includes a hyphen).

**Comment by Jarred-Sumner** [comment]
Interesting

**Comment by DontBreakAlex** [comment]
So it turns out that JSON config files are handled differently
https://github.com/oven-sh/bun/blob/22818e6806cfff66804a74bdbd71f90d195f8183/src/bun.js/module_loader.zig#L1574-L1585 https://github.com/oven-sh/bun/blob/22818e6806cfff66804a74bdbd71f90d195f8183/src/fs.zig#L1608-L1615
They go through are a special parser
https://github.com/oven-sh/bun/blob/22818e6806cfff66804a74bdbd71f90d195f8183/src/json_parser.zig#L885
and are rewritten as modules, thus producing a syntax error in this case:
```TS
var key_with_hyphen = !0

export {
    key_with_hyphen as key-with-hyphen
};

export default { "key-with-hyphen": key_with_hyphen };
```
@Jarred-Sumner why are these files rewritten like this ? Is it for JSON5 compatibility ?

**Comment by DontBreakAlex** [comment]
According to MDN [quoting the alias should work](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export), but I get the same error rewriting it like this:
```JS
var key_with_hyphen = !0

export {
    key_with_hyphen as "key-with-hyphen"
};

export default { "key-with-hyphen": key_with_hyphen };
```
Edit: I'm not sure why this is not working, according WebKit's Bugzilla this [has been supported for a while](https://bugs.webkit.org/show_bug.cgi?id=217576)...
