### ISSUE TITLE
Bug: --hot is not exiting the previous process properly

### ISSUE THREAD

**Issue by libersoft-org** [oven-sh/bun#7315]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 6.1.0-13-amd64 x86_64 unknown (Debain 12)

### What steps can reproduce the bug?

Saved some source code file which made Bun with --hot parameter to reload

### What is the expected behavior?

The previous process (before saving) willl be terminated.

### What do you see instead?

Old connections with MySQL (from previous process) is not terminated, terminal shows some messages twice etc.

**Comment by HoloPanio** [comment]
Instead of using `--hot` try using `--watch`.  The thing with hot reloading is that it doesn't completely restart your process, so if you have any active connections, they will not be terminated when reloading whereas `--watch` it will hard restart the application so that all active connections will properly be terminated (Including databases, event listeners, etc.).  You can read more about it [here](https://bun.sh/docs/runtime/hot).

**Comment by libersoft-org** [comment]
> Instead of using `--hot` try using `--watch`. The thing with hot reloading is that it doesn't completely restart your process, so if you have any active connections, they will not be terminated when reloading whereas `--watch` it will hard restart the application so that all active connections will properly be terminated (Including databases, event listeners, etc.). You can read more about it [here](https://bun.sh/docs/runtime/hot).

Works great, my bad, thank you!
