### ISSUE TITLE
Disabling strict mode when running bun

### ISSUE THREAD

**Issue by marcocondrache** [oven-sh/bun#7381]
### What is the problem this feature would solve?

I'm working on a project for a company that doesn't use strict mode. This doesn't allow me to use bun to compile and run the project as it finds errors that i cannot fix and touch. It would be very helpful to run bun on non-strict projects in order to take advantage of all the features that bun provides.

### What is the feature you are proposing to solve the problem?

Add an option like "--no-strict" in order to disable the strict mode when running or building with bun.

### What alternatives have you considered?

I've tried to explicitly disable the strict mode in the tsconfig but nothing changed.

**Comment by notramo** [comment]
Please don't add legacy features to Bun. I understand that it can be quite frustrating not being able to use Bun features on a legacy project, but legacy projects could go with `pnpm` and `node`.
While it would be fun to support all JS features, Bun isn't even usable for modern projects as it lacks modern features too. Until all modern features are implemented, I would not recommend adding legacy features.

**Comment by marcocondrache** [comment]
Then please don't advertise bun as a drop-in replacement for Node.js. 
If the goal of bun is to be a full alternative to Node then it should support non-legacy and legacy projects. I also think that disabling strict mode wouldn't require a lot of changes but at the same time you would expand the usability platform of bun.

**Comment by Jarred-Sumner** [comment]
@MarcoMihaiCondrache If the entry point is CommonJS, it will use sloppy mode. If the entry point is ESM or ambiguous, it will use strict mode. 

To enable strict mode by default in your project, please set `"type": "commonjs"` in package.json. 

Future versions of Node.js may auto-detect whether the entry point is CommonJS or ESM and change behavior accordingly, so this issue may impact your project in a future Node.js upgrade as well.

We aren't going to change the default for all projects from strict mode to sloppy mode, but hopefully adding `"type": "commonjs"` will be a suitable workaround in the meantime. I'm closing this as not planned not due to lack of caring about the issue you're facing, but because we are unlikely to change the default from strict mode/esm to sloppy mode at this point.
