### ISSUE TITLE
SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries

### ISSUE THREAD

**Issue by stevehollaar** [oven-sh/bun#74]
Hello!
I'm hitting the following while trying bun on an existing nextjs project. Any suggestions on how to debug?
```
bun
[0.12ms] "node_modules.bun" - 1933 modules, 130 packages
[0.03ms] ".env.development"
[3.00ms] Bun!! v0.0.52


  Link: http://localhost:3001


[0.06ms] "node_modules.server.bun" - 1938 modules, 131 packages
[0.00ms] ".env.development"
[91.62ms] Next.js ready! (powered by Bun)
75 |         console.error(err);
76 |     });
77 |     addEventListener("fetch", async (event) => {
78 |       var route = Bun.match(event);
79 |
80 |       const PageNamespace = await import(route.filePath);
                                      ^
 SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.
      at (anonymous) (http://localhost:3001/blob:node_modules.server.bun:80:34)
```

**Comment by Jarred-Sumner** [comment]
This is most likely a CommonJS <> ESM interop issue. 

If you use `require` or `module.exports` in your code along with `export * from` it has issues with HMR because CommonJS is exported as `export default commonJS(() => codeInhere)`. This is Bun's fault and needs to be fixed, but I haven't been able to prioritize it yet.

For now, try replacing usages of `export * from` that point to a CommonJS module with an import and re-export manually, like this:
```js
// Instead of this
export * from 'lodash';

// Try this
import {camelCase} from 'lodash';

export {camelCase};
```

You can find where `export * from` is used by grepping for it:

```bash
git grep "export \* from"
```

This only applies to app code. Running `bun bun --use next` bundles dependencies and `export * from` should work great in any node_modules you're using.

#### If that doesn't work

Try starting Bun without SSR/pre-rendering enabled:

```bash
bun --disable-bun.js
```

This disables Bun's JavaScript runtime environment from trying to render your Next.js pages into HTML. It will make it a little slower to show pages on start and mean any code in `getStaticProps` or `getServerSideProps` won't be executed.

**Comment by stevehollaar** [comment]
Thanks for the help!
Unfortunately, I don't have any CommonJS usage in my next.js code. I replaced all usages of `export *` with `export { foo }`, just to see, however I get the same behaviour.

`bun --disable-bun.js` also misbehaves, giving me a blank screen with no feedback in the browser or console.
I suspect there must be something in my dependencies that bun dislikes, as a clean project works just fine

**Comment by The-Code-Monkey** [comment]
@Jarred-Sumner I seem to be hitting this issue but not during build, only when running bun test

**Comment by morgante** [comment]
I'm also encountering this during tests.

**Comment by valgaze** [comment]
Could also be related **[type-only import/exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)**, ex

Error ❌

```ts
export { SurveyQuestion, SurveyQuestionType } from "./cards";
```

vs Working ✅

```ts
export type { SurveyQuestion, SurveyQuestionType } from "./cards";
```

**Comment by ChuckJonas** [comment]
I just ran into this with bun and the above comment fixed it.  In my case  I have to split my `exports` out to two different statements, which is a bit annoying:

```ts
export { AssistantDefinition, definition } from "./definition";
//ERR: SyntaxError: Indirectly exported binding name 'AssistantDefinition' is not found.
```

```ts
export { definition } from "./definition";
export type { AssistantDefinition } from "./definition";
```

**Comment by plepisnew** [comment]
> Could also be related **[type-only import/exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)**, ex
> 
> Error ❌
> 
> ```ts
> export { SurveyQuestion, SurveyQuestionType } from "./cards";
> ```
> 
> vs Working ✅
> 
> ```ts
> export type { SurveyQuestion, SurveyQuestionType } from "./cards";
> ```

You are an angel
