### ISSUE TITLE
Cannot find package Astro:content when using vitest in AstroJS

### ISSUE THREAD

**Issue by tobyhage** [oven-sh/bun#7714]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

- Install AstroJS and vitest
- in package.json add in scripts: "test": "vitest",
- make this test

`
import { test } from 'vitest';
import { getEntry } from 'astro:content';

test('getEntryBySlug will fail', async () => {
  await getEntry('post', 'example').then((file) => {
    console.log('File', file);
  });
});
`

and run: "bun test"

### What is the expected behavior?

Test is running correct

### What do you see instead?

src/tests/getEntryBySlug.test.ts:
error: Cannot find package "astro:content" from src/tests/getEntryBySlug.test.ts"

### Additional information

versions astro and vitest

astro@4.0.5
vitest@1.0.4

**Comment by Jarred-Sumner** [comment]
When you run `bun test` using Bun, it uses `bun:test`. `bun:test` rewrites `"vitest"` imports to `bun:test` automatically. This often works because `bun:test` is very compatible with jest & vitest. In this case, it doesn't because `bun:test` does not support reading Vite configuration files currently.

To use vitest, run `bun run test` instead.
