### ISSUE TITLE
Bun build error: No matching export in "node:buffer" for import "Buffer"

### ISSUE THREAD

**Issue by marshallr12** [oven-sh/bun#7935]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Linux 6.4.0-1mx-ahs-amd64 x86_64 unknown

### What steps can reproduce the bug?

Add a dependency that has `import { Buffer } from 'buffer'`;  then try to build index.ts:

- `bun init`
- `bun add @solana/web3js`
- `bun install`
- Add 2 lines to index.ts:

```
import { PublicKey } from '@solana/web3.js'
let key = new PublicKey("xxxxx");
```

Then run:

`bun build ./index.ts --outfile ./dist/bundle.ts`

### What is the expected behavior?

`/dist/bundle.ts` should be produced.

### What do you see instead?

```
1 | import { Buffer } from 'buffer';
             ^
error: No matching export in "node:buffer" for import "Buffer"
    at /bun-test/node_modules/@solana/web3.js/lib/index.browser.esm.js:1:10
󰋜 /src/solana/js/bun-test via v1.0.20 via v18.19.0 
```

### Additional information

Since this is a 3rd party API, is there a configuration that would point Bun to its own implementation of Buffer rather than node:buffer?

**Comment by Jarred-Sumner** [comment]
you don’t need to build ahead of time to run code in bun. It can help reduce memory usage, but otherwise you can directly run the code 

if you still want to build ahead of time, set `target` to `bun`. By default, `bun build` builds for `browser` and the error you’re running into is in the `node:buffer` polyfill. 

To build for bun

```
bun build ./index.ts --outfile ./dist/bundle.ts --target=bun
```

Either solution, running the file directly or setting target should fix this but please leave a comment if it doesn’t

**Comment by marshallr12** [comment]
Thanks! Using --target=bun worked for me. The purpose of the build step was to create a package for npm publish. If someone subsequently adds the published package as a dependency for their nodejs web project, would you expect it to still work properly in the browser page?
