### ISSUE TITLE
BullMQ fails to build with Bun

### ISSUE THREAD

**Issue by knajjars** [oven-sh/bun#8086]
### What version of Bun is running?

v1.0.22

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. install BullMQ
2. Add a bull queue and dummy worker that console.logs in the `index.ts`
3. build the index.ts using `bun build --target bun --outdir build`
4. run `bun build/index.ts`

error 
```
function getPkgJsonDir() {
      for (const modPath of module.paths || []) {
                              ^
ReferenceError: Can't find variable: module
```

**Comment by MaikuMori** [comment]
Using `--compile` I get:

```
ReferenceError: Can't find variable: module_script_loader
      at getPkgJsonDir (/$bunfs/root/cli:46442:25)
      at new ScriptLoader (/$bunfs/root/cli:46509:21)
      at /$bunfs/root/cli:46722:20
```

**Comment by Curetix** [comment]
I'm getting the same error from a bundled BullMQ server script. Running the TS file directly works fine, but building (with target bun) and then running it throws `ReferenceError: Can't find variable: module_script_loader`.

Seems to be caused by [this function](https://github.com/taskforcesh/bullmq/blob/83e8a611b1a758354426244739bcc950e658e1f3/src/commands/script-loader.ts#L499-L509), which gets bundled to this:

```js
var getPkgJsonDir = function() {
  for (const modPath of module_script_loader.paths || []) {
    try {
      const prospectivePkgJsonDir = path3.dirname(modPath);
      fs2.accessSync(modPath, fs2.constants.F_OK);
      return prospectivePkgJsonDir;
    } catch (e) {
    }
  }
  return "";
};
```

**Comment by mrsum** [comment]
Same error

**Comment by evmd** [comment]
Any news on this ?

**Comment by rvanderfeer** [comment]
I ran into this error too, the BullMQ method that @Curetix mentions seems to hold a clue; the method's comment references a discussion on [stack overflow](https://stackoverflow.com/questions/10265798/determine-project-root-from-a-running-node-js-application/18721515#18721515) which states;

> Node publishes all the module search paths to module.paths. We can traverse these and pick the first one that resolves.

It would appear that Bun follows this behavior only when running.
When building/compiling the 'module' global seems to be replaced somehow, which suggests to me it may not be recognized or set as a global.

A simple test file confirms this;

```ts
// index.ts
console.log(module.paths);
```

When launched with `bun run` this will produce an array output.
When built via `bun build --target bun --outfile out.js index.ts` and subsequently run via `bun run out.js` this produces `undefined`.

@knajjars I suggest you change the title of your bug report so to something like `module.paths not set when using bun build` - surely there will be modules other than BullMQ suffering from this bug.

_EDIT: There seems to be a bit more to it; apparently this is caused by BullMQ using the `module.paths` to dynamically load Lua files onto the Redis instance, which would hide these files from the Bun bundler. These would need to be turned into assets by the bundler somehow._

**Comment by Daniel-Manea** [comment]
Hey! Same problem here. Did anyone found a solution?

**Comment by zenozaga** [comment]
Hello everyone! I encountered the same problem, and I'm still not sure if this is the best solution. However, this is what worked for me using Bun with SandboxedJob, after reviewing the source code.


```
// worker.ts

import { ParentCommand, type SandboxedJob } from "bullmq";

export default async function(job: SandboxedJob) {
    console.log(`Job ${job.name}:${job.id} started with data`, job.data);
    
    exit({
        state: "sent"
    });
}

function exit<T extends any>(data: T, success: boolean = true) {
    process.send?.({
        cmd: success ? ParentCommand.Completed : ParentCommand.Failed,
        data: data
    });

    process.exit(0);
}
```

This way, the jobs are no longer marked as failed. But again, I'm not sure if it's the best solution.

**Comment by atbe** [comment]
Was this issue actually resolved?

**Comment by Pyakz** [comment]
is this resolved? 
still facing this issue
<img width="672" alt="Image" src="https://github.com/user-attachments/assets/e58c8145-67c1-42b1-87f3-c0f8fabb12eb" />

**Comment by Pyakz** [comment]
were you able to solve it guys?


i dont really want to start from scratch again and go back to node
