### ISSUE TITLE
`eval` not hoisting `var` causing `ReferenceError: Can't find variable:`

### ISSUE THREAD

**Issue by AntonioGargaro** [oven-sh/bun#8123]
### What version of Bun is running?

1.0.19+906f86d6f

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

See sample script

```typescript
console.log("Hello via Bun@" + Bun.version);

declare const env: { a?: number }

eval(`var env = {}`)
eval(`env.a = 1`)

console.log(`env is`, { env })
```

### What is the expected behavior?

Console log is outputted:

> Hello via Bun@1.0.19
env is {
  env: {
    a: 1,
  },
}

### What do you see instead?

> Hello via Bun@1.0.19
1 | console.log("Hello via Bun@" + Bun.version);
2 |
3 | declare const env: { a?: number }
4 |
5 | eval(`var env = {}`)
6 | eval(`env.a = 1`)
    ^
ReferenceError: Can't find variable: env
      at /Users/antoniogargaro/temp/bun-eval/index.ts:6:1

### Additional information

Version `v1.0.18` works with the above code sample, but versions greater than v1.0.18 all seem to throw that error.

**Comment by paperclover** [comment]
ES modules are strict mode, which do not allow eval to work like this. If you run an ES Module in node:

<img width="528" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/7e3475e5-45a6-4e24-bf32-6bf01a374aec">

If you add `module.exports` into your module, it will force the runtime to make this a commonjs module, which will not have this issue.

```ts
eval(`var env = {}`);
eval(`env.a = 1`);
console.log(`env is`, { env })
module.exports = {};
```

The reason this worked before is due to a transpiler change in #7693. `eval` in all cases used to be rewritten to `(0, eval)()`, which would execute in the global scope.

See this example:

```ts
eval(`var a = 1`);
{
  let a = 2;
  console.log(eval('a'))
}
```

Bun 1.0.18 prints 1, Bun latest (and node in either cjs or mjs) correctly prints 2.

And again, `eval` in my opinion is a bad practice that almost always can be avoided.

**Comment by AntonioGargaro** [comment]
Thanks for the explanation, I learned something new.
