### ISSUE TITLE
"bun run <filename>.ts" not running

### ISSUE THREAD

**Issue by LucasCoderTV** [oven-sh/bun#821]
### Version

0.1.4

### Platform

Microsoft Windows NT 10.0.19043.0 x64

### What steps will reproduce the bug?

1. Write a simple app. It can be anything. I used:
`
export default  {
    port:  3000,
    fetch(request:  Request)  {
        return new  Response('Bun Is Fun!!');
    }
}
`

2. Run `bun run <filename>.ts`
3. Have it not run.

### How often does it reproduce? Is there a required condition?

This is happening to me all the time!

anything  that isnt `bun -v` will not work

### What is the expected behavior?

It should run

### What do you see instead?

Nothing. No Command Output.

![image](https://user-images.githubusercontent.com/109552736/180322033-c50aa109-6d6a-41ea-a09a-6cdbe35764e8.png)
See?

### Additional information

I am using WSL 1, so maybe that's why...
I have refreshed my console also, because most people say

> Just refresh your bash!
> -Said Everyone on stack overflow

**Comment by Jarred-Sumner** [comment]
Did you try going to localhost:3000? There is no logger by default

**Comment by LucasCoderTV** [comment]
I did, all it says is:
> **Hmmm… can't reach this page: localhost refused to connect.**

**Comment by mryechkin** [comment]
I'm facing the same issue. Nothing comes up, and `localhost:3000` is just timing out

**Comment by LucasCoderTV** [comment]
> I'm facing the same issue. Nothing comes up, and `localhost:3000` is just timing out

Bun is in beta/alpha, so there are alot  of bugs.

**Comment by JoltCode** [comment]
I've just attempted to reproduce this, but I'm not encountering the bug mentioned; it works fine for me.

**Comment by copongcopong** [comment]
reproduced issue on Ubuntu 22.04 LTS 
bun version: 0.1.5
```
[0.04ms] ".env.local"
12 |       if(typeof entryNamespace?.default?.fetch === 'function')  {
13 |         Bun.serve(entryNamespace.default);
14 |       }
15 |    }, reportError);
16 | } else if (typeof entryNamespace?.default?.fetch === 'function') {
17 |    Bun.serve(entryNamespace.default);
       ^
Error: Failed to start server
      at bun:main:17:3

```
works on older version `0.1.2`

**Comment by sewe75** [comment]
WSL 1 is just an emulation that lacks a native kernel.  
Any reason not to upgrade to WSL 2?  
```wsl --set-version <distro name> 2```  
Regarding the docs you can even downgrade v2 to v1 that way: https://docs.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2  
To set the default WSL version to 2 run ```wsl --set-default-version 2```  
  
If you are in need of running an instance in v1 you can clone your running one (after upgrading to v2) and set the clone to v1 after importing it: https://superuser.com/questions/1589877/how-do-you-clone-a-wsl-distro  

But: Just avoid using WSL 1 unless there are reasons to use a (partially implemented, discontinued) emulation instead of a native kernel.

**Comment by LucasCoderTV** [comment]
ok this is probably why
> works on older version `0.1.2`

**Comment by maor-benami** [comment]
For me it was another server running on port 3000.
Error message could be better...
