### ISSUE TITLE
reached unreachable code

### ISSUE THREAD

**Issue by Zer0bytte** [oven-sh/bun#8256]
### What version of Bun is running?

latest version

### What platform is your computer?

Windows x64

### What steps can reproduce the bug?

![image](https://github.com/oven-sh/bun/assets/85482481/18f7a7e0-5640-47c9-8e81-fd9ce667afb8)
When trying to open listening url bun server crash

**Comment by paperclover** [comment]
impossible to tell exactly what the issue is from just this alone. i cannot reproduce this on the windows device i use for dev.

I think very long time ago I noticed that specifically on a baseline build that bun would crash during a request.

Once #8606 is merged, can you re-run this code and see if

1. it still happens
2. verify this is specific to baseline confirming my guess

**Comment by paperclover** [comment]
close as i was never unable to reproduce this and no followup has been recieved
