### ISSUE TITLE
Segfault with built in modules + bun-utilities

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#840]
### Version

0.1.5

### Platform

`Linux paperback 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What steps will reproduce the bug?

`a.ts`
```ts
import './b';
import { exec } from 'bun-utilities';
exec;
console.log(':)');
```
`b.ts`
```ts
import fs from 'fs';
fs; // prevent tree-shaking
```

The above code fails with `SegmentationFault at 24` on bun 0.1.4 and 0.1.5

### How often does it reproduce? Is there a required condition?

Reproduces every time, so long the `b` import comes before the `bun-utilities` import. reversing them fixes it. I would give a reproduction without bun-utilities but i'm too tired to figure out how that one works.

### Additional information

[on discord me and Jarred found out this:](https://discord.com/channels/876711213126520882/887787428973281300/1000292217337938011) (punctuation and formatting modified)

> **Jarred**: one question is, what happens if you do `await import("node:fs");` instead of static import. basically i'm wondering if this is a bug in the require() implementation
> **dave**: it works
> **Jarred**: `import fs from 'node:fs'` transforms into
`import.meta.require("node:fs")`, which does a synchronous ESM import; but maybe synchronous ESM import is bugged when there is already an import in progress
> **dave**: its looks like something about imports from not the entry file. im unsure. but again its really weird because import order matters for this. importing `bun-utilities` before `fs` doesnt error.
> **Jarred**: hm. yeah it sounds very much like a require bug, which sucks because it's hardcoded (all the builtins use `require()`)

**Comment by theoparis** [comment]
I'm encountering the same issue, but with `bun-utilities` and `@paperdave/logger`. It is fixed if i switch the import order here.

```ts
import log, { injectLogger } from "@paperdave/logger";
import { exec } from "bun-utilities";
```

**Comment by paperclover** [comment]
> I'm encountering the same issue, but with `bun-utilities` and `@paperdave/logger`. It is fixed if i switch the import order here.
> 
> ```ts
> import log, { injectLogger } from "@paperdave/logger";
> import { exec } from "bun-utilities";
> ```

this is because my logger depends on `node:fs` (I use `writeSync(0, data)`. we should test if it's specifically fs that causes this, and what inside of bun-utilities causes it (is it NAPI in general or what)

**Comment by zhuzilin** [comment]
This segfault doesn't seem like to happen in v0.1.7. Could you give it another try?

**Comment by paperclover** [comment]
> This segfault doesn't seem like to happen in v0.1.7. Could you give it another try?

I can reproduce it with the initial reproduction at the top of the issue. Ubuntu 22, x64.

Reproduces on bun 0.1.7 release, and bun canary august 8th 2022.

**Comment by Jarred-Sumner** [comment]
@zhuzilin  if you or anyone else wants to take a look 

The bug is somewhere here: 

https://github.com/oven-sh/bun/blob/ceb78d2bb9203fb622dc467b9e58dab8adff52d4/src/bun.js/builtins/js/ImportMetaObject.js#L67-L196

To re-generate the builtins (so that JS changes are reflected): 

```bash
make clean-bindings && make builtins && make bindings -j$(ncpu) && make bun-link-lld-debug
```

If you run into an error about missing a script, copy [this file](https://github.com/oven-sh/WebKit/blob/main/Source/JavaScriptCore/Scripts/generate-js-builtins.py). It will be added into new Linux webkit builds but I forgot to put it in there in the latest build

one possible mitigation for now is to not transform top-level import statements to `import.meta.require()`, but it would be better to just fix this

A longer term fix  is to update WebKit and use the new `SyntheticModuleRecord`. Then, some bindings code to make it so the CommonJS transform automatically registers

You can see the new SyntheticModuleRecord type in https://github.com/WebKit/WebKit/pull/3071

**Comment by zhuzilin** [comment]
This should have been fixed by the above pr. Please reopen if the bug still exists.
