### ISSUE TITLE
sveltekit is very slow in bun when running with `@sveltejs/adapter-node`

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8637]
### What is the problem this feature would solve?

a full reproduction with details: https://github.com/huseeiin/bun-svelte-adapter-node
benchmarks done with `oha`:
`oha -n 10000 http://localhost:3000`
about 2800 req/s

### What is the feature you are proposing to solve the problem?

either the bun or svelte team to build a stable bun adapter for sveltekit since its very hard to build a fully-fledged production-ready one especially that the maintainer of `svelte-adapter-bun` is one person.

### What alternatives have you considered?

i built a small bun adapter in the repo above. it doesn't work for all needs but it gives hope :smile:

**Comment by Jarred-Sumner** [comment]
from the readme:

> adapter-node with bun: ~2800 req/s
> adapter-node with node: ~1400 req/s

Considering we're 2x faster than node here, it sounds likely this is something for SvelteKit to investigate rather than for us to take action on (which would benefit in all runtimes). I think it's worth looking at in the future but I don't think this is something we're likely to take action on soon.
