### ISSUE TITLE
windows: stopping a http server keeps process alive forever

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#8742]
### What steps can reproduce the bug?

```ts
import { serve } from "bun";
const server = serve({
  fetch() {
    return new Response("Hello world");
  },
  port: 0,
});
const res = await fetch(`http://${server.hostname}:${server.port}`);
if (res.status !== 200) throw "fail from server";
if ((await res.text()) !== "Hello world") throw "fail from server";
server.stop();
console.log("ok");
```

**Comment by ghiscoding** [comment]
I'm not sure if it's related or not but this reminds me of Lerna [issue](https://github.com/lerna/lerna/issues/2841) that was only observed on Windows and was caused by a child process missing option and just adding `windowsHide: false` to `execa` `child_process` (in this [PR](https://github.com/lerna/lerna/pull/3156)) fixed the issue.
