### ISSUE TITLE
Docker RUN bun install

### ISSUE THREAD

**Issue by TrackZone1** [oven-sh/bun#8749]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.1.0-15-cloud-amd64 x86_64 unknown

### What steps can reproduce the bug?

```
FROM node:latest
FROM oven/bun:latest as base

WORKDIR /usr/src/app

COPY package*.json ./

RUN bun install

COPY . .

EXPOSE 3000

ENTRYPOINT [ "bun", "run", "index.js" ]
```

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/48413426/0b98f246-1102-4e2c-b560-fae84030bcfb)
Before Bun 1.26 I had no problems at all

**Comment by cupofjoakim** [comment]
I tried replicating this with a base example on my machine, and I can not. Granted the only dependency at this point is `bun-types` but the `FailedToOpenSocket` error you're receiving should have happened on my end too if it was an issue in bun itself.

My repo that fails to replicate your issue is here: https://github.com/cupofjoakim/bun-docker

This is the bun install output from `docker build .`:

```
Step 4/5 : RUN bun install
 ---> Running in 38233900acf9
bun install v1.0.26 (c75e768a)
 Resolving dependencies
 Resolved, downloaded and extracted [20]
 Saved lockfile

 + bun-types@1.0.26

 5 packages installed [1.81s]
Removing intermediate container 38233900acf9
```

I guess your issue is either on docker level or on network level.

**Comment by TrackZone1** [comment]
> I tried replicating this with a base example on my machine, and I can not. Granted the only dependency at this point is `bun-types` but the `FailedToOpenSocket` error you're receiving should have happened on my end too if it was an issue in bun itself.
> 
> My repo that fails to replicate your issue is here: https://github.com/cupofjoakim/bun-docker
> 
> This is the bun install output from `docker build .`:
> 
> ```
> Step 4/5 : RUN bun install
>  ---> Running in 38233900acf9
> bun install v1.0.26 (c75e768a)
>  Resolving dependencies
>  Resolved, downloaded and extracted [20]
>  Saved lockfile
> 
>  + bun-types@1.0.26
> 
>  5 packages installed [1.81s]
> Removing intermediate container 38233900acf9
> ```
> 
> I guess your issue is either on docker level or on network level.

Thanks for the hint, I have clear my iptables rules and forgot to restart docker.
