### ISSUE TITLE
Can't terminate bun running in `--watch` mode with Ctrl+C

### ISSUE THREAD

**Issue by gvilums** [oven-sh/bun#8788]
### What version of Bun is running?

1.0.26-debug+2f8f77eeb

### What platform is your computer?

Linux - Ubuntu

### What steps can reproduce the bug?

```
Bun.serve({
  fetch() {
    return new Response("Hello world");
  },
});
console.log('listen');
```

run with `bun --watch`, then attempt to stop with Ctrl+C

### What is the expected behavior?

Bun stops

### What do you see instead?

Nothing happens

### Additional information

This may be the root cause of #8786: People will attempt to end the bun process by terminating the shell, but this leaves bun running in the background, potentially blocking ports.

**Comment by ronitkrshah** [comment]
I'm facing the same issue in my Arch Linux

```bash
bun --watch index.ts
```
`CTRL+C` doesn't stop watch mode

Kernel Version : 6.6.14-2-lts
Bun Version: 1.0.26

**Comment by gvilums** [comment]
PR to fix this: #8792

**Comment by bcherny** [comment]
This seems to have regressed again as of 1.1.42

**Comment by csprance** [comment]
I'm experiencing this same behavior again on canary 1.2.5

**Comment by shm0x** [comment]
Same on released 1.2.5

**Comment by LeHyperion** [comment]
Experiencing the same issue with `--hot` hot reloading in version 1.2.5.

**Comment by csprance** [comment]
Something I've noticed is when I install bun with npm or yarn I see that behavior described here. 

However if I install it with PowerShell this isn't the case. 

I've also noticed that on windows using bun to run workspace scripts it has this same issue where it doesn't end the process correctly. 

So my workaround there is to have the script CD into the folder and run bun instead of using bun to run bun with filters.
