### ISSUE TITLE
Clear message needed if tsconfig.json is missing

### ISSUE THREAD

**Issue by alexkuz** [oven-sh/bun#90]
If `tsconfig.json` is missing in project, bun reports an error that is not very helpful:
```
error: ModuleNotFound
```
Bun should report about config specifically or maybe use some default settings instead.

**Comment by Jarred-Sumner** [comment]
There should never be a situation where a missing tsconfig.json causes an error

Can you give a little more info?

**Comment by alexkuz** [comment]
Sure:
```sh
mkdir test && cd test

yarn init

touch index.tsx

bun bun index.tsx     # error: ModuleNotFound

touch tsconfig.json

bun bun index.tsx     # error: ModuleNotFound

echo '{"compilerOptions":{"baseUrl": "."}}' > tsconfig.json

bun bun index.tsx     # success
```
Seems like an issue is in missing `baseUrl`

**Comment by Jarred-Sumner** [comment]
Oh, this is actually because `bun bun` interprets the input path as a package path

so it thinks you're doing this inside of `test`:

```js
import foo from 'index.tsx';
```

This is close to the behavior of webpack

So when you set a `baseUrl`, you're making it possible to import `index.tsx` from the project root without a `./`

But, it should be smarter here and realize that there is no package called "index.tsx" but there is a project-relative path

**Comment by Jarred-Sumner** [comment]
This specific message was slightly improved in https://github.com/Jarred-Sumner/bun/commit/11e3faa8da57748c98592f4eeb32ecdc72620857

**Comment by alexkuz** [comment]
Ah, got it, I never used webpack as CLI actually
BTW it says `Did you mean './index.tsx'?` which is very helpful.
That's maybe actually better than trying to figure out implicitly what it means.
