### ISSUE TITLE
`ag` runs without stdin with Bun shell

### ISSUE THREAD

**Issue by gaute** [oven-sh/bun#9510]
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

I use `ag`, a faster alternative to `grep`, in a Bun shell command that pipes stdout from one command to ag´s stdin. It worked fine up to Bun 1.0.31, but fails in Bun 1.0.32 and 1.0.33.

In an empty directory, make these two files:

catfile.txt
```
cat cat cat
cat cat
cat
```

bunbug.test.js
```
import {expect, test} from "bun:test";
import {$} from 'bun';

test('grep and ag produces same output', async () => {
  const grepOutput = await $`cat catfile.txt | grep 'cat'`.text();
  const agOutput = await $`cat catfile.txt | ag 'cat'`.text();

  expect(agOutput).toEqual(grepOutput);
});
```

### What is the expected behavior?

In the session below, I first run the commands `cat catfile.txt | grep 'cat'` and `cat catfile.txt | ag 'cat'`. They do the same thing, as they should.

Then, I install Bun 1.0.31, and run the test that confirms the output is equal.

```
$ cat catfile.txt | grep 'cat'
cat cat cat cat
cat cat
cat
$ cat catfile.txt | ag 'cat'
cat cat cat cat
cat cat
cat
$ curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.31"
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
Run 'bun --help' to get started
$ ~/.bun/bin/bun test
bun test v1.0.31 (e2567512)

bunbug.test.js:
✓ grep and ag produces same output [45.90ms]

 1 pass
 0 fail
 1 expect() calls
Ran 1 tests across 1 files. [63.00ms]
```

### What do you see instead?

When I install Bun 1.0.32, the test fails. It's now as if `ag` runs without stdin, it finds matches in both files.

```
$ curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.32"
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
Run 'bun --help' to get started
$ ~/.bun/bin/bun test
bun test v1.0.32 (5fec71bd)

bunbug.test.js:
3 | 
4 | test('grep and ag produces same output', async () => {
5 |   const grepOutput = await $`cat catfile.txt | grep 'cat'`.text();
6 |   const agOutput = await $`cat catfile.txt | ag 'cat'`.text();
7 | 
8 |   expect(agOutput).toEqual(grepOutput);
      ^
error: expect(received).toEqual(expected)

Expected: "cat cat cat cat\ncat cat\ncat\n"
Received: "catfile.txt:1:cat cat cat cat\ncatfile.txt:2:cat cat\ncatfile.txt:3:cat\nbunbug.test.js:5:  const grepOutput = await $`cat catfile.txt | grep 'cat'`.text();\nbunbug.test.js:6:  const agOutput = await $`cat catfile.txt | ag 'cat'`.text();\n"

      at /Users/gaute/Arbeid/Test/bunbug/bunbug.test.js:8:3
✗ grep and ag produces same output [60.20ms]

 0 pass
 1 fail
 1 expect() calls
Ran 1 tests across 1 files. [88.00ms]
```

The same happens in 1.0.33.

**Comment by Jarred-Sumner** [comment]
This can be reproduced outside of JavaScript and directly in the bun shell via running a `.bun.sh` file:

- [bun-v1.0.30-systrace.log](https://github.com/oven-sh/bun/files/14648669/bun-v1.0.30-systrace.log)
- [bun-v1.0.33-systrace.log](https://github.com/oven-sh/bun/files/14648671/bun-v1.0.33-systrace.log)

<img width="244" alt="image" src="https://github.com/oven-sh/bun/assets/709451/88cc7419-945b-4884-a909-ba6fd6bfddf2">

@zackradisic are we now inheriting stdin instead of creating a pipe? When `.text()` or similar is used, we should not inherit stdin

**Comment by zackradisic** [comment]
Closing because this is actually caused by `ag` not supporting sockets for stdin (see [this](https://github.com/ggreer/the_silver_searcher/issues/1538)). Sockets are used in pipelines to ensure IO is not blocking without breaking process behavior by setting O_NONBLOCK

In this particular case, you could instead redirect `catfile.txt` to `ag` like so: `ag 'cat' < catfile.txt`. This will not use sockets and rather just pass a file descriptor pointing to the catfile.txt file
