### ISSUE TITLE
NODE_ENV=production in package.json scripts no longer reads from .env.production

### ISSUE THREAD

**Issue by linusback** [oven-sh/bun#9635]
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Linux 6.5.0-25-generic x86_64 unknown

### What steps can reproduce the bug?

Create a new bun project.
`bun init`

Change package.json to:
```
{
  "name": "bun-env-issue",
  "module": "index.js",
  "type": "module",
  "scripts": {
    "dev": "NODE_ENV=development bun index.js",
    "prod": "NODE_ENV=production bun index.js"
  },
  "devDependencies": {
    "@types/bun": "latest"
  }
}
```

Chang index.js to
```
console.log("NODE_ENV:", import.meta.env.NODE_ENV)
console.log("ENV_FILE_NAME:", import.meta.env.ENV_FILE_NAME)
```

create .env files 
.env
```
ENV_FILE_NAME=.env
```

.env.development
```
ENV_FILE_NAME=.env.development
```

.env.production
```
ENV_FILE_NAME=.env.production
```

Run 
`bun run prod`

### What is the expected behavior?

```
$ NODE_ENV=production bun index.js
NODE_ENV: production
ENV_FILE_NAME: .env.production
```

### What do you see instead?

```
$ NODE_ENV=production bun index.js
NODE_ENV: production
ENV_FILE_NAME: .env.development
```

### Additional information

Earlier versions of bun would choose .env.production if NODE_ENV=production was specified inside of scripts in package.json. 
To get the previous behavior in v1.0.35 you need to specify NODE_ENV=production outside of package.json.

This is problematic since a common pattern is to put the different modes inside of package.json scripts. And it breaks previous behaviour.

Recreated the problem including the previous behavior in the following repo where 2 docker images exists one working (bun version 1.0.33, and one broken 1.0.35): [https://github.com/linusback/bun-env-issue](https://github.com/linusback/bun-env-issue)

**Comment by paperclover** [comment]
this is interesting. in previous versions of bun it seems that the env file was not loaded. to show this, i can add a third script that just prints ENV_FILE_NAME. when run in older versions it is not set, but now it is set, indicating that we load it.

<img width="720" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/8b0b7a79-4ac3-4ee3-90e4-c03a464c340a">

going back, it seems there was no case `bun run` used to load `.env` and friends.

<img width="547" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/53117653-b2cb-4fa5-9386-61fef4e619fd">

the reason this is problematic is the (intentional) priority of env variables is:

- process passed variables
- `.env` file variables
- some defaults by bun (`NODE_ENV=development` when loading a `.env` file)

what you are experiencing is the following happens:

1. `bun run script` is run without environment variables (call this process A)
2. `bun run script` loads `.env.development` in (process A)
3. process A spawns a shell that executes `NODE_ENV=production bun index.js`.
4. `bun index.js` is spawned with `.env.development` loaded BUT `NODE_ENV` is now set to `production` (call this process B)
5. Process B proceeds to load `.env.production`, and it correctly applies the rule above about prioritizing process-passed variables
6. all of the variables that came from .env.development take priority over the newly loaded `.env.production`

not fun. it is very confusing to see `NODE_ENV=production` to load dev env without any sign of `NODE_ENV=DEVELOPMENT`

in my opinion, there is not a good use case for the script runner to load environment variables (bullet point 2 above).

- it is now VERY easy to load undesired env files, as development variables are loaded by default.
- regardless, we are loading environment variables twice, which is a waste. the only case environment variables will never be loaded is when the js script runs in `node` or you invoke a binary like esbuild. i argue this is not an issue as other script runners behave this way, `node` will not be used in the future when `--bun` is the default, and web frameworks like vite do their own env loading regardless.
- the previous act of adding this was a **real-world breaking change, breaking linusback's docker container.**

**Comment by raspy8766** [comment]
Not certain if the fix from @paperdave will address it, but I just downgraded to 1.0.33 and it works successfully with a `.env.development` and a `.env.production` file as expected. However, when I define a `.env.local`, the `env.local` file env variables still take precedence over `.env.production`.

**Comment by paperclover** [comment]
i have noticed that .env.local has always taken precedence (can be seen all the way back in bun 1.0), and while i would like to change that, such would be a breaking change rather than a regression fix. i'm making some more changes to my pr, but it's going to specifically preserve this behavior.

**Comment by linusback** [comment]
@paperdave 
Thank you so much for the detailed explanation, it is indeed very interesting. I actually spent some time looking at the zig code, it looks like a fun language.

**Comment by gyohza** [comment]
We had the same problem and it took us a full day of debugging for us to fix our pipeline.

To be fair, we should've pinned our bun version in the pipeline. Fetching the latest version (1.0.35) broke it entirely, as it was not pointing to the correct environment.

Pinning the bun version in our pipeline to 1.0.26 fixed it. Lesson learned, I guess.

**Comment by Jarred-Sumner** [comment]
@gyohza very sorry about this. It was an unintentional breaking change caused by a lack of test coverage for this specific behavior. We broke it when we rewrote the code for spawning & waiting for processes to support Windows along with posix. We have a fix (including regression tests) and will merge the fix for this today and push a new release (Bun v1.0.36)

**Comment by paperclover** [comment]
Fixed in https://github.com/oven-sh/bun/pull/9689
