### ISSUE TITLE
Stuck shell on windows (nushell)

### ISSUE THREAD

**Issue by romancitodev** [oven-sh/bun#9811]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. Run any `bun` command. _(bun run dev)_
2. Send the Ctrl + C Signal.
3. Write anything.

![image](https://github.com/oven-sh/bun/assets/84428770/ff98453b-5926-4725-8100-3ff813e40260)

### What is the expected behavior?

The expected behaviour is just obtain control of the shell again.

**Comment by romancitodev** [comment]
In other shells like powershell, works correctly.

**Comment by pratikb64** [comment]
I can confirm this happens on win 11 also.

I have noticed few things by using:

nushell - only alphabets works. ctrl, alt, enter, backspace , etc. does not work. Arrow keys generate symbols ( [A [B [C [D )
cmd - everything works except backspace clears out whole words instead of single letters, Arrow keys generate symbols ( [A [B [C [D )
powershell - everything works normally.

**Comment by Barbiero** [comment]
related issue on nushell side https://github.com/nushell/nushell/issues/12355

Apparently, there are some attributes that are not cleaned up on windows after an interrupt

**Comment by dan-myles** [comment]
Having this exact same issue.

**Comment by itsMapleLeaf** [comment]
Want to come and note that this still happens with Nushell in v1.1.3 

![image](https://github.com/oven-sh/bun/assets/19603573/e5b34cb0-425a-4685-a447-56d6ac7a0de5)

**Comment by romancitodev** [comment]
Works for me with bun `v1.1.3` and nushell `0.91.0`.

![image](https://github.com/oven-sh/bun/assets/84428770/53e48b4c-5a09-4765-a8bd-3244ab6e2469)

_But I'm not going to close the issue because it may not work for someone else._

**Comment by itsMapleLeaf** [comment]
That's interesting, since the [issue reported earlier](https://github.com/nushell/nushell/issues/12355) was reported on 0.91.1. Regression in a patch release?

It could also be related to how the Vite CLI hooks into the keyboard for `h + enter`

EDIT: Can confirm. I disabled that message and keyboard handler with `logLevel: "warn"` in my vite config, and now it works fine.

**Comment by PAStheLoD** [comment]
Hello,

Just an additional data point. The error is reproducible on bun 1.1.7+b0b7db5c0 and nu 0.93.0  (In both Windows Terminal and in conhost.exe, win11 23H2 - 22631.3527)

Behavior is very similar to the [previous](https://github.com/oven-sh/bun/issues/9587) one.

**Comment by paperdave** [comment]
This was fixed sometime after bun 1.1. I can reproduce it on that version, but not on the latest one. I had a PR that touched some related code (#11927), but it does not regress this bug. Please open a new issue if it continues to occur.
